### ISSUE TITLE
stage2 crash when running behavior tests for aarch64 with LLVM backend

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#10837]
### Zig Version

0.10.0-dev.610+9bbfbacae

### Steps to Reproduce

Create a stage2 build, then run the behavior tests targeting aarch64.

```
./zig-out/bin/zig test ../test/behavior.zig -I../test -fLLVM -target aarch64-linux
```

### Expected Behavior

All tests passed.

### Actual Behavior

With a debug build of LLVM 13.0.1 I get this:

```
zig: /home/andy/Downloads/llvm-project-13/llvm/lib/IR/Constants.cpp:1253: llvm::ConstantAggregate::ConstantAggregate(llvm::Type*, llvm::Value::ValueTy, llvm::ArrayRef<llvm::Constant*>): Assertion `V[I]->getType() == ST->getTypeAtIndex(I) && "Initializer for struct element doesn't match!"' failed.

Thread 1 "zig" received signal SIGABRT, Aborted.
0x00007ffff7cbcbaa in raise () from /nix/store/kq5mfvarbjar95xahcf7kd5mfkc64qz3-glibc-2.33-78/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7cbcbaa in raise ()
   from /nix/store/kq5mfvarbjar95xahcf7kd5mfkc64qz3-glibc-2.33-78/lib/libc.so.6
#1  0x00007ffff7ca7523 in abort ()
   from /nix/store/kq5mfvarbjar95xahcf7kd5mfkc64qz3-glibc-2.33-78/lib/libc.so.6
#2  0x00007ffff7ca741f in __assert_fail_base.cold.0 ()
   from /nix/store/kq5mfvarbjar95xahcf7kd5mfkc64qz3-glibc-2.33-78/lib/libc.so.6
#3  0x00007ffff7cb55f2 in __assert_fail ()
   from /nix/store/kq5mfvarbjar95xahcf7kd5mfkc64qz3-glibc-2.33-78/lib/libc.so.6
#4  0x000000000dd54e7b in llvm::ConstantAggregate::ConstantAggregate (this=0xefe8a70, T=0xefc57f0, 
    VT=llvm::Value::ConstantStructVal, V=...)
    at /home/andy/Downloads/llvm-project-13/llvm/lib/IR/Constants.cpp:1253
#5  0x000000000dd553bc in llvm::ConstantStruct::ConstantStruct (this=0xefe8a70, T=0xefc57f0, V=...)
    at /home/andy/Downloads/llvm-project-13/llvm/lib/IR/Constants.cpp:1322
#6  0x000000000dd6a22b in llvm::ConstantAggrKeyType<llvm::ConstantStruct>::create (
    this=0x7ffffffedb70, Ty=0xefc57f0)
    at /home/andy/Downloads/llvm-project-13/llvm/lib/IR/ConstantsContext.h:448
#7  0x000000000dd67395 in llvm::ConstantUniqueMap<llvm::ConstantStruct>::create (this=0xedb8fd0, 
    Ty=0xefc57f0, V=..., HashKey=...)
    at /home/andy/Downloads/llvm-project-13/llvm/lib/IR/ConstantsContext.h:710
#8  0x000000000dd64293 in llvm::ConstantUniqueMap<llvm::ConstantStruct>::getOrCreate (this=0xedb8fd0, 
    Ty=0xefc57f0, V=...) at /home/andy/Downloads/llvm-project-13/llvm/lib/IR/ConstantsContext.h:729
#9  0x000000000dd5565e in llvm::ConstantStruct::get (ST=0xefc57f0, V=...)
    at /home/andy/Downloads/llvm-project-13/llvm/lib/IR/Constants.cpp:1360
#10 0x000000000dd7eb15 in LLVMConstNamedStruct (StructTy=0xefc57f0, ConstantVals=0xf005e80, Count=2)
    at /home/andy/Downloads/llvm-project-13/llvm/lib/IR/Core.cpp:1472
#11 0x0000000006f0ca47 in codegen.llvm.DeclGen.genTypedValue (dg=0x7ffffffef790, tv=...)
    at /home/andy/dev/zig/src/codegen/llvm.zig:1568
#12 0x0000000006eff2f2 in codegen.llvm.DeclGen.genDecl (dg=0x7ffffffef790)
    at /home/andy/dev/zig/src/codegen/llvm.zig:639
#13 0x0000000006efb292 in codegen.llvm.Object.updateDecl (self=0xedb6fa0, module=0xedb7f00, 
    decl=0xede9450) at /home/andy/dev/zig/src/codegen/llvm.zig:523
#14 0x0000000006c7f4fc in link.Elf.updateDecl (self=0xedb69d0, module=0xedb7f00, decl=0xede9450)
    at /home/andy/dev/zig/src/link/Elf.zig:2925
#15 0x0000000006c7ea7d in link.File.updateDecl (base=0xedb69d0, module=0xedb7f00, decl=0xede9450)
    at link.zig:460
#16 0x0000000006c7346d in Module.linkerUpdateDecl (mod=0xedb7f00, decl=0xede9450) at Module.zig:5262
#17 0x0000000006c6d35c in Compilation.processOneJob (comp=0xedb5ca8, job=..., 
    main_progress_node=0x7fffffff0510) at Compilation.zig:2712
```

This issue may be hiding another issue.

**Comment by andrewrk** [comment]
The assertion we are hitting is something already solved in stage1 with this:

```c++
// We have this because union constants can't be represented by the official union type,
// and this property bubbles up in whatever aggregate type contains a union constant
static bool is_llvm_value_unnamed_type(CodeGen *g, ZigType *type_entry, LLVMValueRef val) {
    return LLVMTypeOf(val) != get_llvm_type(g, type_entry);
}
```

**Comment by andrewrk** [comment]
After the fix in c10fdde5a64a46bc514500e97b8c87d19f86e431, there is a new problem uncovered:

```
zig: /home/andy/Downloads/llvm-project-13/llvm/lib/IR/Value.cpp:493: void llvm::Value::doRAUW(llvm::Value*, llvm::Value::ReplaceMetadataUses): Assertion `New->getType() == getType() && "replaceAllUses of value with new value of different type!"' failed.

Thread 1 "zig" received signal SIGABRT, Aborted.
0x00007ffff7cbcbaa in raise () from /nix/store/kq5mfvarbjar95xahcf7kd5mfkc64qz3-glibc-2.33-78/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7cbcbaa in raise ()
   from /nix/store/kq5mfvarbjar95xahcf7kd5mfkc64qz3-glibc-2.33-78/lib/libc.so.6
#1  0x00007ffff7ca7523 in abort ()
   from /nix/store/kq5mfvarbjar95xahcf7kd5mfkc64qz3-glibc-2.33-78/lib/libc.so.6
#2  0x00007ffff7ca741f in __assert_fail_base.cold.0 ()
   from /nix/store/kq5mfvarbjar95xahcf7kd5mfkc64qz3-glibc-2.33-78/lib/libc.so.6
#3  0x00007ffff7cb55f2 in __assert_fail ()
   from /nix/store/kq5mfvarbjar95xahcf7kd5mfkc64qz3-glibc-2.33-78/lib/libc.so.6
#4  0x000000000df37e57 in llvm::Value::doRAUW (this=0xf01ec90, New=0xf01f010, 
    ReplaceMetaUses=llvm::Value::ReplaceMetadataUses::Yes)
    at /home/andy/Downloads/llvm-project-13/llvm/lib/IR/Value.cpp:493
#5  0x000000000df37f9c in llvm::Value::replaceAllUsesWith (this=0xf01ec90, New=0xf01f010)
    at /home/andy/Downloads/llvm-project-13/llvm/lib/IR/Value.cpp:521
#6  0x000000000dd896cd in LLVMReplaceAllUsesWith (OldVal=0xf01ec90, NewVal=0xf01f010)
    at /home/andy/Downloads/llvm-project-13/llvm/lib/IR/Core.cpp:900
#7  0x0000000006f02679 in codegen.llvm.DeclGen.genDecl (dg=0x7ffffffef770)
    at /home/andy/dev/zig/src/codegen/llvm.zig:664
#8  0x0000000006efe452 in codegen.llvm.Object.updateDecl (self=0xedc4fc0, module=0xedc5f10, 
    decl=0xedf7660) at /home/andy/dev/zig/src/codegen/llvm.zig:523
#9  0x0000000006c827bc in link.Elf.updateDecl (self=0xedc49e0, module=0xedc5f10, decl=0xedf7660)
    at /home/andy/dev/zig/src/link/Elf.zig:2949
#10 0x0000000006c81d3d in link.File.updateDecl (base=0xedc49e0, module=0xedc5f10, decl=0xedf7660)
    at link.zig:460
#11 0x0000000006c7672d in Module.linkerUpdateDecl (mod=0xedc5f10, decl=0xedf7660) at Module.zig:5262
#12 0x0000000006c7061c in Compilation.processOneJob (comp=0xedc3cb8, job=..., 
    main_progress_node=0x7fffffff04e8) at Compilation.zig:2712
#13 0x0000000006c5c84e in Compilation.performAllTheWork (self=0xedc3cb8) at Compilation.zig:2676
#14 0x0000000006c559a5 in Compilation.update (comp=0xedc3cb8) at Compilation.zig:2082
#15 0x0000000006ebf31e in Compilation.buildOutputFromZig (comp=0xedb8638, src_basename=..., 
    output_mode=Lib, out=0xedb8980, misc_task_tag=compiler_rt) at Compilation.zig:4909
#16 0x0000000006c7223f in Compilation.processOneJob (comp=0xedb8638, job=..., 
    main_progress_node=0x7fffffff25e8) at Compilation.zig:3063
#17 0x0000000006c5c84e in Compilation.performAllTheWork (self=0xedb8638) at Compilation.zig:2676
#18 0x0000000006c559a5 in Compilation.update (comp=0xedb8638) at Compilation.zig:2082
#19 0x0000000006bb6be0 in updateModule (gpa=..., comp=0xedb8638, hook=...) at main.zig:2964
#20 0x0000000006b42ebe in buildOutputType (gpa=..., arena=..., all_args=..., arg_mode=...)
    at main.zig:2651
#21 0x0000000006b28257 in mainArgs (gpa=..., arena=..., args=...) at main.zig:216
#22 0x0000000006b27191 in main () at main.zig:165
#23 0x00000000070211c8 in std.start.callMain () at /home/andy/dev/zig/lib/std/start.zig:561
#24 0x0000000006b29cf8 in std.start.initEventLoopAndCallMain ()
    at /home/andy/dev/zig/lib/std/start.zig:495
#25 std.start.callMainWithArgs (argc=7, argv=0x7fffffffa7b8, envp=...)
    at /home/andy/dev/zig/lib/std/start.zig:445
#26 0x0000000006b29aa3 in std.start.main (c_argc=7, c_argv=0x7fffffffa7b8, c_envp=0x7fffffffa7f8)
    at /home/andy/dev/zig/lib/std/start.zig:460
(gdb) up
#1  0x00007ffff7ca7523 in abort ()
   from /nix/store/kq5mfvarbjar95xahcf7kd5mfkc64qz3-glibc-2.33-78/lib/libc.so.6
(gdb) 
#2  0x00007ffff7ca741f in __assert_fail_base.cold.0 ()
   from /nix/store/kq5mfvarbjar95xahcf7kd5mfkc64qz3-glibc-2.33-78/lib/libc.so.6
(gdb) 
#3  0x00007ffff7cb55f2 in __assert_fail ()
   from /nix/store/kq5mfvarbjar95xahcf7kd5mfkc64qz3-glibc-2.33-78/lib/libc.so.6
(gdb) 
#4  0x000000000df37e57 in llvm::Value::doRAUW (this=0xf01ec90, New=0xf01f010, 
    ReplaceMetaUses=llvm::Value::ReplaceMetadataUses::Yes)
    at /home/andy/Downloads/llvm-project-13/llvm/lib/IR/Value.cpp:493
493	  assert(New->getType() == getType() &&
(gdb) p New->dump()
@1 = internal unnamed_addr global { i6, { %target.Target.Os.LinuxVersionRange } } { i6 8, { %target.Target.Os.LinuxVersionRange } { %target.Target.Os.LinuxVersionRange { %builtin.Version.Range { %builtin.Version { i32 3, i32 16, i32 0 }, %builtin.Version { i32 5, i32 10, i32 81 } }, %builtin.Version { i32 2, i32 19, i32 0 } } } }, align 4
$1 = void
(gdb) p this->dump()
@builtin.os = internal unnamed_addr constant %target.Target.Os, align 4
$2 = void
```
