### ISSUE TITLE
zig cc -fsanatize=address fails at link time on macOS

### ISSUE THREAD

**Issue by drfuchs** [ziglang/zig#11403]
### Zig Version

0.10.0-dev.1736+93e11b824

### Steps to Reproduce

zig cc -fsanitize=address hello.c

Tried on "Apple M1 Pro macOS Monterey 12.3.1" as well as "Intel Core i7 macOS Catalina 10.15.7"

### Expected Behavior

Joy in Mudville

### Actual Behavior

zig cc -fsanitize=address hello.c
error(link): undefined reference to symbol '___asan_init'
error(link):   first referenced in '/Users/elided/.cache/zig/o/elided/hello.o'
error(link): undefined reference to symbol '___asan_register_image_globals'
error(link):   first referenced in '/Users/elided/.cache/zig/o/elided/hello.o'
error(link): undefined reference to symbol '___asan_unregister_image_globals'
error(link):   first referenced in '/Users/elided/.cache/zig/o/elided/hello.o'
error(link): undefined reference to symbol '___asan_version_mismatch_check_v8'
error(link):   first referenced in '/Users/elided/.cache/zig/o/elided/hello.o'
error: UndefinedSymbolReference

(On macOS Monterey, it also first complained:
warning(link): directory not found for '-L/usr/local/lib'
for what that's worth.)

**Comment by moosichu** [comment]
This is related to #5163 and #10374 - although applying to asan instead of ubsan.

**Comment by drfuchs** [comment]
(Just to add more color to this bug / lack of feature, in case it affects its prioritization:)

This issue interferes with Zig's "Maintain it with Zig: Incrementally improve your C/C++/Zig codebase" story.

Most directly, you can't use the advertised "drop-in C/C++ compiler" functionality of Zig for developing stand-alone C code while asan detection is crucial.  So all the fabulous advantages of being able to do so disappear.

More importantly, it also seems to interfere with taking existing C codebases that are in pretty good but perhaps not immaculate condition, and trying to incrementally port them to Zig: How can I compile and link and run such that something is keeping an eye on the malloc'd pointers used by the C code at runtime, while still being able to call into / out of Zig code that's also compiled in debug mode? Or even if my C code is perfect, perhaps I might call it in an incorrect way from my new Zig code, causing the C code to, say, dereference a free pointer, which still needs detecting.  

I'm willing to make any C-world pointer that round-trips through Zig code be a pointer to a type that's opaque to my Zig code (so that they never get dereferenced directly in the Zig code, and thus need no asan-like checking there), if that helps; or use something other than malloc/free from C; or whatever else might do the trick. 

Or did I perhaps miss the boat, and there's a currently-supported way to handle this, perhaps using regular "cc -fsanitize=address" on the C code, and "zig build-obj" on the zig code, and who-knows-what linker to put it all together (and pray that there are no conflicts about who owns main() and whose crt startup code gets included and what libraries I have to explicitly include, and etc.)? Will the solution work across platforms, even ignoring cross-compilation?

FWIW, I'm way more concerned about asan than general ubsan detection, based on the difficulty of tracking down the bugs that result when not automatically detected at the moment of initial transgression.

**Comment by prenaux** [comment]
I'll link https://github.com/ziglang/zig/issues/12992 here since I feel its related - to fully support C++ in zigcc on all targets.

**Comment by chadbrewbaker** [comment]
Here is how Apple is driving it in their unit tests, https://github.com/apple-oss-distributions/libmalloc/blob/387a5a03c017801ecdfe9cbe7f8d69a9b427df68/tests/asan.c#L13

Another reason why it would be nice to have all of MacOS libsystem building statically, so Zig could re-use Apple's own tests.

**Comment by chrisirhc** [comment]
Reproducible on linux x86_64 so this is not a mac-specific issue:
```bash
 % ./zig-linux-x86_64-0.11.0-dev.2368+f4b411314/zig cc -fsanitize=address  hello.c
LLD Link... ld.lld: error: undefined symbol: __asan_init
>>> referenced by hello.c
>>>               /home/user/.cache/zig/o/35face62758b9eaf253cfae70bafbb87/hello.o:(asan.module_ctor)

ld.lld: error: undefined symbol: __asan_version_mismatch_check_v8
>>> referenced by hello.c
>>>               /home/user/.cache/zig/o/35face62758b9eaf253cfae70bafbb87/hello.o:(asan.module_ctor)

ld.lld: error: undefined symbol: __asan_register_globals
>>> referenced by hello.c
>>>               /home/user/.cache/zig/o/35face62758b9eaf253cfae70bafbb87/hello.o:(asan.module_ctor)

ld.lld: error: undefined symbol: __asan_unregister_globals
>>> referenced by hello.c
>>>               /home/user/.cache/zig/o/35face62758b9eaf253cfae70bafbb87/hello.o:(asan.module_dtor)
```

**Comment by cdcarter** [comment]
Was trying to switch a C/bison side project of mine over to zig-build, but no AddressSanitizer on MacOS (12.1, M1 Pro CPU) means this project will have to stay with clang for now.

**Comment by g-berthiaume** [comment]
I had the same issue on windows 11

Please note that, the same command works with clang but not zig cc.

```powershell
# Will work
$ clang .\main.c .\pingpong.c -Wall -Wextra -Wpedantic -fsanitize=address -O0 -g3 -o .\appb.exe
   Creating library .\appb.lib and object .\appb.exp
# Will fail
$ zig cc .\main.c .\pingpong.c -Wall -Wextra -Wpedantic -fsanitize=address -O0 -g3 -o .\appb.exe
LLD Link... lld-link: error: undefined symbol: __asan_report_load1
[....]
```

Here's some info about my setup:
![image](https://github.com/ziglang/zig/assets/19377511/08d9a812-8b65-4de6-825f-2d3dc3eb898e)

**Comment by Warchant** [comment]
> I had the same issue on windows 11
> 
> Please note that, the same command works with clang but not zig cc.
> 
> ```powershell
> # Will work
> $ clang .\main.c .\pingpong.c -Wall -Wextra -Wpedantic -fsanitize=address -O0 -g3 -o .\appb.exe
>    Creating library .\appb.lib and object .\appb.exp
> # Will fail
> $ zig cc .\main.c .\pingpong.c -Wall -Wextra -Wpedantic -fsanitize=address -O0 -g3 -o .\appb.exe
> LLD Link... lld-link: error: undefined symbol: __asan_report_load1
> [....]
> ```
> 
> Here's some info about my setup: ![image](https://user-images.githubusercontent.com/19377511/275025824-08d9a812-8b65-4de6-825f-2d3dc3eb898e.png)

I just added -L$(ASAN_DIR) and -lasan to link flags, and now asan works. (Windows11, inside WSL2).


```bash
$ find /usr/lib -type f -name "libasan.*"
/usr/lib/gcc/x86_64-linux-gnu/11/libasan.a
/usr/lib/x86_64-linux-gnu/libasan.so.6.0.0
$ zig c++ -L/usr/lib/gcc/x86_64-linux-gnu/11 -lasan -fsanitize=address -o zig_bin 1.cpp
$ ./zig_bin
Hello World!

=================================================================
==10112==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x7f8a2046a1e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x201766 in main /mnt/c/W/cli/1/1.cpp:5
    #2 0x7f8a201b5d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

SUMMARY: AddressSanitizer: 4 byte(s) leaked in 1 allocation(s).
```

**Comment by g-berthiaume** [comment]
> I just added -L$(ASAN_DIR) and -lasan to link flags, and now asan works. (Windows11, inside WSL2).

Hi @Warchant. Thanks for your feedback.
It also worked on my machine when using those flags:

```txt
zig cc main.c -L/usr/lib/gcc/x86_64-linux-gnu/11/ -lasan -fsanitize=address -o main
```

**Comment by nevakrien** [comment]
same issue on windows 10

**Comment by miguno** [comment]
Similar issue on macOS 14.6.1.

**Comment by JacobHumphreys** [comment]
This is still occurring in zig 0.14.1 on x84_64 linux (nixos).


```
sh-5.2$ zig c++ --version
clang version 19.1.7
Target: x86_64-unknown-linux-gnu                                                                              Thread model: posix
InstalledDir: /nix/store/xfs50swh37h0qj78sfhsg8ppl41gi10z-zig-0.14.1/bin                                     

sh-5.2$ zig version
0.14.1
sh-5.2$ zig c++  ./src/*.cpp -o main
sh-5.2$ zig c++ -fsanitize=address ./src/*.cpp -o main
ld.lld: error: undefined symbol: __asan_option_detect_stack_use_after_return
>>> referenced by main.cpp:3 (./src/main.cpp:3)
...

```

**Comment by JacobHumphreys** [comment]
> > I just added -L$(ASAN_DIR) and -lasan to link flags, and now asan works. (Windows11, inside WSL2).
> 
> Hi [@Warchant](https://github.com/Warchant). Thanks for your feedback. It also worked on my machine when using those flags:
> 
> zig cc main.c -L/usr/lib/gcc/x86_64-linux-gnu/11/ -lasan -fsanitize=address -o main

This resolved the issue on  my machine as well.

Would anyone happen to know of a way to pass the -L/usr/lib/gcc/x86_64-linux-gnu/11/ -lasan linkage flags to the build system?

**Comment by Kyn21kx** [comment]
Just here to bump the attention to this issue a bit, I'm also experiencing this issue on Windows 11, zig version 0.14.0

<img width="1909" height="838" alt="Image" src="https://github.com/user-attachments/assets/0d1d8794-a25d-4b26-8ca7-a93513ed689f" />
