### ISSUE TITLE
stage2 segfault slicing zero length array field of struct

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig#11787]
```zig
pub export fn entry() void {
    const S = struct {
        a: [0]usize,
        fn foo(self: *@This(), start: usize, end: usize) []usize {
            return self.a[start..end];
        }
    };
    var s: S = undefined;
    _ = s.foo(0, 0);
}
```

Segfault happens in LLVM when doing `buildInBoundsGEP` in `airPtrAdd`.

**Comment by martinhath** [comment]
I've done a bunch of digging, and while I think I have narrowed the problem down to at least understand what's happening, I'm not sure what the best approach is for a fix.
Issue #6706 seems very related.


The segfault comes from a failed assertion:
```
zig: /home/mht/src/llvm-project-13/llvm/include/llvm/IR/Instructions.h:923: llvm::Type* llvm::checkGEPType(Type*): Assertion `Ty && "Invalid GetElementPtrInst indices for type!"' failed.
```

in the call to `buildInBoundsGEP`

https://github.com/ziglang/zig/blob/a12abc6d6c8b89a09befdcbd9019247ccc3bd641/src/codegen/llvm.zig#L6609-L6614


`base_ptr` and `offset` have these values:
```
(gdb) p (('llvm::Value' *) base_ptr)->dump()
  %5 = getelementptr inbounds i8, i8* %4, i64 1, !dbg !22
(gdb) p (('llvm::Value' *) base_ptr)->getType()->dump()
i8*
(gdb) p (('llvm::Value' *) offset)->dump()
i64 %1
```


There were two things that I was confused about: (1) why `base_ptr` is a `i8*`, and (2) why we've got a `i64 1` in the GEP.

(1) is due to

https://github.com/ziglang/zig/blob/a12abc6d6c8b89a09befdcbd9019247ccc3bd641/src/codegen/llvm.zig#L2561-L2570

I.e. we're lowering pointers to all zero-sized types to `*i8`.


(2) is due to

https://github.com/ziglang/zig/blob/a12abc6d6c8b89a09befdcbd9019247ccc3bd641/src/codegen/llvm.zig#L8899-L8911



From what I can tell, LLVM is complaining about the indices because we're indexing with a `i32` (which is for struct fields) and then a `i64` (pointer offsets), and our base type is just a `*i8`, so the first indexing doesn't really make sense.

The lowering to `*i8` does *not* happen if we have a pointer directly to the zero-sized array though; in that case it is lowered to a `[0 x i64]*`, which I think is telling that we're doing something weird here.



<details>
<summary>Code to reproduce</summary>

```zig
const S = struct {
    a: [0]usize,
};

fn foo(s: *S, start: usize, end: usize) []usize {
    return s.a[start..end];
}

pub export fn entry() void {
    var s = S{ .a = .{}, };
    _ = foo(&s, 0, 0);
}
```


</details>


<details>
<summary>AIR for the snippet</summary>

```
%0 = arg(*11787.S)
%1 = arg(usize)
%2 = arg(usize)
%3!= dbg_block_begin()
%4!= dbg_stmt(2:5)
%6 = alloc(**11787.S)
%8!= store(%6, %0!)
%10 = bitcast(*const *11787.S, %6!)
%12 = load(*11787.S, %10!)
%14 = struct_field_ptr_index_0(*[0]usize, %12!)
%16 = ptr_add(%14!, %1)
%18 = sub_with_overflow(%2, %1)
%19 = struct_field_val(%18, 1)
%21 = cmp_eq(%19!, %20!)
%41!= block(void, {
  %42!= cond_br(%21!, {
    %24! %31! %39!
    %43!= br(%41, @Zir.Inst.Ref.void_value)
  }, {
    %40!= call(%31!, [%24!, %39!])
  })
})
%44 = struct_field_val(%18!, 0)
%46 = cmp_lte(%2, %45)
%55!= block(void, {
  %56!= cond_br(%46!, {
    %45!
    %57!= br(%55, @Zir.Inst.Ref.void_value)
  }, {
    %54!= call(%53, [%2, %45!])
  })
})
%58 = cmp_lte(%1, %2)
%63!= block(void, {
  %64!= cond_br(%58!, {
    %1! %53! %2!
    %65!= br(%63, @Zir.Inst.Ref.void_value)
  }, {
    %62!= call(%53!, [%1!, %2!])
  })
})
%67 = slice(%16!, %44!)
%68!= dbg_stmt(2:5)
%69!= dbg_block_end()
%70!= ret(%67!)
```

</details>

<details>
<summary>Full stack trace</summary>

```
Thread 1 "zig" received signal SIGABRT, Aborted.
0x00007ffff7c8e36c in ?? () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7c8e36c in ?? () from /lib64/libc.so.6
#1  0x00007ffff7c3e838 in raise () from /lib64/libc.so.6
#2  0x00007ffff7c28535 in abort () from /lib64/libc.so.6
#3  0x00007ffff7c2845c in ?? () from /lib64/libc.so.6
#4  0x00007ffff7c37366 in __assert_fail () from /lib64/libc.so.6
#5  0x00000000082df6ab in llvm::checkGEPType (Ty=0x0) at /home/mht/src/llvm-project-13/llvm/include/llvm/IR/Instructions.h:923
#6  0x00000000082df88f in llvm::GetElementPtrInst::getGEPReturnType (ElTy=0xff16aa8, Ptr=0xff510c0, IdxList=...)
    at /home/mht/src/llvm-project-13/llvm/include/llvm/IR/Instructions.h:1080
#7  0x00000000082dfa25 in llvm::GetElementPtrInst::GetElementPtrInst (this=0xff4d750, PointeeType=0xff16aa8, Ptr=0xff510c0,
    IdxList=..., Values=3, NameStr=..., InsertBefore=0x0) at /home/mht/src/llvm-project-13/llvm/include/llvm/IR/Instructions.h:1157
#8  0x00000000082df7a9 in llvm::GetElementPtrInst::Create (PointeeType=0xff16aa8, Ptr=0xff510c0, IdxList=..., NameStr=...,
    InsertBefore=0x0) at /home/mht/src/llvm-project-13/llvm/include/llvm/IR/Instructions.h:965
#9  0x00000000082df7ff in llvm::GetElementPtrInst::CreateInBounds (PointeeType=0xff16aa8, Ptr=0xff510c0, IdxList=..., NameStr=...,
    InsertBefore=0x0) at /home/mht/src/llvm-project-13/llvm/include/llvm/IR/Instructions.h:987
#10 0x0000000008af4e16 in llvm::IRBuilderBase::CreateInBoundsGEP (this=0xff47110, Ty=0xff16aa8, Ptr=0xff510c0, IdxList=...,
    Name=...) at /home/mht/src/llvm-project-13/llvm/include/llvm/IR/IRBuilder.h:1746
#11 0x000000000a6c382c in LLVMBuildInBoundsGEP (B=0xff47110, Pointer=0xff510c0, Indices=0x7fffffff20e8, NumIndices=2,
    Name=0x32c527 <__unnamed_1900> "") at /home/mht/src/llvm-project-13/llvm/lib/IR/Core.cpp:3714
#12 0x00000000074c2bf9 in codegen.llvm.FuncGen.airPtrAdd (self=0x7fffffff37c0, inst=16)
    at /home/mht/src/zig/src/codegen/llvm.zig:6593
#13 0x00000000074b01f4 in codegen.llvm.FuncGen.genBody (self=0x7fffffff37c0, body=...)
    at /home/mht/src/zig/src/codegen/llvm.zig:4104
#14 0x00000000074ad88c in codegen.llvm.Object.updateFunc (o=0xff16050, module=0xff14db8, func=0xff47e80, air=..., liveness=...)
    at /home/mht/src/zig/src/codegen/llvm.zig:1026
#15 0x000000000725f6d8 in link.Elf.updateFunc (self=0xff15950, module=0xff14db8, func=0xff47e80, air=..., liveness=...)
    at /home/mht/src/zig/src/link/Elf.zig:2386
#16 0x000000000707d25e in link.File.updateFunc (base=0xff15950, module=0xff14db8, func=0xff47e80, air=..., liveness=...)
    at link.zig:510
#17 0x000000000705d503 in Module.ensureFuncBodyAnalyzed (mod=0xff14db8, func=0xff47e80) at Module.zig:4249
#18 0x0000000006d9b49b in Compilation.processOneJob (comp=0xff13d88, job=...) at Compilation.zig:2966
#19 0x0000000006d848fe in Compilation.performAllTheWork (comp=0xff13d88, main_progress_node=0x7fffffff5770) at Compilation.zig:2898
#20 0x0000000006d7cdf4 in Compilation.update (comp=0xff13d88) at Compilation.zig:2238
#21 0x0000000006ceb850 in updateModule (gpa=..., comp=0xff13d88, hook=...) at main.zig:3327
#22 0x0000000006cb4015 in buildOutputType (gpa=..., arena=..., all_args=..., arg_mode=...) at main.zig:3016
#23 0x0000000006c97d12 in mainArgs (gpa=..., arena=..., args=...) at main.zig:234
#24 0x0000000006c96e35 in main () at main.zig:174
#25 0x0000000006c99760 in std.start.callMain () at /home/mht/src/zig/lib/std/start.zig:576
#26 std.start.initEventLoopAndCallMain () at /home/mht/src/zig/lib/std/start.zig:510
#27 std.start.callMainWithArgs (argc=7, argv=0x7fffffffe0f8, envp=...) at /home/mht/src/zig/lib/std/start.zig:460
#28 std.start.main (c_argc=7, c_argv=0x7fffffffe0f8, c_envp=0x7fffffffe138) at /home/mht/src/zig/lib/std/start.zig:475
```

</details>

**Comment by davidgm94** [comment]
This is no longer crashing
