### ISSUE TITLE
Segmentation fault when linking with shared library

### ISSUE THREAD

**Issue by hdante** [ziglang/zig#12010]
Hello, I'm getting a segfault when executing the following trivial program:

```zig
const std = @import("std");
const stdout = std.io.getStdOut().writer();

extern fn add(a: c_int, b: c_int) c_int;

pub fn main() !void {
        const a: c_int = 1;
        const b: c_int = 2;
        const c = add(1, 2);

        try stdout.print("{} + {} = {}\n", .{a, b, c});
}
```

```c
int add(int a, int b)
{
	return a+b;
}
```

    $ cc -shared -nostdlib -o libadd.so add.c
    $ zig build-exe -dynamic shared.zig  -l ./libadd.so
    $ ./shared
    Segmentation fault at address 0x0
    ???:?:?: 0x0 in ??? (???)
    /usr/lib/zig/std/start.zig:561:37: 0x22430a in std.start.callMain (shared)
                const result = root.main() catch |err| {
                                        ^
    /usr/lib/zig/std/start.zig:495:12: 0x205667 in std.start.callMainWithArgs (shared)
        return @call(.{ .modifier = .always_inline }, callMain, .{});
               ^
    /usr/lib/zig/std/start.zig:409:17: 0x204764 in std.start.posixCallMainAndExit (shared)
        std.os.exit(@call(.{ .modifier = .always_inline }, callMainWithArgs, .{ argc, argv, envp }));
                    ^
    /usr/lib/zig/std/start.zig:322:5: 0x204571 in std.start._start (shared)
        @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
        ^
    Aborted (core dumped)

Hint: the resulting executable does not have an entry for the dynamic linker on its program headers:

    $ readelf -lW ./shared

    (...)
    Program Headers:
      Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
      PHDR           0x000040 0x0000000000200040 0x0000000000200040 0x0001f8 0x0001f8 R   0x8
      LOAD           0x000000 0x0000000000200000 0x0000000000200000 0x002490 0x002490 R   0x1000
      LOAD           0x002490 0x0000000000203490 0x0000000000203490 0x030bf0 0x030bf0 R E 0x1000
      LOAD           0x033080 0x0000000000235080 0x0000000000235080 0x001480 0x001480 RW  0x1000
      LOAD           0x034500 0x0000000000237500 0x0000000000237500 0x000020 0x003c64 RW  0x1000
      TLS            0x033080 0x0000000000234080 0x0000000000234080 0x000000 0x000018 R   0x8
      DYNAMIC        0x034428 0x0000000000236428 0x0000000000236428 0x0000d0 0x0000d0 RW  0x8
      GNU_RELRO      0x033080 0x0000000000235080 0x0000000000235080 0x001480 0x001f80 R   0x1
      GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x1000000 RW  0
    (...)

The current workaround seems to be linking with libc:

    $ zig build-exe -dynamic shared.zig  -lc -l ./libadd.so
    $ ./shared
    1 + 2 = 3

In this case, the executable contains an entry for the dynamic linker:

    $ readelf -lW ./shared
    
    (...)
    Program Headers:
      Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
      PHDR           0x000040 0x0000000000200040 0x0000000000200040 0x000268 0x000268 R   0x8
      INTERP         0x0002a8 0x00000000002002a8 0x00000000002002a8 0x00001c 0x00001c R   0x1
          [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
      LOAD           0x000000 0x0000000000200000 0x0000000000200000 0x002f6c 0x002f6c R   0x1000
      LOAD           0x002f70 0x0000000000203f70 0x0000000000203f70 0x034d80 0x034d80 R E 0x1000
      LOAD           0x037cf0 0x0000000000239cf0 0x0000000000239cf0 0x001468 0x001468 RW  0x1000
      LOAD           0x039158 0x000000000023c158 0x000000000023c158 0x0000c8 0x0001a8 RW  0x1000
      TLS            0x037cf0 0x0000000000238cf0 0x0000000000238cf0 0x000000 0x000018 R   0x8
      DYNAMIC        0x038fd0 0x000000000023afd0 0x000000000023afd0 0x000170 0x000170 RW  0x8
      GNU_RELRO      0x037cf0 0x0000000000239cf0 0x0000000000239cf0 0x001468 0x002310 R   0x1
      GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x1000000 RW  0
      NOTE           0x0002c4 0x00000000002002c4 0x00000000002002c4 0x000020 0x000020 R   0x4
    (...)

**Comment by nektro** [comment]
should it not be `$ zig build-exe -dynamic shared.zig -L. -ladd` ?

**Comment by hdante** [comment]
> should it not be `$ zig build-exe -dynamic shared.zig -L. -ladd` ?

That should give an identical result when using these parameters with a C compiler, but unfortunately `zig -L` adds a RUNPATH entry on the binary, which is undesired:

    0x000000000000001d (RUNPATH)            Library runpath: [.]

For sample programs this should make no difference, but for production code, this makes a big difference (it changes the program behavior depending on the files in the named directory). This looks like another (usability) bug to me, so I'm using `-l` with the library path, at least for the sample program.

Anyway, using either syntax changes nothing in this bug report.

**Comment by matdibu** [comment]
I stumbled upon the same thing when following the example at https://ziglang.org/learn/build-system/#dynamic-library, using zig 0.12.0

The output from `ldd` looks identical between the executables (with and without `demo.linkLibC();`)

Attempting to run the broken binary under gdb I got no useful info
```
Reading symbols from demo.nolibc...
(gdb) r
Starting program: demo.nolibc 

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt full
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.
```

Even if it's not meant to work without libc, it would be nice if it gave some clues

**Comment by matdibu** [comment]
In the context of the fizzbuzz library+demo on https://ziglang.org/learn/build-system/#dynamic-library


```zig
const libfizzbuzz = b.addSharedLibrary(.{
    .name = "fizzbuzz",
    .root_source_file = b.path("lib/fizzbuzz.zig"),
    .target = target,
    .optimize = optimize,
});

const demo = b.addExecutable(.{
    .name = "demo",
    .root_source_file = b.path("bin/demo.zig"),
    .target = target,
    .optimize = optimize,
    .linkage = .dynamic,
    // .link_libc = true,
});

demo.linkLibrary(libfizzbuzz);
```

| Library type  | demo.link_libc |  demo.linkage | result |
| ------------- | ------------- |------------- |------------- |
| static  | false  | static        | ok  |
| static  | false  | dynamic      | ok  |
| static  | true  | static      | error: libc of the specified target requires dynamic linking  |
| static  | true  | dynamic      | ok  |
| static  | not specified  | not specified      | ok  |
| shared  | false  | static      | error: using shared libraries requires dynamic linking  |
| shared  | false  | dynamic      | segfault  |
| shared  | true  | static      | error: libc of the specified target requires dynamic linking  |
| shared  | true  | dynamic      | ok  |
| shared  | not specified  | not specified      | segfault  |

**Comment by matdibu** [comment]
Also reproduced with zig version `0.13.0-dev.249+ed75f6256`

**Comment by matdibu** [comment]
the shared library + unspecified `demo.link_libc` and `demo.linkage` combo is able to print to stdout, but it crashes as soon as it tries to call into the function from the shared library

**Comment by matdibu** [comment]
under `lldb`, when issuing an `image list` I can see that the fizzbuzz library is loaded only when `link_libc=true`
```
(lldb) image list
[  0] 4C66C7CA 0x0000000001000000 /home/mateidibu/git/personal/xfs_undelete/zig-out/bin/demo 
[  1] 1F0B799E-8FA1-BC84-81E2-EE7B1D4D5AAC-4B9FCB48 0x00007ffff7fc8000 /nix/store/apab5i73dqa09wx0q27b6fbhd1r18ihl-glibc-2.39-31/lib/ld-linux-x86-64.so.2 
[  2] 2D05501D-1741-7E75-802F-5EF7CD68F6EE-70E4E687 0x00007ffff7fc6000 [vdso] (0x00007ffff7fc6000)
[  3] 459394C3 0x00007ffff7fbc000 zig-out/lib/libfizzbuzz.so 
[  4] CFD0ADEA-AED7-D46A-3790-28CC9694FC95-DD125976 0x00007ffff7dcf000 /nix/store/apab5i73dqa09wx0q27b6fbhd1r18ihl-glibc-2.39-31/lib/libc.so.6 
```

when not linking against libc, it no longer loads:
```
[  0] 878A78AC 0x0000000001000000 /home/mateidibu/git/personal/xfs_undelete/zig-out/bin/demo 
[  1] 2D05501D-1741-7E75-802F-5EF7CD68F6EE-70E4E687 0x00007ffff7ffd000 [vdso] (0x00007ffff7ffd000)
```

**Comment by matdibu** [comment]
if I understand correctly, glibc is not linked against by default, but a libc implementation is required for dynamic linking

some sort of warning when trying to dynamically link without a libc implementation could be useful

in retrospective, it was obvious that you need (g)libc if you want to `demo.linkLibrary(libfizzbuzz);` where `libfizzbuzz` is a shared library

**Comment by matdibu** [comment]
for anyone retracing my steps, [this series of articles (part 14 in particular)](https://fasterthanli.me/series/making-our-own-executable-packer/part-14) has some great insight
