### ISSUE TITLE
Immediate segfault when linking with libc

### ISSUE THREAD

**Issue by Ogromny** [ziglang/zig#13052]
### Zig Version

0.9.1

### Steps to Reproduce

main.zig:
```zig
const c = @cImport({
    @cInclude("stdlib.h");
});

pub fn main() !void {
    c.exit(10);
}
```

```sh
zig build-exe main.zig -lc
./main
```

### Expected Behavior

Successful run (`echo $?` == `10`)

### Actual Behavior

It `Segmentation fault`...

PS: My glibc version is 2.36

**Comment by nektro** [comment]
does this reproduce on master?

**Comment by Ogromny** [comment]
Yes I tried with `zig-linux-x86_64-0.10.0-dev.4217+9d8cdb855`, and same thing. It `Segmentation fault`.

I tried to `gdb` it, and that's what I got, I don't know if it can help 
```sh
~/Code/Zig/Test_c $ ./zig-linux-x86_64-0.10.0-dev.4217+9d8cdb855/zig build-exe main.zig -lc -O Debug 
~/Code/Zig/Test_c $ ./main
Segmentation fault 
~/Code/Zig/Test_c $ gdb ./main
Reading symbols from ./main...
(gdb) r
Starting program: /home/ogromny/Code/Zig/Test_c/main 

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000000210ca1 in _start ()
(gdb) 
```

**Comment by Ogromny** [comment]
Oh that's weird:
```zig
// ./zig-linux-x86_64-0.10.0-dev.4217+9d8cdb855/zig build-exe main.zig -lc -O Debug --show-builtin                  
const std = @import("std");
/// Zig version. When writing code that supports multiple versions of Zig, prefer
/// feature detection (i.e. with `@hasDecl` or `@hasField`) over version checks.
pub const zig_version = std.SemanticVersion.parse("0.10.0-dev.4217+9d8cdb855") catch unreachable;
pub const zig_backend = std.builtin.CompilerBackend.stage2_llvm;

pub const output_mode = std.builtin.OutputMode.Exe;
pub const link_mode = std.builtin.LinkMode.Dynamic;
pub const is_test = false;
pub const single_threaded = false;
pub const abi = std.Target.Abi.musl;
pub const cpu: std.Target.Cpu = .{
    .arch = .x86_64,
    .model = &std.Target.x86.cpu.x86_64,
    .features = std.Target.x86.featureSet(&[_]std.Target.x86.Feature{
        .@"64bit",
        .adx,
        .aes,
        .avx,
        .avx2,
        .bmi,
        .bmi2,
        .clflushopt,
        .cmov,
        .cx16,
        .cx8,
        .f16c,
        .fma,
        .fsgsbase,
        .fxsr,
        .idivq_to_divl,
        .invpcid,
        .lzcnt,
        .macrofusion,
        .mmx,
        .movbe,
        .nopl,
        .pclmul,
        .pku,
        .popcnt,
        .prfchw,
        .rdrnd,
        .rdseed,
        .sahf,
        .sgx,
        .slow_3ops_lea,
        .slow_incdec,
        .sse,
        .sse2,
        .sse3,
        .sse4_1,
        .sse4_2,
        .ssse3,
        .vzeroupper,
        .x87,
        .xsave,
        .xsavec,
        .xsaveopt,
        .xsaves,
    }),
};
pub const os = std.Target.Os{
    .tag = .linux,
    .version_range = .{ .linux = .{
        .range = .{
            .min = .{
                .major = 5,
                .minor = 15,
                .patch = 68,
            },
            .max = .{
                .major = 5,
                .minor = 15,
                .patch = 68,
            },
        },
        .glibc = .{
            .major = 2,
            .minor = 19,
            .patch = 0,
        },
    }},
};
pub const target = std.Target{
    .cpu = cpu,
    .os = os,
    .abi = abi,
    .ofmt = object_format,
};
pub const object_format = std.Target.ObjectFormat.elf;
pub const mode = std.builtin.Mode.Debug;
pub const link_libc = true;
pub const link_libcpp = false;
pub const have_error_return_tracing = true;
pub const valgrind_support = true;
pub const sanitize_thread = false;
pub const position_independent_code = true;
pub const position_independent_executable = false;
pub const strip_debug_info = false;
pub const code_model = std.builtin.CodeModel.default;
```

Why is the target set to musl ?
```zig
pub const abi = std.Target.Abi.musl;
```

Setting the target manually work as expected:
```sh
~/Code/Zig/Test_c $ ./zig-linux-x86_64-0.10.0-dev.4217+9d8cdb855/zig build-exe main.zig -lc -O Debug -target x86_64-linux-gnu 
~/Code/Zig/Test_c $ ./main                                                                                                                                                                                         
~/Code/Zig/Test_c $ echo $?
10
~/Code/Zig/Test_c $ 
```

I was using musl in the past though, so I think that's probably not a zig issue, but an OS issue...

**Comment by kassane** [comment]
I had the same problem with version `0.10.0-dev.4217+9d8cdb855` even when using `zig cc` and `zig c++`.

I can't enable the builtin to `glibc` and `libc++` being always false, except for target musl.

**Comment by nektro** [comment]
what does `ldd ./main` print?

**Comment by Ogromny** [comment]
```
~/Code/Zig/Test_c $ zig build-exe main.zig -lc
~/Code/Zig/Test_c $ ldd ./main                                          
././main: error while loading shared libraries: /usr/lib/libc.so: invalid ELF header
```
```
~/Code/Zig/Test_c $ zig build-exe main.zig -lc -target x86_64-linux-gnu 
~/Code/Zig/Test_c $ ldd ./main                                          
	linux-vdso.so.1 => linux-vdso.so.1 (0x00007ffedbfe5000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fdc16046000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fdc15e49000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib/ld-linux-x86-64.so.2 (0x00007fdc16052000)
~/Code/Zig/Test_c $ 
```

**Comment by nektro** [comment]
what distro?

**Comment by Ogromny** [comment]
> what distro?

Kisslinux (with glibc instead of musl)

**Comment by remeh** [comment]
Hey :wave: 

While working on a project where I link various C libraries (both from the systems and from provided `.so`/`.dylib`), I think I've hit the same issues on Fedora 36, but with the same project, I've no problem on macOS.

Adding a call to ` linkLibC()`  in my `build.zig`  solved it on Fedora (while I don't need to call this on macOS).

HTH.

**Comment by Ogromny** [comment]
Closing, the problem came from my system (dirty switch from musl to glibc), not related to zig
