### ISSUE TITLE
zig build-obj crashes with SIGSEGV

### ISSUE THREAD

**Issue by KAction** [ziglang/zig#13658]
### Zig Version

0.11.0-dev.251+7c527c6df

### Steps to Reproduce and Observed Behavior

Attached tarball with four files: `dynlib.h`, `dynlib.zig`, `crash.sh` and `core`. Script `crash.sh` contains command line invocation that tries to build `dynlib.o` from `dynlib.zig`, but crashes with SIGSEGV. Core files is generated on my system (glibc-based NixOS, fwiw) included.
[zig-crash.tar.gz](https://github.com/ziglang/zig/files/10096957/zig-crash.tar.gz)

### Expected Behavior

Object file is generated.

**Comment by KAction** [comment]
Core file is probably useless, though: gdb output is not enlightening at all:
```
Core was generated by `zig build-obj -lc -I. libdyn.zig'.
Program terminated with signal SIGSEGV, Segmentation fault.
--Type <RET> for more, q to quit, c to continue without paging--
#0  0x0000000007377a7b in ?? ()
[Current thread is 1 (LWP 434912)]
(gdb) bt
#0  0x0000000007377a7b in ?? ()
#1  0x0000000007395a9f in ?? ()
#2  0x000000000737a626 in ?? ()
#3  0x00000000073b030d in ?? ()
#4  0x00000000073a2c71 in ?? ()
#5  0x000000000737816b in ?? ()
#6  0x0000000007383411 in ?? ()
#7  0x000000000737d123 in ?? ()
#8  0x00000000073756dc in ?? ()
#9  0x000000000733c1bf in ?? ()
#10 0x00000000077b6fd9 in ?? ()
#11 0x0000000007a44568 in ?? ()
#12 0x0000000007a455c4 in ?? ()
#13 0x0000000007a63027 in ?? ()
#14 0x0000000007bf816a in ?? ()
#15 0x0000000000000000 in ?? ()

```

**Comment by KAction** [comment]
FWIW, bug exists in zig=0.9.1 that is part of nixpkgs master.

**Comment by KAction** [comment]
This time I have debugging symbols, which may be useful:

```
           PID: 442787 (zig)
           UID: 1000 (kaction)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Sat 2022-11-26 15:24:21 EST (1min 39s ago)
  Command Line: zig build-obj -lc -I. libdyn.zig
    Executable: /nix/store/j7hjcxl1bgdhw6wshcdvg4g6s6ihilfk-zig-0.9.1/bin/zig
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (kaction)
       Boot ID: bec305801f6047cdbddb4f457526241b
    Machine ID: b779c0f90c494faf94947e215b58561e
      Hostname: despise
       Storage: /var/lib/systemd/coredump/core.zig.1000.bec305801f6047cdbddb4f457526241b.442787.1669494261000000.zst (present)
     Disk Size: 1.3M
       Message: Process 442787 (zig) of user 1000 dumped core.
                
                Module linux-vdso.so.1 with build-id 5d28cbcbf579cfeda52860ed74c26e761ea39cb3
                Module libxml2.so.2 without build-id.
                Module libncursesw.so.6 without build-id.
                Module libz.so.1 without build-id.
                Module libdl.so.2 with build-id 67c430223def0be24c4ae1a4c3985f26566b8831
                Module librt.so.1 with build-id 7c9aae26f0646a27bf0f7c49c914b3258c5fa43e
                Module libffi.so.8 without build-id.
                Module ld-linux-x86-64.so.2 with build-id db50353a26600bb848b9a5541b1506e0a24cb34b
                Module libc.so.6 with build-id 2bb226bc600b443958c7566207d0d02f8345e6ea
                Module libgcc_s.so.1 without build-id.
                Module libm.so.6 with build-id b8454b40db819599169f3a948939aed4b3fc7f82
                Module libstdc++.so.6 without build-id.
                Module libLLVM-13.so with build-id 32ef532475d38c2564126683ac115854e03212e0
                Module zig without build-id.
                Stack trace of thread 442798:
                #0  0x0000000000a220ab AstGen.WipMembers.finishBits (zig + 0x6220ab)
                #1  0x0000000000000000 n/a (n/a + 0x0)
                #2  0x0000000000a94933 AstGen.ifExpr (zig + 0x694933)
                #3  0x0000000000a21b79 AstGen.expr (zig + 0x621b79)
                #4  0x0000000000b6c469 AstGen.unusedResultExpr (zig + 0x76c469)
                #5  0x0000000000b097f6 AstGen.blockExprStmts (zig + 0x7097f6)
                #6  0x0000000000a9752f AstGen.blockExpr (zig + 0x69752f)
                #7  0x0000000000a208d2 AstGen.expr (zig + 0x6208d2)
                #8  0x0000000000a8b22d AstGen.fnDecl (zig + 0x68b22d)
                #9  0x0000000000a1f6ad AstGen.containerMember (zig + 0x61f6ad)
                #10 0x000000000099127e AstGen.structDeclInner (zig + 0x59127e)
                #11 0x0000000000899a25 AstGen.generate (zig + 0x499a25)
                #12 0x000000000099c2b5 Module.astGenFile (zig + 0x59c2b5)
                #13 0x0000000000999d3a Compilation.workerAstGenFile (zig + 0x599d3a)
                #14 0x000000000099d390 ThreadPool.Closure.runFn.3868 (zig + 0x59d390)
                #15 0x00000000009960a8 std.Thread.Instance.entryFn (zig + 0x5960a8)
                #16 0x00007f57652a9e86 start_thread (libc.so.6 + 0x88e86)
                #17 0x00007f5765330c60 __clone3 (libc.so.6 + 0x10fc60)
                
                Stack trace of thread 442790:
                #0  0x00007f57652a67d5 __futex_abstimed_wait_common (libc.so.6 + 0x857d5)
                #1  0x00007f57652b1ef8 __new_sem_wait_slow64.constprop.0 (libc.so.6 + 0x90ef8)
                #2  0x0000000000996118 std.Thread.Instance.entryFn (zig + 0x596118)
                #3  0x00007f57652a9e86 start_thread (libc.so.6 + 0x88e86)
                #4  0x00007f5765330c60 __clone3 (libc.so.6 + 0x10fc60)
                
                Stack trace of thread 442800:
                #0  0x00007f57652a67d5 __futex_abstimed_wait_common (libc.so.6 + 0x857d5)
                #1  0x00007f57652b1ef8 __new_sem_wait_slow64.constprop.0 (libc.so.6 + 0x90ef8)
                #2  0x0000000000996118 std.Thread.Instance.entryFn (zig + 0x596118)
                #3  0x00007f57652a9e86 start_thread (libc.so.6 + 0x88e86)
                #4  0x00007f5765330c60 __clone3 (libc.so.6 + 0x10fc60)
                
                Stack trace of thread 442803:
                #0  0x00007f57652b944c _int_malloc (libc.so.6 + 0x9844c)
                #1  0x00007f57652b9cf7 __libc_malloc (libc.so.6 + 0x98cf7)
                #2  0x00007f57652bb613 posix_memalign (libc.so.6 + 0x9a613)
                #3  0x000000000083eeda std.heap.CAllocator.alloc (zig + 0x43eeda)
                #4  0x00000000008a4452 std.mem.Allocator.reallocAdvancedWithRetAddr.1044 (zig + 0x4a4452)
                #5  0x0000000000b002ae AstGen.strLitAsString (zig + 0x7002ae)
                #6  0x0000000000a905ef AstGen.builtinCall (zig + 0x6905ef)
                #7  0x0000000000a21eac AstGen.expr (zig + 0x621eac)
                #8  0x0000000000a8b913 AstGen.globalVarDecl (zig + 0x68b913)
                #9  0x0000000000a1e52d AstGen.containerMember (zig + 0x61e52d)
                #10 0x000000000099127e AstGen.structDeclInner (zig + 0x59127e)
                #11 0x0000000000899a25 AstGen.generate (zig + 0x499a25)
                #12 0x000000000099c2b5 Module.astGenFile (zig + 0x59c2b5)
                #13 0x0000000000999d3a Compilation.workerAstGenFile (zig + 0x599d3a)
                #14 0x000000000099d390 ThreadPool.Closure.runFn.3868 (zig + 0x59d390)
                #15 0x00000000009960a8 std.Thread.Instance.entryFn (zig + 0x5960a8)
                #16 0x00007f57652a9e86 start_thread (libc.so.6 + 0x88e86)
                #17 0x00007f5765330c60 __clone3 (libc.so.6 + 0x10fc60)
                
                Stack trace of thread 442794:
                #0  0x00007f57652a67d5 __futex_abstimed_wait_common (libc.so.6 + 0x857d5)
                #1  0x00007f57652b1ef8 __new_sem_wait_slow64.constprop.0 (libc.so.6 + 0x90ef8)
                #2  0x0000000000996118 std.Thread.Instance.entryFn (zig + 0x596118)
                #3  0x00007f57652a9e86 start_thread (libc.so.6 + 0x88e86)
                #4  0x00007f5765330c60 __clone3 (libc.so.6 + 0x10fc60)
                
                Stack trace of thread 442791:
                #0  0x00007f57652a67d5 __futex_abstimed_wait_common (libc.so.6 + 0x857d5)
                #1  0x00007f57652b1ef8 __new_sem_wait_slow64.constprop.0 (libc.so.6 + 0x90ef8)
                #2  0x0000000000996118 std.Thread.Instance.entryFn (zig + 0x596118)
                #3  0x00007f57652a9e86 start_thread (libc.so.6 + 0x88e86)
                #4  0x00007f5765330c60 __clone3 (libc.so.6 + 0x10fc60)
                
                Stack trace of thread 442789:
                #0  0x00007f57652a67d5 __futex_abstimed_wait_common (libc.so.6 + 0x857d5)
                #1  0x00007f57652b1ef8 __new_sem_wait_slow64.constprop.0 (libc.so.6 + 0x90ef8)
                #2  0x0000000000996118 std.Thread.Instance.entryFn (zig + 0x596118)
                #3  0x00007f57652a9e86 start_thread (libc.so.6 + 0x88e86)
                #4  0x00007f5765330c60 __clone3 (libc.so.6 + 0x10fc60)
                
                Stack trace of thread 442788:
                #0  0x00007f57652a67d5 __futex_abstimed_wait_common (libc.so.6 + 0x857d5)
                #1  0x00007f57652b1ef8 __new_sem_wait_slow64.constprop.0 (libc.so.6 + 0x90ef8)
                #2  0x0000000000996118 std.Thread.Instance.entryFn (zig + 0x596118)
                #3  0x00007f57652a9e86 start_thread (libc.so.6 + 0x88e86)
                #4  0x00007f5765330c60 __clone3 (libc.so.6 + 0x10fc60)
                
                Stack trace of thread 442793:
                #0  0x00007f57652a67d5 __futex_abstimed_wait_common (libc.so.6 + 0x857d5)
                #1  0x00007f57652b1ef8 __new_sem_wait_slow64.constprop.0 (libc.so.6 + 0x90ef8)
                #2  0x0000000000996118 std.Thread.Instance.entryFn (zig + 0x596118)
                #3  0x00007f57652a9e86 start_thread (libc.so.6 + 0x88e86)
                #4  0x00007f5765330c60 __clone3 (libc.so.6 + 0x10fc60)
                
                Stack trace of thread 442795:
                #0  0x00007f57652a67d5 __futex_abstimed_wait_common (libc.so.6 + 0x857d5)
                #1  0x00007f57652b1ef8 __new_sem_wait_slow64.constprop.0 (libc.so.6 + 0x90ef8)
                #2  0x0000000000996118 std.Thread.Instance.entryFn (zig + 0x596118)
                #3  0x00007f57652a9e86 start_thread (libc.so.6 + 0x88e86)
                #4  0x00007f5765330c60 __clone3 (libc.so.6 + 0x10fc60)
                
                Stack trace of thread 442801:
                #0  0x00007f57652a67d5 __futex_abstimed_wait_common (libc.so.6 + 0x857d5)
                #1  0x00007f57652b1ef8 __new_sem_wait_slow64.constprop.0 (libc.so.6 + 0x90ef8)
                #2  0x0000000000996118 std.Thread.Instance.entryFn (zig + 0x596118)
                #3  0x00007f57652a9e86 start_thread (libc.so.6 + 0x88e86)
                #4  0x00007f5765330c60 __clone3 (libc.so.6 + 0x10fc60)
                
                Stack trace of thread 442796:
                #0  0x00007f57652a67d5 __futex_abstimed_wait_common (libc.so.6 + 0x857d5)
                #1  0x00007f57652b1ef8 __new_sem_wait_slow64.constprop.0 (libc.so.6 + 0x90ef8)
                #2  0x0000000000996118 std.Thread.Instance.entryFn (zig + 0x596118)
                #3  0x00007f57652a9e86 start_thread (libc.so.6 + 0x88e86)
                #4  0x00007f5765330c60 __clone3 (libc.so.6 + 0x10fc60)
                
                Stack trace of thread 442802:
                #0  0x00007f57652a67d5 __futex_abstimed_wait_common (libc.so.6 + 0x857d5)
                #1  0x00007f57652b1ef8 __new_sem_wait_slow64.constprop.0 (libc.so.6 + 0x90ef8)
                #2  0x0000000000996118 std.Thread.Instance.entryFn (zig + 0x596118)
                #3  0x00007f57652a9e86 start_thread (libc.so.6 + 0x88e86)
                #4  0x00007f5765330c60 __clone3 (libc.so.6 + 0x10fc60)
                
                Stack trace of thread 442797:
                #0  0x00007f57652a67d5 __futex_abstimed_wait_common (libc.so.6 + 0x857d5)
                #1  0x00007f57652b1ef8 __new_sem_wait_slow64.constprop.0 (libc.so.6 + 0x90ef8)
                #2  0x0000000000996118 std.Thread.Instance.entryFn (zig + 0x596118)
                #3  0x00007f57652a9e86 start_thread (libc.so.6 + 0x88e86)
                #4  0x00007f5765330c60 __clone3 (libc.so.6 + 0x10fc60)
                
                Stack trace of thread 442792:
                #0  0x00007f57652a67d5 __futex_abstimed_wait_common (libc.so.6 + 0x857d5)
                #1  0x00007f57652b1ef8 __new_sem_wait_slow64.constprop.0 (libc.so.6 + 0x90ef8)
                #2  0x0000000000996118 std.Thread.Instance.entryFn (zig + 0x596118)
                #3  0x00007f57652a9e86 start_thread (libc.so.6 + 0x88e86)
                #4  0x00007f5765330c60 __clone3 (libc.so.6 + 0x10fc60)
                
                Stack trace of thread 442787:
                #0  0x00007f57652a67d5 __futex_abstimed_wait_common (libc.so.6 + 0x857d5)
                #1  0x00007f57652b1ef8 __new_sem_wait_slow64.constprop.0 (libc.so.6 + 0x90ef8)
                #2  0x00000000008d2538 Compilation.update (zig + 0x4d2538)
                #3  0x0000000000895cbf main.updateModule (zig + 0x495cbf)
                #4  0x000000000086be19 main.buildOutputType (zig + 0x46be19)
                #5  0x0000000000840672 main (zig + 0x440672)
                #6  0x00007f576524a24e __libc_start_call_main (libc.so.6 + 0x2924e)
                #7  0x00007f576524a309 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x29309)
                #8  0x000000000083e465 _start (zig + 0x43e465)
                
                Stack trace of thread 442799:
                #0  0x00007f57652a67d5 __futex_abstimed_wait_common (libc.so.6 + 0x857d5)
                #1  0x00007f57652b1ef8 __new_sem_wait_slow64.constprop.0 (libc.so.6 + 0x90ef8)
                #2  0x0000000000996118 std.Thread.Instance.entryFn (zig + 0x596118)
                #3  0x00007f57652a9e86 start_thread (libc.so.6 + 0x88e86)
                #4  0x00007f5765330c60 __clone3 (libc.so.6 + 0x10fc60)
                ELF object binary architecture: AMD x86-64
```

And full core in tarball. Because GitHub does not support uploading of core files directly.

[core.tar.gz](https://github.com/ziglang/zig/files/10096978/core.tar.gz)

**Comment by Vexu** [comment]
Reduction:
```zig
pub export fn entry() void {
    if (true) {} else defer {}
    // while (true) {} else defer {}
    // for ("") |_| {} else defer {}
}
```
