### ISSUE TITLE
comptime recursion crashes

### ISSUE THREAD

**Issue by alichraghi** [ziglang/zig#13780]
```zig
fn crash() type {
    return crash();
}

test {
    _ = crash();
}
```
```
$ zig test file.zig
fish: Job 1, 'zig test file.zig' terminated by signal SIGSEGV (Address boundary error)
```

**EDIT:** this original issue has been fixed a while ago. but Sema.zig needs to be re-written to not be recursive

**Comment by nektro** [comment]
bottom of trace

```
#1667 0x00000000009fb58b in Sema.analyzeBody (sema=0x7fffffff1530, block=0x7ffffffea3b8, body=<error reading variable: Cannot access memory at address 0x5a>) at /home/meghan/src/zig/src/Sema.zig:798
#1668 0x0000000000d15005 in Sema.analyzeCall (sema=0x7fffffff1530, block=0x7ffffffedc68, func=90, func_src=..., call_src=..., modifier=auto, ensure_result_used=false, uncasted_args=..., bound_arg_src=...) at /home/meghan/src/zig/src/Sema.zig:6591
#1669 0x0000000000a1d13e in Sema.zirCall (sema=0x7fffffff1530, block=0x7ffffffedc68, inst=25) at /home/meghan/src/zig/src/Sema.zig:6106
#1670 0x00000000007fdc5a in Sema.analyzeBodyInner (sema=0x7fffffff1530, block=0x7ffffffedc68, body=...) at /home/meghan/src/zig/src/Sema.zig:916
#1671 0x0000000000d3a9d7 in Sema.resolveBlockBody (sema=0x7fffffff1530, parent_block=0x7fffffff12f8, src=..., child_block=0x7ffffffedc68, body=..., body_inst=20, merges=0x7ffffffedbe8) at /home/meghan/src/zig/src/Sema.zig:5241
#1672 0x0000000000ac5538 in Sema.zirBlock (sema=0x7fffffff1530, parent_block=0x7fffffff12f8, inst=20) at /home/meghan/src/zig/src/Sema.zig:5224
#1673 0x000000000080ac5f in Sema.analyzeBodyInner (sema=0x7fffffff1530, block=0x7fffffff12f8, body=...) at /home/meghan/src/zig/src/Sema.zig:1449
#1674 0x00000000009fb58b in Sema.analyzeBody (sema=0x7fffffff1530, block=0x7fffffff12f8, body=<error reading variable: Cannot access memory at address 0x5a>) at /home/meghan/src/zig/src/Sema.zig:798
#1675 0x00000000007cc1da in Module.analyzeFnBody (mod=0x2554c30, func=0x25631b0, arena=...) at /home/meghan/src/zig/src/Module.zig:5661
#1676 0x00000000007ae9bb in Module.ensureFuncBodyAnalyzed (mod=0x2554c30, func=0x25631b0) at /home/meghan/src/zig/src/Module.zig:4344
#1677 0x000000000065cf54 in Compilation.processOneJob (comp=0x2553af8, job=...) at /home/meghan/src/zig/src/Compilation.zig:3154
#1678 0x000000000064a310 in Compilation.performAllTheWork (comp=0x2553af8, main_progress_node=0x7fffffff2cd0) at /home/meghan/src/zig/src/Compilation.zig:3092
#1679 0x000000000064266a in Compilation.update (comp=0x2553af8) at /home/meghan/src/zig/src/Compilation.zig:2401
#1680 0x00000000005d0cc0 in main.updateModule (gpa=..., comp=0x2553af8, hook=...) at /home/meghan/src/zig/src/main.zig:3376
#1681 0x0000000000517b29 in main.buildOutputType (gpa=..., arena=..., all_args=..., arg_mode=...) at /home/meghan/src/zig/src/main.zig:3043
#1682 0x00000000004aed5f in main.mainArgs (gpa=..., arena=..., args=...) at /home/meghan/src/zig/src/main.zig:236
#1683 0x00000000004ae446 in main (argc=3, argv=0x7fffffffb768) at /home/meghan/src/zig/src/stage1.zig:56
```

**Comment by alichraghi** [comment]
this doesn't crash anymore
```
test.zig:2:17: error: inline call is recursive
    return crash();
           ~~~~~^~
referenced by:
    crash: test.zig:2:12
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

**Comment by alichraghi** [comment]
Seems like this is now just a duplicate of #13724
