### ISSUE TITLE
compiler segfault in comptime block

### ISSUE THREAD

**Issue by cgag** [ziglang/zig#1437]
Didn't really expect this to work but I hit a segfault while playing around:

```
const std = @import("std");
const Map = std.AutoHashMap;
const warn = std.debug.warn;

comptime {
    var direct_alloc = &std.heap.DirectAllocator.init().allocator;
    var keywords = Map([]const u8, i32).init(direct_alloc);
    keywords.put("and", 10);
}

pub fn main() void {
}
```

```#0  0x0000000000dd52cb in hash_const_val (const_val=<error reading variable: Cannot access memory at address 0x7ffc052c4fa8>) at /home/cgag/bin/zig/src/analyze.cpp:4689
        __PRETTY_FUNCTION__ = "uint32_t hash_const_val(ConstExprValue*)"
        __func__ = "hash_const_val"
#1  0x0000000000dd5646 in hash_const_val (const_val=0x67ff968) at /home/cgag/bin/zig/src/analyze.cpp:4783
        __PRETTY_FUNCTION__ = "uint32_t hash_const_val(ConstExprValue*)"
        __func__ = "hash_const_val"
#2  0x0000000000dd5646 in hash_const_val (const_val=0x67ff968) at /home/cgag/bin/zig/src/analyze.cpp:4783
        __PRETTY_FUNCTION__ = "uint32_t hash_const_val(ConstExprValue*)"
        __func__ = "hash_const_val"
#3  0x0000000000dd5646 in hash_const_val (const_val=0x67ff968) at /home/cgag/bin/zig/src/analyze.cpp:4783
        __PRETTY_FUNCTION__ = "uint32_t hash_const_val(ConstExprValue*)"
        __func__ = "hash_const_val"
```

**Comment by andrewrk** [comment]
This is no longer an issue in master branch.
