### ISSUE TITLE
Zig crashes building AArch64 executable without FP/Neon extensions

### ISSUE THREAD

**Issue by msiedlarek** [ziglang/zig#15614]
### Zig Version

0.11.0-dev.2999+1e9811070

### Steps to Reproduce and Observed Behavior

Compiling a minimal program

```zig
pub fn main() void {}
```

with ARMv8 floating-point extension and the Advanced SIMD extensions disabled

```shell
zig build-exe -target aarch64-linux -mcpu generic-fp_armv8-neon main.zig
```

causes Zig to crash hitting `llvm_unreachable` in `llvm::MVT::getVectorMinNumElements()`

```gdb
LLVM Emit Object... Process 60105 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x0000000104dbad41 zig`llvm::MVT::getVectorMinNumElements() const + 49
zig`llvm::MVT::getVectorMinNumElements:
->  0x104dbad41 <+49>: ud2
    0x104dbad43 <+51>: movl   $0x400, %eax              ; imm = 0x400
    0x104dbad48 <+56>: movl   %eax, -0x10(%rbp)
    0x104dbad4b <+59>: jmp    0x104dbae3a               ; <+298>
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
  * frame #0: 0x0000000104dbad41 zig`llvm::MVT::getVectorMinNumElements() const + 49
    frame #1: 0x0000000104dcf83e zig`llvm::EVT::getVectorElementCount() const + 30
    frame #2: 0x000000010588be31 zig`llvm::SelectionDAG::SplitVector(llvm::SDValue const&, llvm::SDLoc const&, llvm::EVT const&, llvm::EVT const&) + 417
    frame #3: 0x0000000106239873 zig`llvm::SelectionDAG::SplitVectorOperand(llvm::SDNode const*, unsigned int) + 211
    frame #4: 0x000000010b2eebcf zig`ReplaceReductionResults(llvm::SDNode*, llvm::SmallVectorImpl<llvm::SDValue>&, llvm::SelectionDAG&, unsigned int, unsigned int) + 191
    frame #5: 0x000000010b2ebcb0 zig`llvm::AArch64TargetLowering::ReplaceNodeResults(llvm::SDNode*, llvm::SmallVectorImpl<llvm::SDValue>&, llvm::SelectionDAG&) const + 4720
    frame #6: 0x000000010616d00e zig`llvm::DAGTypeLegalizer::CustomLowerNode(llvm::SDNode*, llvm::EVT, bool) + 286
    frame #7: 0x000000010619292f zig`llvm::DAGTypeLegalizer::PromoteFloatResult(llvm::SDNode*, unsigned int) + 63
    frame #8: 0x00000001061631d3 zig`llvm::DAGTypeLegalizer::run() + 1939
    frame #9: 0x000000010616fc23 zig`llvm::SelectionDAG::LegalizeTypes() + 1411
    frame #10: 0x0000000106031e5d zig`llvm::SelectionDAGISel::CodeGenAndEmitDAG() + 397
    frame #11: 0x0000000106031632 zig`llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) + 16594
    frame #12: 0x000000010602b1cc zig`llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) + 3868
    frame #13: 0x00000001048bf2c1 zig`llvm::MachineFunctionPass::runOnFunction(llvm::Function&) + 1329
    frame #14: 0x00000001029fa7a8 zig`llvm::FPPassManager::runOnModule(llvm::Module&) + 8408
    frame #15: 0x00000001029e46e5 zig`llvm::legacy::PassManagerImpl::run(llvm::Module&) + 2245
    frame #16: 0x0000000101df1531 zig`ZigLLVMTargetMachineEmitToFile(targ_machine_ref=0x000000011cacac00, module_ref=0x0000000119183350, error_message=0x00007ff7bfeeb868, is_debug=false, is_small=false, time_report=false, tsan=false, lto=false, asm_filename=0x0000000000000000, bin_filename="~/.cache/zig/o/316a7535932f4451773dbb8a3d05d948/libcompiler_rt.a.o", llvm_ir_filename=0x0000000000000000, bitcode_filename=0x0000000000000000) at zig_llvm.cpp:391:16
    frame #17: 0x0000000100620ebc zig`codegen.llvm.Object.flushModule(self=0x000000011917e830, comp=0x000000011cac0210, prog_node=0x00007ff7bfef1cd0) at llvm.zig:865:34
    frame #18: 0x000000010063df04 zig`link.Elf.flushModule(self=0x000000011cac9000, comp=0x000000011cac0210, prog_node=0x00007ff7bfef1cd0) at Elf.zig:1029:47
    frame #19: 0x000000010061ce81 zig`link.File.flushModule(base=0x000000011cac9000, comp=0x000000011cac0210, prog_node=0x00007ff7bfef1cd0) at link.zig:817:74
    frame #20: 0x00000001003d223d zig`link.File.linkAsArchive(base=0x000000011cac9000, comp=0x000000011cac0210, prog_node=0x00007ff7bfef1cd0) at link.zig:989:33
    frame #21: 0x0000000100187f17 zig`link.File.flush(base=0x000000011cac9000, comp=0x000000011cac0210, prog_node=0x00007ff7bfef1cd0) at link.zig:794:38
    frame #22: 0x0000000100187967 zig`Compilation.flush(comp=0x000000011cac0210, prog_node=0x00007ff7bfef1cd0) at Compilation.zig:2151:24
    frame #23: 0x000000010018adce zig`Compilation.update(comp=0x000000011cac0210, main_progress_node=0x00007ff7bfef1cd0) at Compilation.zig:2115:27
    frame #24: 0x00000001002bddcc zig`Compilation.updateSubCompilation(parent_comp=0x000000011982b610, sub_comp=0x000000011cac0210, misc_task=compiler_rt, prog_node=0x00007ff7bfef1cd0) at Compilation.zig:5298:28
    frame #25: 0x00000001002e5dd1 zig`Compilation.buildOutputFromZig(comp=0x000000011982b610, src_basename=(ptr = "compiler_rt.zig", len = 15), output_mode=Lib, out=0x000000011982b950, misc_task_tag=compiler_rt, prog_node=0x00007ff7bfef1cd0) at Compilation.zig:5394:34
    frame #26: 0x00000001002eab8d zig`Compilation.buildCompilerRtOneShot(comp=0x000000011982b610, output_mode=Lib, out=0x000000011982b950, prog_node=0x00007ff7bfef1cd0) at Compilation.zig:3735:28
    frame #27: 0x000000010018ddb4 zig`Compilation.performAllTheWork(comp=0x000000011982b610, main_progress_node=0x00007ff7bfef1cd0) at Compilation.zig:3076:49
    frame #28: 0x000000010018a0be zig`Compilation.update(comp=0x000000011982b610, main_progress_node=0x00007ff7bfef1cd0) at Compilation.zig:2020:31
    frame #29: 0x00000001001b87ec zig`main.updateModule(comp=0x000000011982b610) at main.zig:3825:24
    frame #30: 0x00000001000310f3 zig`main.buildOutputType(gpa=mem.Allocator @ 0x0000000112e9edf8, arena=mem.Allocator @ 0x00007ff7bfeff1b0, all_args=[][]const u8 @ 0x00007ff7bfef3968, arg_mode=main.ArgMode @ 0x000000011026fd33) at main.zig:3260:17
    frame #31: 0x00000001000043aa zig`main.mainArgs(gpa=mem.Allocator @ 0x0000000112e9edf8, arena=mem.Allocator @ 0x00007ff7bfeff1b0, args=[][]const u8 @ 0x00007ff7bfefec70) at main.zig:268:31
    frame #32: 0x0000000100003a08 zig`main.main at main.zig:212:20
    frame #33: 0x00000001000060ba zig`main [inlined] start.callMain at start.zig:609:37
    frame #34: 0x00000001000060ae zig`main [inlined] start.initEventLoopAndCallMain at start.zig:543:5
    frame #35: 0x00000001000060ae zig`main at start.zig:493:36
    frame #36: 0x000000010000601e zig`main(c_argc=7, c_argv=0x00007ff7bfeff6e8, c_envp=0x00007ff7bfeff728) at start.zig:508:80
    frame #37: 0x00007ff81989641f dyld`start + 1903
```

### Expected Behavior

I would like to program to compile, or at least tell me why it's not possible.

**Comment by nektro** [comment]
```
LLVM Emit Object... Don't know how to custom expand this
UNREACHABLE executed at /home/meghan/src/llvm-16/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:22089!

Thread 1 "zig" received signal SIGABRT, Aborted.
0x00007fffea1e8bc7 in __pthread_kill_implementation () from /nix/store/2j8jqmnd9l7plihhf713yf291c9vyqjm-glibc-2.35-224/lib/libc.so.6
(gdb) bt
#0  0x00007fffea1e8bc7 in __pthread_kill_implementation () from /nix/store/2j8jqmnd9l7plihhf713yf291c9vyqjm-glibc-2.35-224/lib/libc.so.6
#1  0x00007fffea19bb46 in raise () from /nix/store/2j8jqmnd9l7plihhf713yf291c9vyqjm-glibc-2.35-224/lib/libc.so.6
#2  0x00007fffea1864b5 in abort () from /nix/store/2j8jqmnd9l7plihhf713yf291c9vyqjm-glibc-2.35-224/lib/libc.so.6
#3  0x00007fffeb199dba in llvm::llvm_unreachable_internal(char const*, char const*, unsigned int) () from /home/meghan/src/llvm-16/out/lib/libLLVM-16.so
#4  0x00007fffedc85e8a in llvm::AArch64TargetLowering::ReplaceNodeResults(llvm::SDNode*, llvm::SmallVectorImpl<llvm::SDValue>&, llvm::SelectionDAG&) const () from /home/meghan/src/llvm-16/out/lib/libLLVM-16.so
#5  0x00007fffebd0c9ac in llvm::DAGTypeLegalizer::CustomLowerNode(llvm::SDNode*, llvm::EVT, bool) () from /home/meghan/src/llvm-16/out/lib/libLLVM-16.so
#6  0x00007fffebccbf0f in llvm::DAGTypeLegalizer::PromoteFloatResult(llvm::SDNode*, unsigned int) () from /home/meghan/src/llvm-16/out/lib/libLLVM-16.so
#7  0x00007fffebd0d36d in llvm::DAGTypeLegalizer::run() () from /home/meghan/src/llvm-16/out/lib/libLLVM-16.so
#8  0x00007fffebd0e43d in llvm::SelectionDAG::LegalizeTypes() () from /home/meghan/src/llvm-16/out/lib/libLLVM-16.so
#9  0x00007fffebe77473 in llvm::SelectionDAGISel::CodeGenAndEmitDAG() () from /home/meghan/src/llvm-16/out/lib/libLLVM-16.so
#10 0x00007fffebe7b5ac in llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) () from /home/meghan/src/llvm-16/out/lib/libLLVM-16.so
#11 0x00007fffebe7d4a2 in llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) [clone .part.0] () from /home/meghan/src/llvm-16/out/lib/libLLVM-16.so
#12 0x00007fffeb7d9015 in llvm::MachineFunctionPass::runOnFunction(llvm::Function&) [clone .part.0] () from /home/meghan/src/llvm-16/out/lib/libLLVM-16.so
#13 0x00007fffeb44ff93 in llvm::FPPassManager::runOnFunction(llvm::Function&) () from /home/meghan/src/llvm-16/out/lib/libLLVM-16.so
#14 0x00007fffeb4501c1 in llvm::FPPassManager::runOnModule(llvm::Module&) () from /home/meghan/src/llvm-16/out/lib/libLLVM-16.so
#15 0x00007fffeb450ab5 in llvm::legacy::PassManagerImpl::run(llvm::Module&) () from /home/meghan/src/llvm-16/out/lib/libLLVM-16.so
#16 0x000000000282f988 in ZigLLVMTargetMachineEmitToFile (targ_machine_ref=0x38d0dd0, module_ref=0x311a920, error_message=0x7ffffffe8078, is_debug=false, is_small=false, time_report=false, tsan=false, lto=false, asm_filename=0x0, bin_filename=0x49dc3ab "/home/meghan/.cache/zig/o/72ac22d66bcc8c720970f44966913ac4/libcompiler_rt.a.o", llvm_ir_filename=0x0, bitcode_filename=0x0) at /home/meghan/src/zig/src/zig_llvm.cpp:391
#17 0x000000000105aa87 in codegen.llvm.Object.flushModule (self=0x3f581b0, comp=0x3d5a1b0, prog_node=0x7ffffffee5e0) at /home/meghan/src/zig/src/codegen/llvm.zig:865
#18 0x00000000010776c3 in link.Elf.flushModule (self=0x4024cd0, comp=0x3d5a1b0, prog_node=0x7ffffffee5e0) at /home/meghan/src/zig/src/link/Elf.zig:1029
#19 0x0000000001056ae1 in link.File.flushModule (base=0x4024cd0, comp=0x3d5a1b0, prog_node=0x7ffffffee5e0) at link.zig:817
#20 0x0000000000e0de4a in link.File.linkAsArchive (base=0x4024cd0, comp=0x3d5a1b0, prog_node=0x7ffffffee5e0) at link.zig:989
#21 0x0000000000bcd182 in link.File.flush (base=0x4024cd0, comp=0x3d5a1b0, prog_node=0x7ffffffee5e0) at link.zig:794
#22 0x0000000000bccbe6 in Compilation.flush (comp=0x3d5a1b0, prog_node=0x7ffffffee5e0) at Compilation.zig:2151
#23 0x0000000000bd0035 in Compilation.update (comp=0x3d5a1b0, main_progress_node=0x7ffffffee5e0) at Compilation.zig:2115
#24 0x0000000000cfd9db in Compilation.updateSubCompilation (parent_comp=0x2daab50, sub_comp=0x3d5a1b0, misc_task=compiler_rt, prog_node=0x7ffffffee5e0) at Compilation.zig:5298
#25 0x0000000000d2540e in Compilation.buildOutputFromZig (comp=0x2daab50, src_basename=..., output_mode=Lib, out=0x2daae80, misc_task_tag=compiler_rt, prog_node=0x7ffffffee5e0) at Compilation.zig:5394
#26 0x0000000000d2a01c in Compilation.buildCompilerRtOneShot (comp=0x2daab50, output_mode=Lib, out=0x2daae80, prog_node=0x7ffffffee5e0) at Compilation.zig:3735
#27 0x0000000000bd30eb in Compilation.performAllTheWork (comp=0x2daab50, main_progress_node=0x7ffffffee5e0) at Compilation.zig:3076
#28 0x0000000000bcf32e in Compilation.update (comp=0x2daab50, main_progress_node=0x7ffffffee5e0) at Compilation.zig:2020
#29 0x0000000000bfc81b in main.updateModule (comp=0x2daab50) at main.zig:3825
#30 0x0000000000a7f752 in main.buildOutputType (gpa=..., arena=..., all_args=..., arg_mode=...) at main.zig:3260
#31 0x0000000000a528d2 in main.mainArgs (gpa=..., arena=..., args=...) at main.zig:268
#32 0x0000000000a51f46 in main.main () at main.zig:212
```

**Comment by msiedlarek** [comment]
Oops, this seems to be a duplicate of #14465
