### ISSUE TITLE
Segmentation fault compiling switch on pointers

### ISSUE THREAD

**Issue by amp-59** [ziglang/zig#16491]
### Zig Version

0.11.0-dev.4059+17255bed4

### Steps to Reproduce and Observed Behavior

Compile example program with `zig build-obj switch_ptr_error.zig`
`switch_ptr_error.zig`:
```zig
const x: [:0]const u8 = "one_two";
const y: [:0]const u8 = "three_four";
const z: [:0]const u8 = &.{};

export fn entry(a: [*:0]const u8) u8 {
    switch (a) {
        x.ptr => return @intCast(x.len),
        y.ptr => return @intCast(y.len),
        else => return 0,
    }
}
```
This result may be affected by compile flags (`-fstrip`) and the presence of other functions.

Another function (assuming the same declarations):
```zig
export fn entry1(a: [*:0]const u8) u8 {
    switch (a) {
        x.ptr => return @intCast(x.len),
        z.ptr => return @intCast(z.len),
        else => return 0,
    }
}
```

### Expected Behavior

-

**Comment by andrewrk** [comment]
as of `0.11.0-dev.4183+32a175740` this is the problem:

```
zig: /home/andy/Downloads/llvm-project-16/llvm/include/llvm/Support/Casting.h:579: decltype(auto) llvm::cast(From*) [with To = llvm::ConstantInt; From = llvm::Value]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.

Thread 1 "zig" received signal SIGABRT, Aborted.
0x00007ffff7d41bc7 in __pthread_kill_implementation () from /nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7d41bc7 in __pthread_kill_implementation () from /nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6
#1  0x00007ffff7cf4b46 in raise () from /nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6
#2  0x00007ffff7cdf4b5 in abort () from /nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6
#3  0x00007ffff7cdf3d9 in __assert_fail_base.cold.0 () from /nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6
#4  0x00007ffff7ced7b6 in __assert_fail () from /nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6
#5  0x000000000890ee33 in LLVMAddCase ()
#6  0x0000000006695153 in codegen.llvm.Builder.WipFunction.WipSwitch.addCase (self=0x7ffffffe6330, val=(true | unknown: 0x18), dest=(unknown: 0x2), wip=0x7ffffffe86b8) at /home/andy/Downloads/zig/src/codegen/llvm/Builder.zig:2323
#7  0x0000000006693d6e in codegen.llvm.FuncGen.airSwitchBr (self=0x7ffffffe8640, inst=20) at /home/andy/Downloads/zig/src/codegen/llvm.zig:5847
#8  0x0000000006121464 in codegen.llvm.FuncGen.genBody (self=0x7ffffffe8640, body=6 items at 0xecb8b58 = {...}) at /home/andy/Downloads/zig/src/codegen/llvm.zig:4820
#9  0x000000000611be16 in codegen.llvm.Object.updateFunc (o=0xec53560, mod=0xec51b50, func_index=1398, air=..., liveness=...) at /home/andy/Downloads/zig/src/codegen/llvm.zig:1543
#10 0x000000000612669a in link.Elf.updateFunc (self=0xec52bc0, mod=0xec51b50, func_index=1398, air=..., liveness=...) at /home/andy/Downloads/zig/src/link/Elf.zig:2583
#11 0x0000000005e8fe64 in link.File.updateFunc (base=0xec52bc0, module=0xec51b50, func_index=1398, air=..., liveness=...) at link.zig:577
#12 0x0000000005c74473 in Module.ensureFuncBodyAnalyzed (mod=0xec51b50, func_index=1398) at Module.zig:3988
#13 0x0000000005c71b21 in Compilation.processOneJob (comp=0xec50a80, job=..., prog_node=0x7ffffffebc20) at Compilation.zig:3183
#14 0x0000000005ad3e84 in Compilation.performAllTheWork (comp=0xec50a80, main_progress_node=0x7ffffffebc20) at Compilation.zig:3120
#15 0x0000000005acf7b2 in Compilation.update (comp=0xec50a80, main_progress_node=0x7ffffffebc20) at Compilation.zig:2067
#16 0x0000000005aff37f in main.updateModule (comp=0xec50a80) at main.zig:3887
#17 0x0000000005b2ee69 in main.buildOutputType (gpa=..., arena=..., all_args=3 items at 0xec0d590 = {...}, arg_mode=...) at main.zig:3308
#18 0x000000000598ea94 in main.mainArgs (gpa=..., arena=..., args=3 items at 0xec0d590 = {...}) at main.zig:273
#19 0x000000000598bd06 in main.main () at main.zig:213
(gdb) 
```

**Comment by alexrp** [comment]
Switching on pointers is planned to be removed from the language.
