### ISSUE TITLE
Stack trace not printed when panicking in imported function

### ISSUE THREAD

**Issue by wooster0** [ziglang/zig#16975]
### Zig Version

0.12.0-dev.168+a31748b29

### Steps to Reproduce and Observed Behavior

`exe.zig`
```zig
extern fn panic() void;

pub fn main() void {
    panic();
}
```
`lib.zig`
```zig
export fn panic() void {
    @panic("panic");
}
```
`build.zig`
```zig
const std = @import("std");

pub fn build(b: *std.Build) !void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const lib = b.addStaticLibrary(.{
        .name = "lib",
        .root_source_file = .{ .path = "lib.zig" },
        .target = target,
        .optimize = optimize,
    });

    const exe = b.addExecutable(.{
        .name = "exe",
        .root_source_file = .{ .path = "exe.zig" },
        .target = target,
        .optimize = optimize,
    });

    exe.linkLibrary(lib);

    b.installArtifact(exe);

    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    const run_step = b.step("run", "Run");
    run_step.dependOn(&run_cmd.step);
}
```
```
$ zig build run
steps [2/6] zig build-exe exe Debug native... LLVM Emit Object... thread 143239 panic: panic
Panicked during a panic. Aborting.
```

### Expected Behavior

```
$ zig build run
steps [2/6] zig build-exe exe Debug native... LLVM Emit Object... thread 142400 panic: panic
lib.zig:2:5: 0x21ea65 in main (exe)
    @panic("panic");
    ^
```

**Comment by kcbanner** [comment]
This is caused by the version of `elf_aux_maybe` (linux.zig) in `lib` not being initialized, which causes the phdr lookup to fail (due to underflow when subtracting from zero):

```
#0  0x00000000002ddc54 in process.getBaseAddress () at /home/kcbanner/kit/zig-linux-x86_64-0.12.0-dev.170+750998eef/lib/std/process.zig:1079
#1  0x00000000002cec55 in os.dl_iterate_phdr__anon_5275 (context=0x7fffffffc120) at /home/kcbanner/kit/zig-linux-x86_64-0.12.0-dev.170+750998eef/lib/std/os.zig:5409
#2  0x00000000002ce749 in debug.DebugInfo.lookupModuleDl (self=0x326608 <debug.self_debug_info>, address=2992457) at /home/kcbanner/kit/zig-linux-x86_64-0.12.0-dev.170+750998eef/lib/std/debug.zig:1837
#3  0x00000000002cf5dd in debug.DebugInfo.getModuleForAddress (self=0x326608 <debug.self_debug_info>, address=2992457) at /home/kcbanner/kit/zig-linux-x86_64-0.12.0-dev.170+750998eef/lib/std/debug.zig:1561
#4  0x00000000002f633f in debug.StackIterator.next_unwind (self=0x7fffffffd120) at /home/kcbanner/kit/zig-linux-x86_64-0.12.0-dev.170+750998eef/lib/std/debug.zig:643
#5  0x00000000002e9670 in debug.StackIterator.next_internal (self=0x7fffffffd120) at /home/kcbanner/kit/zig-linux-x86_64-0.12.0-dev.170+750998eef/lib/std/debug.zig:669
#6  0x00000000002dad0f in debug.StackIterator.next (self=0x7fffffffd120) at /home/kcbanner/kit/zig-linux-x86_64-0.12.0-dev.170+750998eef/lib/std/debug.zig:584
#7  0x00000000002daadc in debug.writeCurrentStackTrace__anon_7051 (out_stream=..., debug_info=0x326608 <debug.self_debug_info>, tty_config=..., start_addr=...)
    at /home/kcbanner/kit/zig-linux-x86_64-0.12.0-dev.170+750998eef/lib/std/debug.zig:731
#8  0x00000000002aef67 in debug.dumpCurrentStackTrace (start_addr=...) at /home/kcbanner/kit/zig-linux-x86_64-0.12.0-dev.170+750998eef/lib/std/debug.zig:127
#9  0x00000000002ae897 in debug.panicImpl (trace=0x0, first_trace_addr=..., msg=...) at /home/kcbanner/kit/zig-linux-x86_64-0.12.0-dev.170+750998eef/lib/std/debug.zig:421
#10 0x00000000002ae6f7 in builtin.default_panic (msg=..., error_return_trace=0x0, ret_addr=...) at /home/kcbanner/kit/zig-linux-x86_64-0.12.0-dev.170+750998eef/lib/std/builtin.zig:813
#11 0x00000000002ae696 in panic () at lib.zig:2
#12 0x000000000023a7e9 in exe.main () at exe.zig:4
#13 0x000000000023a0ad in start.posixCallMainAndExit () at /home/kcbanner/kit/zig-linux-x86_64-0.12.0-dev.170+750998eef/lib/std/start.zig:360
#14 0x0000000000239c02 in _start () at /home/kcbanner/kit/zig-linux-x86_64-0.12.0-dev.170+750998eef/lib/std/start.zig:243
```

Linking libc does resolve the issue, so I think the `linux.zig` getauxval implementation has to handle usage from libraries where the startup code that initializes it doesn't run.
