### ISSUE TITLE
Segfault when targeting `x86_64-windows-musl`

### ISSUE THREAD

**Issue by 190n** [ziglang/zig#18139]
### Zig Version

0.12.0-dev.1741+2549de80b

### Steps to Reproduce and Observed Behavior

- Compile any Zig file with `-target x86_64-windows-musl`:

```zig
$ cat monkey.zig
const std = @import("std");

pub fn main() !void {
    std.debug.print("Hello, world!\n", .{});
}
$ zig build-exe -target x86_64-windows-musl monkey.zig
LLVM Emit Object... zsh: segmentation fault (core dumped)  zig build-exe -target x86_64-windows-musl src/explode.zig
```

### Expected Behavior

If I understand everything correctly, it should print an error indicating that Musl does not support Windows (I believe I typed `musl` by mistake instead of `msvc` while I was trying to remember the non-GNU ABI option for Windows) instead of just segfaulting.

**Comment by rootbeer** [comment]
If you add `-lc` to indicate you want to link an external C library (I think this is generally required when using the `-musl` or `-gnu` targets?), you'll get a slightly better error message:

```
$ zig build-exe -target x86_64-windows-musl monkey.zig -lc
error: unable to find or provide libc for target 'x86_64-windows.win8_1...win10_fe-musl'
info: zig can provide libc for related target x86_64-windows-gnu
```

In a zig build with debug logging, the backtrace isn't very useful (without the `-lc`). I get:
```
$ zig  build-exe -target x86_64-windows-musl monkey.zig -Dlog
LLVM Emit Object... thread 13310 panic: Segmentation fault at address 0x100000007
???:?:?: 0xaaf8070 in ??? (???)
???:?:?: 0x10d89f3f in ??? (???)
Unwind information for `???:0x10d89f3f` was not available, trace may be incomplete

Aborted
```

**Comment by jimying** [comment]
It's mean that `x86_64-windows-musl` is not supported.

please list supported targets for windows platform:
```
zig targets |grep windows
```

**Comment by rootbeer** [comment]
Not that this changes the bug report (the compiler shouldn't crash, regardless of how nonsensical the options you pass it are).  

That said, as I understand it the Zig `-lc` option generally links the C library specified by the `-target`, not necessarily the system C library.  Except on some platforms (e.g., FreeBSD) the system C library is required.  See the code in https://github.com/ziglang/zig/blob/master/src/target.zig.  (When zig is acting like a c/c++ compiler via `zig cc` the `-lc` should link in the system C library.)

You can test it yourself with `zig build-exe hello.zig -lc -target native-native-musl` which builds a statically linked binary with the Musl C library.  Vs `zig build-exe hello.zig -lc -target native-native-gnu` which builds a dynamically linked binary with the GNU C Library.  On Linux at least, a bare `zig build-exe hello.zig` will use the Zig-native syscall code, and not link a C library at all.

There are a lot of combinations here (the `-target` tuple and the host system and `-lc` or not), and not all of them make sense.

**Comment by jimying** [comment]
I have create a PR to fix it.

**Comment by rootbeer** [comment]
I don't think this is a problem with Musl or adding better musl-detection in Compilation.zig (as proposed in #18161).  That said, I don't have any specific suggestions of where or how to fix this ...  I think there may be a deeper problem where the set of valid _arch-os-abi_ combinations should be vetted at a higher level (in `src/target.zig` maybe?).  For example, if you try the (nonsense?) targets `x86_64-windows-android` or `x86_64-windows-pixel` or `x86_64-windows-gnueabihf` you'll get a similar segfault as `x86_64-windows-musl`.  Oddly `native-windows-muslx32` causes a different compiler error....

I suspect there are a lot of such invalid combinations (the set of valid arch and abi is extensive ... see `zig targets`).  I have no idea as to which ones might be wholly invalid, versus just missing some support, versus missing a ton of support.

**Comment by jimying** [comment]
@rootbeer 
 Good job!  thanks.

The basic idear of the PR (#18161):   when the target abi with `musl` not exists in `libc' list,  print error.
I think can extend it and make it generic:   check if the target is exists in `libc` list, print error.
I'll give it a try and see if I can solve it . (I'm new to zig ^_^)

PS: get  libc list by `zig targets`
```

"libc": [
  "aarch64_be-linux-gnu",
  "aarch64_be-linux-musl",
  "aarch64_be-windows-gnu",
  "aarch64-linux-gnu",
  "aarch64-linux-musl",
  "aarch64-windows-gnu",
 ........
]
```

**Comment by jimying** [comment]
I close PR #18161,  if i solve it , i'll reopen it.

**Comment by jimying** [comment]
update

 `-target x86_64-windows-musl` crash in llvm library,   gdb stack backtrace info:
```
(gdb) bt
#0  0x000000000534e3b8 in (anonymous namespace)::WinCOFFWriter::GetOrCreateCOFFSymbol(llvm::MCSymbol const*) ()
#1  0x000000000534d67c in (anonymous namespace)::WinCOFFWriter::executePostLayoutBinding(llvm::MCAssembler&, llvm::MCAsmLayout const&) ()
#2  0x000000000534c3d8 in (anonymous namespace)::WinCOFFObjectWriter::executePostLayoutBinding(llvm::MCAssembler&, llvm::MCAsmLayout const&) ()
#3  0x0000000004690920 in llvm::MCAssembler::layout(llvm::MCAsmLayout&) ()
#4  0x0000000004690b40 in llvm::MCAssembler::Finish() ()
#5  0x00000000063c4b10 in llvm::AsmPrinter::doFinalization(llvm::Module&) ()
#6  0x00000000041a7a28 in llvm::FPPassManager::doFinalization(llvm::Module&) ()
#7  0x00000000041a2da0 in llvm::legacy::PassManagerImpl::run(llvm::Module&) ()
#8  0x0000000003f6306c in ZigLLVMTargetMachineEmitToFile (targ_machine_ref=0xffff3ac72c70, module_ref=0xffff3b317c60, error_message=0xfffffffedf00, is_debug=true, is_small=false, time_report=false, 
    tsan=false, lto=false, asm_filename=0x0, bin_filename=0xffff37d9c2c0 "/home/jim/.cache/zig/o/b258a0efc4eabdcac424789dceb4c98d/c.lib.obj", llvm_ir_filename=0x0, bitcode_filename=0x0)
    at src/zig_llvm.cpp:357
#9  0x0000000008b1e750 in codegen.llvm.Object.flushModule (self=0xffff3a543f00, comp=0xffff3ac6db40, prog_node=0xffffffff4138) at /home/build/zig/src/codegen/llvm.zig:1292
#10 0x0000000008b2940c in link.Coff.flushModule (self=0xffff3ac7daf0, comp=0xffff3ac6db40, prog_node=0xffffffff4138) at /home/build/zig/src/link/Coff.zig:1647
#11 0x0000000008b17c30 in link.File.flushModule (base=0xffff3ac7dc48, comp=0xffff3ac6db40, prog_node=0xffffffff4138) at link.zig:841
#12 0x000000000883bc54 in link.File.linkAsArchive (base=0xffff3ac7dc48, comp=0xffff3ac6db40, prog_node=0xffffffff4138) at link.zig:1068
#13 0x000000000852e8a4 in link.File.flush (base=0xffff3ac7dc48, comp=0xffff3ac6db40, prog_node=0xffffffff4138) at link.zig:819
#14 0x000000000852e274 in Compilation.flush (comp=0xffff3ac6db40, prog_node=0xffffffff4138) at Compilation.zig:2657
#15 0x000000000856ca54 in Compilation.update (comp=0xffff3ac6db40, main_progress_node=0xffffffff4138) at Compilation.zig:2595
#16 0x000000000875e934 in Compilation.updateSubCompilation (parent_comp=0xffffbe7b0b70, sub_comp=0xffff3ac6db40, misc_task=zig_libc, prog_node=0xffffffff4138) at Compilation.zig:6740
#17 0x00000000087882b0 in Compilation.buildOutputFromZig (comp=0xffffbe7b0b70, src_basename=..., output_mode=Lib, out=0xffffbe7b0f70, misc_task_tag=zig_libc, prog_node=0xffffffff4138)
    at Compilation.zig:6841
#18 0x0000000008789de8 in Compilation.processOneJob (comp=0xffffbe7b0b70, job=..., prog_node=0xffffffff4138) at Compilation.zig:4004
#19 0x000000000856fce8 in Compilation.performAllTheWork (comp=0xffffbe7b0b70, main_progress_node=0xffffffff4138) at Compilation.zig:3702
#20 0x000000000856b854 in Compilation.update (comp=0xffffbe7b0b70, main_progress_node=0xffffffff4138) at Compilation.zig:2508
#21 0x0000000008598b64 in main.updateModule (comp=0xffffbe7b0b70) at main.zig:4283
#22 0x00000000085b9708 in main.buildOutputType (gpa=..., arena=..., all_args=..., arg_mode=...) at main.zig:3684
#23 0x00000000083e3898 in main.mainArgs (gpa=..., arena=..., args=...) at main.zig:278
#24 0x00000000083e0c08 in main.main () at main.zig:222
```
