### ISSUE TITLE
Compiler segfaults when emitting extern function with arguments

### ISSUE THREAD

**Issue by meithecatte** [ziglang/zig#18202]
### Zig Version

0.12.0-dev.1773+8a8fd47d2, also reproducible on 0.11.0

### Steps to Reproduce and Observed Behavior

```zig
export fn f(a: u32) callconv(.Naked) noreturn {
    _ = a;
    while (true) {}
}
```

Compile with `zig build-lib -target x86-linux-gnu test.zig`

### Expected Behavior

It is unclear whether this is valid code – the ABI of the target in question would imply that the argument should be passed on the stack, and that might not be clearly defined for `callconv(.Naked)`. However, this should emit an error message instead of segfaulting.

**Comment by nektro** [comment]
```
LLVM Emit Object... Can't get register for value!
UNREACHABLE executed at /home/meghan/src/llvm-17/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:1796!

Thread 1 "zig" received signal SIGABRT, Aborted.
0x00007fffea4a1adc in __pthread_kill_implementation () from /nix/store/dg8mpqqykmw9c7l0bgzzb5znkymlbfjw-glibc-2.37-8/lib/libc.so.6
(gdb) bt
#0  0x00007fffea4a1adc in __pthread_kill_implementation () from /nix/store/dg8mpqqykmw9c7l0bgzzb5znkymlbfjw-glibc-2.37-8/lib/libc.so.6
#1  0x00007fffea452cb6 in raise () from /nix/store/dg8mpqqykmw9c7l0bgzzb5znkymlbfjw-glibc-2.37-8/lib/libc.so.6
#2  0x00007fffea43c8ba in abort () from /nix/store/dg8mpqqykmw9c7l0bgzzb5znkymlbfjw-glibc-2.37-8/lib/libc.so.6
#3  0x00007fffeb16b4da in llvm::llvm_unreachable_internal (msg=msg@entry=0x7fffef7ba0d5 "Can't get register for value!", file=file@entry=0x7fffef7aec68 "/home/meghan/src/llvm-17/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp", line=line@entry=1796) at /home/meghan/src/llvm-17/llvm/lib/Support/ErrorHandling.cpp:212
#4  0x00007fffebcb7a97 in llvm::SelectionDAGBuilder::getValueImpl (this=0x35f9590, V=<optimized out>) at /home/meghan/src/llvm-17/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:1796
#5  0x00007fffebcbd32d in llvm::SelectionDAGBuilder::getValue (this=0x35f9590, V=<optimized out>) at /home/meghan/src/llvm-17/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:1613
#6  0x00007fffebccd0a0 in llvm::SelectionDAGBuilder::visitStore (this=0x35f9590, I=...) at /home/meghan/src/llvm-17/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:4372
#7  0x00007fffebce7802 in llvm::SelectionDAGBuilder::visit (this=0x35f9590, I=...) at /home/meghan/src/llvm-17/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:1191
#8  0x00007fffebd65597 in llvm::SelectionDAGISel::SelectBasicBlock (this=0x35f74a0, Begin=..., End=..., HadTailCall=@0x7ffffffea5c8: false) at /home/meghan/src/llvm-17/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:691
#9  0x00007fffebd6648c in llvm::SelectionDAGISel::SelectAllBasicBlocks (this=<optimized out>, Fn=...) at /home/meghan/src/llvm-17/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1700
#10 0x00007fffebd68268 in llvm::SelectionDAGISel::runOnMachineFunction (this=0x35f74a0, mf=...) at /home/meghan/src/llvm-17/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:482
#11 0x00007fffebd6a0da in llvm::SelectionDAGISel::runOnMachineFunction (this=<optimized out>, mf=...) at /home/meghan/src/llvm-17/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:663
#12 0x00007fffeeeb4f15 in (anonymous namespace)::X86DAGToDAGISel::runOnMachineFunction (this=0x35f74a0, MF=...) at /home/meghan/src/llvm-17/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp:191
#13 0x00007fffeb71f36e in llvm::MachineFunctionPass::runOnFunction (this=0x35f74a0, F=...) at /home/meghan/src/llvm-17/llvm/lib/CodeGen/MachineFunctionPass.cpp:91
#14 0x00007fffeb3d4325 in llvm::FPPassManager::runOnFunction (this=0x3596f00, F=...) at /home/meghan/src/llvm-17/llvm/lib/IR/LegacyPassManager.cpp:1435
#15 0x00007fffeb3d4521 in llvm::FPPassManager::runOnModule (this=0x3596f00, M=...) at /home/meghan/src/llvm-17/llvm/lib/IR/LegacyPassManager.cpp:1481
#16 0x00007fffeb3d4e24 in (anonymous namespace)::MPPassManager::runOnModule (M=..., this=<optimized out>) at /home/meghan/src/llvm-17/llvm/lib/IR/LegacyPassManager.cpp:1550
#17 llvm::legacy::PassManagerImpl::run (this=0x35e34c0, M=...) at /home/meghan/src/llvm-17/llvm/lib/IR/LegacyPassManager.cpp:535
#18 0x0000000002fbf5fb in ZigLLVMTargetMachineEmitToFile (targ_machine_ref=<optimized out>, module_ref=0x359b240, error_message=0x7ffffffed288, is_debug=<optimized out>, is_small=<optimized out>, time_report=<optimized out>, tsan=false, lto=false, asm_filename=0x0, bin_filename=0x35c33c0 "libtest.a.o", llvm_ir_filename=0x0, bitcode_filename=<optimized out>) at /home/meghan/src/zig/src/zig_llvm.cpp:357
#19 0x0000000001137e08 in codegen.llvm.Object.flushModule (self=0x3597b80, comp=0x35950a0, prog_node=0x7fffffff1288) at /home/meghan/src/zig/src/codegen/llvm.zig:1292
#20 0x0000000001158046 in link.Elf.flushModule (self=0x35970b0, comp=0x35950a0, prog_node=0x7fffffff1288) at /home/meghan/src/zig/src/link/Elf.zig:940
#21 0x000000000113055d in link.File.flushModule (base=0x3597300, comp=0x35950a0, prog_node=0x7fffffff1288) at link.zig:838
#22 0x0000000000e46795 in link.File.linkAsArchive (base=0x3597300, comp=0x35950a0, prog_node=0x7fffffff1288) at link.zig:1064
#23 0x0000000000b196f9 in link.File.flush (base=0x3597300, comp=0x35950a0, prog_node=0x7fffffff1288) at link.zig:815
#24 0x0000000000b190a6 in Compilation.flush (comp=0x35950a0, prog_node=0x7fffffff1288) at Compilation.zig:2649
#25 0x0000000000b5d2af in Compilation.update (comp=0x35950a0, main_progress_node=0x7fffffff1288) at Compilation.zig:2606
#26 0x0000000000b8c713 in main.updateModule (comp=0x35950a0) at main.zig:4276
#27 0x0000000000baf24d in main.buildOutputType (gpa=..., arena=..., all_args=..., arg_mode=...) at main.zig:3677
#28 0x00000000009bb108 in main.mainArgs (gpa=..., arena=..., args=...) at main.zig:280
#29 0x00000000009b82b6 in main.main () at main.zig:222
```
