### ISSUE TITLE
packed struct depending on itself crashes

### ISSUE THREAD

**Issue by wooster0** [ziglang/zig#20134]
### Zig Version

0.13.0-dev.344+b2588de6c

### Steps to Reproduce and Observed Behavior

```zig
const X = packed struct {
    x: @Type(.{ .Int = .{ .signedness = .unsigned, .bits = @sizeOf(X) } }),
};

comptime {
    _ = X{};
}
```
```
Segmentation fault
```

### Expected Behavior

```
x.zig:1:18: error: struct 'x.X' depends on itself
const X = packed struct {
          ~~~~~~~^~~~~~
```

**Comment by gooncreeper** [comment]
Smaller reproduction on `0.14.0-dev.2210+62f4a6b4d`
```Zig
test {
    _ = packed struct {
        x: @This(),
    };
}
```
Interestingly there is no backtrace for the segmentation fault unlike yours, so this could be a separate issue.

**Comment by Rexicon226** [comment]
Here's the trace

<details>

<summary>Stack Trace</summary>

```
#0  0x0000000001b10edb in Type.bitSizeInner__anon_175301 (ty=..., zcu=0xe9000019d2, tid=(unknown: 0xaa))
#1  0x000000000188360a in Type.bitSizeSema (ty=..., pt=...)
#2  0x0000000002002c86 in Sema.backingIntType (sema=0x7ffffe004920, struct_type=...)
#3  0x0000000001d4d3e1 in Sema.resolveStructLayout (sema=0x7ffffe004920, ty=...)
#4  0x0000000001aaa9b6 in Type.resolveStructInner (ty=..., pt=..., resolution=layout)
#5  0x0000000001874f37 in Type.resolveLayout (ty=..., pt=...)
#6  0x0000000001b12788 in Type.bitSizeInner__anon_175301 (ty=..., zcu=0x7fffd7fa8c00, tid=main)
#7  0x000000000188360a in Type.bitSizeSema (ty=..., pt=...)
#8  0x0000000002002c86 in Sema.backingIntType (sema=0x7ffffe00c6f0, struct_type=...)
#9  0x0000000001d4d3e1 in Sema.resolveStructLayout (sema=0x7ffffe00c6f0, ty=...)
#10 0x0000000001aaa9b6 in Type.resolveStructInner (ty=..., pt=..., resolution=layout)
#11 0x0000000001874f37 in Type.resolveLayout (ty=..., pt=...)
#12 0x0000000001b12788 in Type.bitSizeInner__anon_175301 (ty=..., zcu=0x7fffd7fa8c00, tid=main)
#13 0x000000000188360a in Type.bitSizeSema (ty=..., pt=...)
#14 0x0000000002002c86 in Sema.backingIntType (sema=0x7ffffe0144c0, struct_type=...)
#15 0x0000000001d4d3e1 in Sema.resolveStructLayout (sema=0x7ffffe0144c0, ty=...)
#16 0x0000000001aaa9b6 in Type.resolveStructInner (ty=..., pt=..., resolution=layout)
#17 0x0000000001874f37 in Type.resolveLayout (ty=..., pt=...)
#18 0x0000000001b12788 in Type.bitSizeInner__anon_175301 (ty=..., zcu=0x7fffd7fa8c00, tid=main)
#19 0x000000000188360a in Type.bitSizeSema (ty=..., pt=...)
#20 0x0000000002002c86 in Sema.backingIntType (sema=0x7ffffe01c290, struct_type=...)
```

</details>

**Comment by mlugg** [comment]
Fixed in https://codeberg.org/ziglang/zig/pulls/31403; now emits a compile error as expected.
