### ISSUE TITLE
Cannot build stage3 from HEAD: error: malloc(): unsorted double linked list corrupted

### ISSUE THREAD

**Issue by dimdin** [ziglang/zig#21801]
### Zig Version

0.14.0-dev.2050+4adf63aef

### Steps to Reproduce and Observed Behavior

Linux 6.1.0-26-amd64 Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux
llvm 19.1.2 (latest llvm .deb builds for debian stable from apt.llvm.org)
cc (Debian 12.2.0-14) gcc 12.2.0
```
cmake .. -DCMAKE_PREFIX_PATH=/usr/lib/llvm-19 -DCMAKE_BUILD_TYPE=Release -DZIG_NO_LIB=ON -GNinja
```
---

```
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring zig version 0.14.0-dev.2050+4adf63aef
-- Found llvm: -lLLVM-19;-lrt;-ldl;-lm;/usr/lib/x86_64-linux-gnu/libz3.so;-lz;-lzstd;-lxml2 (Required is at least version "19") 
-- Found clang: /usr/lib/llvm-19/lib/libclang-cpp.so.19.1 (Required is at least version "19") 
-- Found lld: /usr/lib/llvm-19/lib/liblldMinGW.a;/usr/lib/llvm-19/lib/liblldELF.a;/usr/lib/llvm-19/lib/liblldCOFF.a;/usr/lib/llvm-19/lib/liblldWasm.a;/usr/lib/llvm-19/lib/liblldMachO.a;/usr/lib/llvm-19/lib/liblldCommon.a (Required is at least version "19") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/din/zig/zig/build
[19/20] Building stage3
FAILED: stage3/bin/zig /home/din/zig/zig/build/stage3/bin/zig 
cd /home/din/zig/zig && /home/din/zig/zig/build/zig2 build --prefix /home/din/zig/zig/build/stage3 --zig-lib-dir /home/din/zig/zig/lib -Dversion-string=0.14.0-dev.2050+4adf63aef -Dtarget=native -Dcpu=native -Denable-llvm -Dconfig_h=/home/din/zig/zig/build/config.h -Dno-langref -Doptimize=ReleaseFast -Dstrip -Dno-lib
install
+- install zig
   +- zig build-exe zig ReleaseFast native failure
error: malloc(): unsorted double linked list corrupted

error: the following command terminated unexpectedly:
/home/din/zig/zig/build/zig2 build-exe --stack 33554432 /home/din/zig/zig/build/zigcpp/libzigcpp.a /usr/lib/llvm-19/lib/libclang-cpp.so.19.1 /usr/lib/llvm-19/lib/liblldMinGW.a /usr/lib/llvm-19/lib/liblldELF.a /usr/lib/llvm-19/lib/liblldCOFF.a /usr/lib/llvm-19/lib/liblldWasm.a /usr/lib/llvm-19/lib/liblldMachO.a /usr/lib/llvm-19/lib/liblldCommon.a -lLLVM-19 /usr/lib/x86_64-linux-gnu/libz3.so -lz -lzstd -lxml2 /usr/lib/gcc/x86_64-linux-gnu/12/libstdc++.so -lunwind -fstrip -fno-sanitize-thread -OReleaseFast -I /usr/lib/llvm-19/include -I /usr/lib/llvm-19/include -L /usr/lib/llvm-19/lib --dep aro --dep aro_translate_c --dep build_options -Mroot=/home/din/zig/zig/src/main.zig -Maro=/home/din/zig/zig/lib/compiler/aro/aro.zig --dep aro -Maro_translate_c=/home/din/zig/zig/lib/compiler/aro_translate_c.zig -Mbuild_options=/home/din/zig/zig/.zig-cache/c/3a7efa83fdf69f5f38c3a5b1efedf4fc/options.zig -lc --cache-dir /home/din/zig/zig/.zig-cache --global-cache-dir /home/din/.cache/zig --name zig -L /usr/lib/llvm-19/lib -I /usr/lib/llvm-19/include --zig-lib-dir /home/din/zig/zig/lib/ --listen=- 
Build Summary: 1/4 steps succeeded; 1 failed
install transitive failure
+- install zig transitive failure
   +- zig build-exe zig ReleaseFast native failure
error: the following build command failed with exit code 1:
/home/din/zig/zig/.zig-cache/o/c6526a05f9f9c85c2317975f06410842/build /home/din/zig/zig/build/zig2 /home/din/zig/zig/lib /home/din/zig/zig /home/din/zig/zig/.zig-cache /home/din/.cache/zig --seed 0xece8be0b -Z3f6f15b64f72cc8b --prefix /home/din/zig/zig/build/stage3 -Dversion-string=0.14.0-dev.2050+4adf63aef -Dtarget=native -Dcpu=native -Denable-llvm -Dconfig_h=/home/din/zig/zig/build/config.h -Dno-langref -Doptimize=ReleaseFast -Dstrip -Dno-lib
ninja: build stopped: subcommand failed.
```

### Expected Behavior

a few commits earlier it was building with the same setup (except llvm that also updated recently).

**Comment by xxxbxxx** [comment]
I also have the issue.  it's not always the exact same error.

ran it with `GLIBC_TUNABLES=glibc.malloc.check=3`
and I get this callstack:

```gdb
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, 
    no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ff1b5c80793 in __pthread_kill_internal (threadid=<optimized out>, signo=6)
    at pthread_kill.c:78
#2  0x00007ff1b5c27d0e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ff1b5c0f942 in __GI_abort () at abort.c:79
#4  0x00007ff1b5c107a7 in __libc_message_impl (fmt=fmt@entry=0x7ff1b5dc23a2 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:132
#5  0x00007ff1b5c8a8a5 in malloc_printerr (
    str=str@entry=0x7ff1b5dc5998 "malloc(): invalid next size (unsorted)") at malloc.c:5772
#6  0x00007ff1b5c8dd6c in _int_malloc (av=av@entry=0x7ff1b5df6ac0 <main_arena>, bytes=bytes@entry=1040)
    at malloc.c:4081
#7  0x00007ff1b5c8ef34 in __GI___libc_malloc (bytes=bytes@entry=1040) at malloc.c:3336
#8  0x00007ff1b5c8f352 in _mid_memalign (alignment=alignment@entry=8, bytes=bytes@entry=1040, 
    address=<optimized out>) at malloc.c:3582
#9  0x00007ff1b5c90c3c in __posix_memalign (memptr=0x7ffd430bf2f8, alignment=8, size=1040)
    at malloc.c:5798
#10 __posix_memalign (memptr=0x7ffd430bf2f8, alignment=8, size=1040) at malloc.c:5782
#11 0x0000000000407366 in heap_CAllocator_alignedAlloc__4317 (a0=1040, a1=3 '\003')
    at /var/home/xavier/src/zig/zig/build19/zig2.c:440012
#12 0x00000000004071e8 in heap_CAllocator_alloc__4320 (a0=0xaaaaaaaaaaaaaaaa, a1=1040, a2=3 '\003', 
    a3=5847164) at /var/home/xavier/src/zig/zig/build19/zig2.c:376281
#13 0x000000000040c12b in mem_Allocator_allocBytesWithAlignment__anon_32711__46232 (a0=..., a1=1040, 
    a2=5847164) at /var/home/xavier/src/zig/zig/build19/zig2.c:527198
#14 0x0000000000484620 in mem_Allocator_allocWithSizeAndAlignment__anon_75862__50669 (a0=..., a1=65, 
    a2=5847164) at /var/home/xavier/src/zig/zig/build19/zig2.c:549229
#15 0x0000000000484148 in mem_Allocator_alignedAlloc__anon_33614__49672 (a0=..., a1=65)
    at /var/home/xavier/src/zig/zig/build19/zig2.c:530825
#16 0x000000000059387c in array_list_ArrayListAligned_28_5b_5dconst_20u8_2cnull_29_ensureTotalCapacityPrecise__21049 (a0=0x7ffd430c14f8, a1=65) at /var/home/xavier/src/zig/zig/build19/zig2.c:549117
#17 0x0000000000593e47 in array_list_ArrayListAligned_28_5b_5dconst_20u8_2cnull_29_ensureTotalCapacity__21048 (a0=0x7ffd430c14f8, a1=40) at /var/home/xavier/src/zig/zig/build19/zig2.c:688296
#18 0x0000000000593d33 in array_list_ArrayListAligned_28_5b_5dconst_20u8_2cnull_29_addOne__21052 (
    a0=0x7ffd430c14f8) at /var/home/xavier/src/zig/zig/build19/zig2.c:525173
#19 0x0000000000593618 in array_list_ArrayListAligned_28_5b_5dconst_20u8_2cnull_29_append__21027 (
    a0=0x7ffd430c14f8, a1=...) at /var/home/xavier/src/zig/zig/build19/zig2.c:455049
#20 0x0000000002d1bf58 in link_Elf_linkWithLLD__5078 (a0=0xfeff5b0, a1=..., a2=0 '\000', a3=...)
    at /var/home/xavier/src/zig/zig/build19/zig2.c:616120
#21 0x00000000025fa2f2 in link_Elf_flush__5063 (a0=0xfeff5b0, a1=..., a2=0 '\000', a3=...)
    at /var/home/xavier/src/zig/zig/build19/zig2.c:616903
#22 0x00000000025f6ed9 in link_File_flush__5000 (a0=0xfeff6e0, a1=..., a2=0 '\000', a3=...)
    at /var/home/xavier/src/zig/zig/build19/zig2.c:486706
#23 0x00000000007ef4a0 in Compilation_flush__5334 (a0=0xfefe200, a1=..., a2=..., a3=0 '\000', a4=...)
    at /var/home/xavier/src/zig/zig/build19/zig2.c:412676
#24 0x00000000007d3caf in Compilation_update__5332 (a0=0xfefe200, a1=...)
    at /var/home/xavier/src/zig/zig/build19/zig2.c:414537
#25 0x000000000046aa72 in main_updateModule__290 (a0=0xfefe200, a1=0 '\000', a2=...)
    at /var/home/xavier/src/zig/zig/build19/zig2.c:427428
#26 0x000000000042a1f3 in main_buildOutputType__282 (a0=..., a1=..., a2=..., a3=...)
    at /var/home/xavier/src/zig/zig/build19/zig2.c:436062
#27 0x0000000000405be0 in main_mainArgs__272 (a0=..., a1=..., a2=...)
    at /var/home/xavier/src/zig/zig/build19/zig2.c:439678
#28 0x0000000000404718 in main_main__270 () at /var/home/xavier/src/zig/zig/build19/zig2.c:376161
#29 0x00000000004041d7 in main (a0=47, a1=0x7ffd430d1668, a2=0x7ffd430d17e8)
    at /var/home/xavier/src/zig/zig/build19/zig2.c:375801
```

**Comment by alexrp** [comment]
This seems like it might be recent breakage from the linker work? cc @andrewrk @kubkon

**Comment by xxxbxxx** [comment]
with this workaround I got a working stage3!

```diff
diff --git a/src/link/Elf.zig b/src/link/Elf.zig
index d02d98800d..ac25457e6f 100644
--- a/src/link/Elf.zig
+++ b/src/link/Elf.zig
@@ -1673,6 +1673,8 @@ fn linkWithLLD(self: *Elf, arena: Allocator, tid: Zcu.PerThread.Id, prog_node: s
         // Create an LLD command line and invoke it.
         var argv = std.ArrayList([]const u8).init(gpa);
         defer argv.deinit();
+        try argv.ensureTotalCapacity(1000);
+
         // We will invoke ourselves as a child process to gain access to LLD.
         // This is necessary because LLD does not behave properly as a library -
         // it calls exit() and does not reset all global data between invocations.
```

**Comment by xxxbxxx** [comment]
ah! the bug probably is:

```diff
diff --git a/src/link/Elf.zig b/src/link/Elf.zig
index d02d98800d..04add93580 100644
--- a/src/link/Elf.zig
+++ b/src/link/Elf.zig
@@ -1973,11 +1973,11 @@ fn linkWithLLD(self: *Elf, arena: Allocator, tid: Zcu.PerThread.Id, prog_node: s
                     switch ((@as(u2, @intFromBool(lib_as_needed)) << 1) | @intFromBool(as_needed)) {
                         0b00, 0b11 => {},
                         0b01 => {
-                            argv.appendAssumeCapacity("--no-as-needed");
+                            argv.append("--no-as-needed");
                             as_needed = false;
                         },
                         0b10 => {
-                            argv.appendAssumeCapacity("--as-needed");
+                            argv.append("--as-needed");
                             as_needed = true;
                         },
                     }
@@ -1986,12 +1986,12 @@ fn linkWithLLD(self: *Elf, arena: Allocator, tid: Zcu.PerThread.Id, prog_node: s
                     // libraries and not static libraries (the check for that needs to be earlier),
                     // but they could be full paths to .so files, in which case we
                     // want to avoid prepending "-l".
-                    argv.appendAssumeCapacity(try dso.path.toString(arena));
+                    argv.append(try dso.path.toString(arena));
                 },
             };

             if (!as_needed) {
-                argv.appendAssumeCapacity("--as-needed");
+                argv.append("--as-needed");
                 as_needed = true;
             }
```
