### ISSUE TITLE
crash instead of compile error for slice used as array init expr when non-zero elements

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#2764]
Please rename this issue after narrowing in on the problem...

Note: I'm not sure if this code should even compile. I was halfway through trying to make a minimal test case for another issue, but after hitting the assertion I gave up.

```zig
var bullets = []u8{0, 1, 2, 3};

test "" {
    if (for (bullets) |*slot| {
        break true;
    } else null) |slot| {

    }
}
```

Output:

```
dbandstra@dbandstra-desktop:~/oxid$ zig test test.zig
Assertion failed. This is a bug in the Zig compiler.
???:?:?: 0x564e8e712c69 in ??? (???)


???:?:?: 0x564e8e6dbc3a in ??? (???)


???:?:?: 0x564e8e67e937 in ??? (???)


???:?:?: 0x564e8e69c826 in ??? (???)


???:?:?: 0x564e8e69d7b0 in ??? (???)


???:?:?: 0x564e8e66906b in ??? (???)


???:?:?: 0x564e8e6df868 in ??? (???)


???:?:?: 0x564e8e6e6974 in ??? (???)


???:?:?: 0x564e8e6e6dc8 in ??? (???)


???:?:?: 0x564e8e680345 in ??? (???)


???:?:?: 0x564e8e698a6a in ??? (???)


???:?:?: 0x564e8e69cf46 in ??? (???)


???:?:?: 0x564e8e69d7b0 in ??? (???)


???:?:?: 0x564e8e6e7cbb in ??? (???)


???:?:?: 0x564e8e6e8112 in ??? (???)


???:?:?: 0x564e8e6e8fc7 in ??? (???)


???:?:?: 0x564e8e635af2 in ??? (???)


???:?:?: 0x564e8e639516 in ??? (???)


???:?:?: 0x564e8e611ca9 in ??? (???)


???:?:?: 0x7fbece929b96 in ??? (???)


???:?:?: 0x54fe258d4c544154 in ??? (???)


Segmentation fault (core dumped)
```

There's a 5 second delay between the message about the assertion and the stack trace.

I'm on Ubuntu 18

**Comment by tiehuis** [comment]
Reduced test case:

```zig
test "" {
    for ([]u8{0}) |_| {}
}
```

Backtrace:

```
#0  0x0000555555ec4e10 in std.debug.StackIterator.next (self=0x7fffffffc410) at /home/me/src/zig/std/debug.zig:265
#1  0x0000555555e956a7 in std.debug.writeCurrentStackTrace (out_stream=0x5555582f38a0 <stderr_file_out_stream+8>, debug_info=0x5555582f38c0 <self_debug_info>, tty_color=false, start_addr=...) at /home/me/src/zig/std/debug.zig:275
#2  0x0000555555e8c4c9 in std.debug.dumpCurrentStackTrace (start_addr=...) at /home/me/src/zig/std/debug.zig:96
#3  0x0000555555e86bf0 in std.debug.panicExtra (trace=0x0, first_trace_addr=..., arg2=...) at /home/me/src/zig/std/debug.zig:207
#4  0x0000555555e86b08 in std.special.panic (msg=..., error_return_trace=0x0) at /home/me/src/zig/std/special/panic.zig:26
#5  0x0000555555e86c8a in stage2_panic (ptr=0x55555790d9f0 "Assertion failed. This is a bug in the Zig compiler.", len=52) at stage1.zig:37
#6  0x0000555555e4fc5b in assert (ok=false) at /home/me/src/zig/src/util.cpp:28
#7  0x0000555555df2958 in ir_analyze_instruction_elem_ptr (ira=0x5555585dc130, elem_ptr_instruction=0x5555585dabb0) at /home/me/src/zig/src/ir.cpp:17283
#8  0x0000555555e10847 in ir_analyze_instruction_base (ira=0x5555585dc130, instruction=0x5555585dabb0) at /home/me/src/zig/src/ir.cpp:25308
#9  0x0000555555e117d1 in ir_analyze (codegen=0x555558354b10, old_exec=0x5555585da0b0, new_exec=0x5555585dc030, expected_type=0x0, expected_type_source_node=0x0) at /home/me/src/zig/src/ir.cpp:25629
#10 0x0000555555ddd08c in ir_eval_const_value (codegen=0x555558354b10, scope=0x55555839f510, node=0x5555583a0eb0, expected_type=0x0, backward_branch_count=0x7fffffffcb48, backward_branch_quota=0x7fffffffcb50, fn_entry=0x0, c_import_buf=0x0, source_node=0x5555583a0eb0, exec_name=0x55555839f7e0, parent_exec=0x0, expected_type_source_node=0x0) at /home/me/src/zig/src/ir.cpp:11372
#11 0x0000555555e53889 in analyze_const_value (g=0x555558354b10, scope=0x55555839f510, node=0x5555583a0eb0, type_entry=0x0, type_name=0x55555839f7e0) at /home/me/src/zig/src/analyze.cpp:973
#12 0x0000555555e5a995 in resolve_decl_var (g=0x555558354b10, tld_var=0x5555583a1ae0) at /home/me/src/zig/src/analyze.cpp:3206
#13 0x0000555555e5ade9 in resolve_top_level_decl (g=0x555558354b10, tld=0x5555583a1ae0, source_node=0x5555583a12c0) at /home/me/src/zig/src/analyze.cpp:3281
#14 0x0000555555df4366 in ir_analyze_decl_ref (ira=0x5555585d9ae0, source_instruction=0x5555585d5d60, tld=0x5555583a1ae0) at /home/me/src/zig/src/ir.cpp:17735
#15 0x0000555555e0ca8b in ir_analyze_instruction_decl_ref (ira=0x5555585d9ae0, instruction=0x5555585d5d60) at /home/me/src/zig/src/ir.cpp:24158
#16 0x0000555555e10f67 in ir_analyze_instruction_base (ira=0x5555585d9ae0, instruction=0x5555585d5d60) at /home/me/src/zig/src/ir.cpp:25460
#17 0x0000555555e117d1 in ir_analyze (codegen=0x555558354b10, old_exec=0x5555583b4368, new_exec=0x5555583b4458, expected_type=0x5555583b4660, expected_type_source_node=0x0) at /home/me/src/zig/src/ir.cpp:25629
#18 0x0000555555e5bcdc in analyze_fn_ir (g=0x555558354b10, fn_table_entry=0x5555583b4300, return_type_node=0x0) at /home/me/src/zig/src/analyze.cpp:3665
#19 0x0000555555e5c133 in analyze_fn_body (g=0x555558354b10, fn_table_entry=0x5555583b4300) at /home/me/src/zig/src/analyze.cpp:3752
#20 0x0000555555e5cfe8 in semantic_analyze (g=0x555558354b10) at /home/me/src/zig/src/analyze.cpp:3999
#21 0x0000555555da9b13 in gen_root_source (g=0x555558354b10) at /home/me/src/zig/src/codegen.cpp:8641
#22 0x0000555555dad537 in codegen_build_and_link (g=0x555558354b10) at /home/me/src/zig/src/codegen.cpp:9589
#23 0x0000555555d85cca in main (argc=3, argv=0x7fffffffd548) at /home/me/src/zig/src/main.cpp:1190
```

This was introduced during the change to `[_]` array initialization I believe.

**Comment by mikdusan** [comment]
#### reduction

```zig
export fn foo() void {
    _ = []u8{ 0, 1 };  // BAD: SIGABRT
    _ = [_]u8{ 0, 1 }; // GOOD
    _ = []u8{};        // GOOD: error: expected array type or [_], found slice
}
```

#### AST block

```
  Block
    BinOpExpr
      Symbol
      ContainerInitExpr
        ArrayType
          Symbol
        IntLiteral
        IntLiteral
    BinOpExpr
      Symbol
      ContainerInitExpr
        InferredArrayType
        IntLiteral
        IntLiteral
    BinOpExpr
      Symbol
      ContainerInitExpr
        ArrayType
          Symbol
```
