### ISSUE TITLE
improve DWARF debug info handling (release mode stack traces)

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2849]
Looking into the CI failure on #2843 and trying to replicate locally I got this segfault when trying to compile in release-safe mode:

```
/home/daurnimator/src/zig/std/debug.zig:283:89: 0x22149e in std.debug.StackIterator.next (test)
                const return_address = @intToPtr(*const usize, self.fp + @sizeOf(usize)).*;
                                                                                        ^
/home/daurnimator/src/zig/std/debug.zig:233:26: 0x20fa55 in std.debug.panicExtra (test)
    dumpCurrentStackTrace(first_trace_addr);
                         ^
/home/daurnimator/src/zig/std/special/test_runner.zig:13:25: 0x224caa in std.special.posixCallMainAndExit (test)
        if (test_fn.func()) |_| {
                        ^
```

Running under gdb:
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000022149e in std.debug.StackIterator.next (self=0x7fffffff96c0) at /home/daurnimator/src/zig/std/debug.zig:283
283	                const return_address = @intToPtr(*const usize, self.fp + @sizeOf(usize)).*;
─── Assembly ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
0x0000000000221497 ? jb     0x2214e6 <std.debug.StackIterator.next+118>
0x0000000000221499 ? test   %rcx,%rcx
0x000000000022149c ? je     0x2214f2 <std.debug.StackIterator.next+130>
0x000000000022149e ? mov    (%rcx),%rcx
0x00000000002214a1 ? cmp    %rcx,(%rsi)
0x00000000002214a4 ? je     0x2214d5 <std.debug.StackIterator.next+101>
0x00000000002214a6 ? mov    (%rax),%rax
─── Expressions ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─── History ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─── Memory ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─── Registers ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   rax 0x000000006474e551     rbx 0x0000000000000001     rcx 0x000000006474e559     rdx 0x00007fffffff93c8     rsi 0x00007fffffff96c0 
   rdi 0x00007fffffff9798     rbp 0x00007fffffff97f0     rsp 0x00007fffffff95b0      r8 0x00007fffffffc128      r9 0x000000000000003d 
   r10 0x00007fffffff9020     r11 0x0000000000000202     r12 0x00007fffffff96c0     r13 0x00007fffffff97a8     r14 0x00007fffffff9798 
   r15 0x0000000000000000     rip 0x000000000022149e  eflags [ PF IF RF ]            cs 0x00000033              ss 0x0000002b         
    ds 0x00000000              es 0x00000000              fs 0x00000000              gs 0x00000000         
─── Source ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
278         self.fp = @intToPtr(*const usize, self.fp).*;
279         if (self.fp == 0) return null;
280 
281         if (self.first_addr) |addr| {
282             while (self.fp != 0) : (self.fp = @intToPtr(*const usize, self.fp).*) {
283                 const return_address = @intToPtr(*const usize, self.fp + @sizeOf(usize)).*;
284                 if (addr == return_address) {
285                     self.first_addr = null;
286                     return return_address;
287                 }
288             }
─── Stack ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[0] from 0x000000000022149e in std.debug.StackIterator.next at /home/daurnimator/src/zig/std/debug.zig:283
arg self = 0x7fffffff96c0
[1] from 0x00000000002141eb in std.debug.writeCurrentStackTrace at /home/daurnimator/src/zig/std/debug.zig:301
arg out_stream = 0x227038 <stderr_file_out_stream+8>
arg debug_info = <optimized out>
arg tty_color = <optimized out>
arg start_addr = <optimized out>
[+]
─── Threads ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[1] id 18676 name test from 0x000000000022149e in std.debug.StackIterator.next at /home/daurnimator/src/zig/std/debug.zig:283
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>>> bt
#0  0x000000000022149e in std.debug.StackIterator.next (self=0x7fffffff96c0) at /home/daurnimator/src/zig/std/debug.zig:283
#1  0x00000000002141eb in std.debug.writeCurrentStackTrace (out_stream=0x227038 <stderr_file_out_stream+8>, debug_info=<optimized out>, tty_color=<optimized out>, start_addr=...) at /home/daurnimator/src/zig/std/debug.zig:301
#2  std.debug.dumpCurrentStackTrace (start_addr=...) at /home/daurnimator/src/zig/std/debug.zig:96
#3  0x000000000020fa56 in std.debug.panicExtra (trace=0x0, first_trace_addr=..., arg2=...) at /home/daurnimator/src/zig/std/debug.zig:233
#4  0x000000000020f996 in std.special.panic (msg=..., error_return_trace=0x7fffffff9798) at /home/daurnimator/src/zig/std/special/panic.zig:28
#5  0x00000000002148ed in std.packed_int_array.PackedIntIo(bool,builtin.Endian.Little).getBits (bit_index=<optimized out>, bytes=...) at /home/daurnimator/src/zig/std/packed_int_array.zig:66
#6  0x00000000002148ed in std.packed_int_array.PackedIntIo(bool,builtin.Endian.Little).get (bytes=..., index=<optimized out>, bit_offset=)
#7  0x0000000000210f5a in BloomFilter(1024,8,u1,builtin.Endian.Little,hashFunc).getCell (self=..., cell=<optimized out>) at /home/daurnimator/src/zig/std/bloom_filter.zig:66
#8  BloomFilter(1024,8,u1,builtin.Endian.Little,hashFunc).contains (self=..., item=...) at /home/daurnimator/src/zig/std/bloom_filter.zig:127
#9  0x000000000020bdaf in test "repro" () at /home/daurnimator/src/zig/std/bloom_filter.zig:332
#10 0x0000000000224cab in std.special.main () at /home/daurnimator/src/zig/std/special/test_runner.zig:13
#11 std.special.callMain () at /home/daurnimator/src/zig/std/special/start.zig:146
#12 std.special.callMainWithArgs (argc=<optimized out>, argv=<optimized out>, envp=...) at /home/daurnimator/src/zig/std/special/start.zig:118
#13 std.special.posixCallMainAndExit () at /home/daurnimator/src/zig/std/special/start.zig:107
#14 0x00000000002247d0 in std.special._start () at /home/daurnimator/src/zig/std/special/start.zig:66
```

**Comment by andrewrk** [comment]
oh, this is actually #398.
