### ISSUE TITLE
assert fail when "implicitly" casting to [N]u8 from []const u8

### ISSUE THREAD

**Issue by lun-4** [ziglang/zig#2870]
Unsure if this is a duplicate. Maybe related to #2749?

```zig
const std = @import("std");

const S = struct {
    field: [50]u8,
};

pub fn main() !void {
    var p = try std.heap.direct_allocator.alloc(u8, 1024);
    const pc = p;
    const s = S{ .field = pc[0..] };
}
```

```
#6  0x0000000000b41411 in assert (ok=false) at src/util.cpp:28
#7  0x0000000000a8b99b in ir_render_slice (g=0x375c040, executable=0x9ab0f88, instruction=0x9c7f700) at src/codegen.cpp:4751
#8  0x0000000000a8f584 in ir_render_instruction (g=0x375c040, executable=0x9ab0f88, instruction=0x9c7f700) at src/codegen.cpp:5707
#9  0x0000000000a8fca2 in ir_render (g=0x375c040, fn_entry=0x9ab0e30) at src/codegen.cpp:5833
#10 0x0000000000a94e11 in do_code_gen (g=0x375c040) at src/codegen.cpp:7010
```

**Comment by lun-4** [comment]
Nowadays that causes a compile error (likely after the slice/array safety changes), which is better than an assert trip.
