### ISSUE TITLE
segfault when importing a C header containing `#include "stdio.h"`

### ISSUE THREAD

**Issue by SamTebbs33** [ziglang/zig#2988]
`zig build-exe` segfaults in `err_msg_create_with_offset` when importing and including a c header file that contains `#include "stdio.h"`

reproduce.h
```
#include "stdio.h"
```
reproduce.zig
```
const lib = @cImport({ @cInclude("reproduce.h"); });

pub fn main() void {
    lib.foo();
}
```
command
```
$ zig build-exe reproduce.zig --library reproduce --library c -isystem /usr/include
Segmentation fault at address 0x230
```
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000eee7ce in err_msg_create_with_offset (path=0xcd17df0, line=0, column=0, offset=561, source=0x0, msg=0xcd17d70)
    at /home/samteb01/repos/zig/src/errmsg.cpp:97
97	        if (source[line_start_offset] == '\n') {
(gdb) bt
#0  0x0000000000eee7ce in err_msg_create_with_offset (path=0xcd17df0, line=0, column=0, offset=561, source=0x0, msg=0xcd17d70)
    at /home/samteb01/repos/zig/src/errmsg.cpp:97
#1  0x0000000000f3d9d7 in ir_analyze_instruction_c_import (ira=0xcd0a690, instruction=0xcd0a280)
    at /home/samteb01/repos/zig/src/ir.cpp:21296
#2  0x0000000000f4d1aa in ir_analyze_instruction_base (ira=0xcd0a690, instruction=0xcd0a280)
    at /home/samteb01/repos/zig/src/ir.cpp:25579
#3  0x0000000000f4ddca in ir_analyze (codegen=0x6bd1b60, old_exec=0xcd09f70, new_exec=0xcd0a590, expected_type=0x0, 
    expected_type_source_node=0x0) at /home/samteb01/repos/zig/src/ir.cpp:25828
#4  0x0000000000f19b6f in ir_eval_const_value (codegen=0x6bd1b60, scope=0x6c18900, node=0x6c18d70, expected_type=0x0, 
    backward_branch_count=0x7fffffffda28, backward_branch_quota=0x7fffffffda30, fn_entry=0x0, c_import_buf=0x0, source_node=0x6c18d70, 
    exec_name=0x6c16e10, parent_exec=0x0, expected_type_source_node=0x0) at /home/samteb01/repos/zig/src/ir.cpp:11474
#5  0x0000000000f90916 in analyze_const_value (g=0x6bd1b60, scope=0x6c18900, node=0x6c18d70, type_entry=0x0, type_name=0x6c16e10)
    at /home/samteb01/repos/zig/src/analyze.cpp:975
#6  0x0000000000f9780a in resolve_decl_var (g=0x6bd1b60, tld_var=0x6c194f0) at /home/samteb01/repos/zig/src/analyze.cpp:3210
#7  0x0000000000f9815c in resolve_top_level_decl (g=0x6bd1b60, tld=0x6c194f0, source_node=0x6c190e0)
    at /home/samteb01/repos/zig/src/analyze.cpp:3397
#8  0x0000000000f30a36 in ir_analyze_decl_ref (ira=0xcd09b40, source_instruction=0xcd09060, tld=0x6c194f0)
    at /home/samteb01/repos/zig/src/ir.cpp:17843
#9  0x0000000000f48f7a in ir_analyze_instruction_decl_ref (ira=0xcd09b40, instruction=0xcd09060)
    at /home/samteb01/repos/zig/src/ir.cpp:24323
#10 0x0000000000f4d53a in ir_analyze_instruction_base (ira=0xcd09b40, instruction=0xcd09060)
    at /home/samteb01/repos/zig/src/ir.cpp:25655
#11 0x0000000000f4ddca in ir_analyze (codegen=0x6bd1b60, old_exec=0xccec7a8, new_exec=0xccec898, expected_type=0x6be14a0, 
    expected_type_source_node=0x6c18fa0) at /home/samteb01/repos/zig/src/ir.cpp:25828
#12 0x0000000000f99057 in analyze_fn_ir (g=0x6bd1b60, fn_table_entry=0xccec740, return_type_node=0x6c18fa0)
    at /home/samteb01/repos/zig/src/analyze.cpp:3789
#13 0x0000000000f994a3 in analyze_fn_body (g=0x6bd1b60, fn_table_entry=0xccec740) at /home/samteb01/repos/zig/src/analyze.cpp:3876
#14 0x0000000000f99de6 in semantic_analyze (g=0x6bd1b60) at /home/samteb01/repos/zig/src/analyze.cpp:4008
#15 0x0000000000ee5d2b in gen_root_source (g=0x6bd1b60) at /home/samteb01/repos/zig/src/codegen.cpp:8620
#16 0x0000000000ee9525 in codegen_build_and_link (g=0x6bd1b60) at /home/samteb01/repos/zig/src/codegen.cpp:9557
#17 0x0000000000ebd9ba in main (argc=9, argv=0x7fffffffe478) at /home/samteb01/repos/zig/src/main.cpp:1207
```
`source` is `0x0`.

Note that this only happens when the header file is in `/usr/include`. I put it in a local directory and changed the `-isystem` parameter value to that directory and there was no segfault. Also note that changing the header to contain `#include <stdio.h>` does not produce a segfault.

**Comment by SamTebbs33** [comment]
Here is a potentially interesting snippet from my gdb session.
```
Breakpoint 3, ir_analyze_instruction_c_import (ira=0xcd0c020, instruction=0xcd0bc10) at /home/samteb01/repos/zig/src/ir.cpp:21291
21291	                Stage2ErrorMsg *clang_err = &errors_ptr[i];
(gdb) p *clang_err
$14 = {filename_ptr = 0xcdcc770 "/home/samteb01/repos/zig/build/lib/zig/include/stdarg.h", filename_len = 55, 
  msg_ptr = 0xcdd3ab0 "parameter named '__gnuc_va_list' is missing", msg_len = 43, 
  source = 0xcdd8b50 "/*===---- stdarg.h - Variable argument handling ", '-' <repeats 28 times>, "===\n *\n * Copyright (c) 2008 Eli Friedman\n *\n * Permission is hereby granted, free of charge, to any person obtaining a copy"..., line = 47, column = 26, offset = 1976}
(gdb) s
21292	                ErrorMsg *err_msg = err_msg_create_with_offset(
(gdb) p *clang_err
$15 = {filename_ptr = 0x0, filename_len = 215406896, msg_ptr = 0xcdb25b0 "too many errors emitted, stopping now", msg_len = 37, 
  source = 0x0, line = 0, column = 0, offset = 561}
(gdb) 

```
This was on the final iteration of the loop. Should a check be added for this edge case where clang doesn't emit all errors in full?
