### ISSUE TITLE
segmentation fault on @bitCast

### ISSUE THREAD

**Issue by jzck** [ziglang/zig#3010]
Hello, find below a minimum example to reproduce:

```
// this example works fine, even without aligning bytes
// pub fn main() void {
//     const bytes = [_]u8{ 255, 255, 255, 255 };
//     const ip = @bitCast(u32, bytes);
// }
```

```
// this segfaults
// crash.zig
pub fn main() void {
    const ip = @bitCast(u32, [_]u8{ 255, 255, 255, 255 });
}
```

```
$ zig build-exe crash.zig
???:?:?: 0x7fbc1472869d in ??? (???)


???:?:?: 0x7fbc1b0fce5f in ??? (???)


???:?:?: 0x7fbc1b0f9bbf in ??? (???)


integer overflow
???:?:?: 0x7fbc147cb17c in ??? (???)


???:?:?: 0x7fbc147b2d71 in ??? (???)


???:?:?: 0x7fbc187e145a in ??? (???)


???:?:?: 0x7fbc1b0fce5f in ??? (???)


???:?:?: 0x7fbc1b0f9bbf in ??? (???)


Aborted (core dumped)
```

I couldn't find any similar issues, and I couldn't find a reason that this code is invalid.

**Comment by SamTebbs33** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000f4ca77 in ir_analyze_instruction_end_expr (ira=0xd005520, instruction=0xd004f50) at /home/samteb01/repos/zig/src/ir.cpp:25409
25409	    if (type_is_invalid(value->value.type))
(gdb) bt
#0  0x0000000000f4ca77 in ir_analyze_instruction_end_expr (ira=0xd005520, instruction=0xd004f50) at /home/samteb01/repos/zig/src/ir.cpp:25409
#1  0x0000000000f4dbcc in ir_analyze_instruction_base (ira=0xd005520, instruction=0xd004f50) at /home/samteb01/repos/zig/src/ir.cpp:25795
#2  0x0000000000f4df03 in ir_analyze (codegen=0x6bd0ac0, old_exec=0xcfe66e8, new_exec=0xcfe67d8, expected_type=0x6bdf9c0, expected_type_source_node=0x6c18380) at /home/samteb01/repos/zig/src/ir.cpp:25852
#3  0x0000000000f9918f in analyze_fn_ir (g=0x6bd0ac0, fn_table_entry=0xcfe6680, return_type_node=0x6c18380) at /home/samteb01/repos/zig/src/analyze.cpp:3789
#4  0x0000000000f995db in analyze_fn_body (g=0x6bd0ac0, fn_table_entry=0xcfe6680) at /home/samteb01/repos/zig/src/analyze.cpp:3876
#5  0x0000000000f99f1e in semantic_analyze (g=0x6bd0ac0) at /home/samteb01/repos/zig/src/analyze.cpp:4008
#6  0x0000000000ee5d95 in gen_root_source (g=0x6bd0ac0) at /home/samteb01/repos/zig/src/codegen.cpp:8626
#7  0x0000000000ee958f in codegen_build_and_link (g=0x6bd0ac0) at /home/samteb01/repos/zig/src/codegen.cpp:9563
#8  0x0000000000ebd9ba in main (argc=3, argv=0x7fffffffe4e8) at /home/samteb01/repos/zig/src/main.cpp:1207
```
