### ISSUE TITLE
Compiler assertion fails - asm “mov %[s], sp”

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#3030]
pub fn main() void {
        var sp = asm("mov %[s], sp”
            : [sp] "=r" (-> usize));

The [s] causes a compiler assertion to fail. This is a misspelling of [sp].

**Comment by SamTebbs33** [comment]
```
#0  assert (ok=false) at /home/samteb01/repos/zig/src/util.cpp:27
#1  0x0000000000ed38ef in ir_render_asm (g=0x6bd0ac0, executable=0xcfe54c8, instruction=0xd0030e0)
    at /home/samteb01/repos/zig/src/codegen.cpp:3861
#2  0x0000000000eda7eb in ir_render_instruction (g=0x6bd0ac0, executable=0xcfe54c8, instruction=0xd0030e0)
    at /home/samteb01/repos/zig/src/codegen.cpp:5557
#3  0x0000000000edb0fb in ir_render (g=0x6bd0ac0, fn_entry=0xcfe5370) at /home/samteb01/repos/zig/src/codegen.cpp:5719
#4  0x0000000000ee00ee in do_code_gen (g=0x6bd0ac0) at /home/samteb01/repos/zig/src/codegen.cpp:6896
#5  0x0000000000ee96e3 in codegen_build_and_link (g=0x6bd0ac0) at /home/samteb01/repos/zig/src/codegen.cpp:9586
#6  0x0000000000ebd9ba in main (argc=3, argv=0x7fffffffe4f8) at /home/samteb01/repos/zig/src/main.cpp:1207
```
It's failing the assertion at
```
case AsmTokenIdVar:
    {
        size_t index = find_asm_index(g, asm_node, asm_token, src_template);
        assert(index < SIZE_MAX);
        ...
    }
```
`SIZE_MAX` is being returned as the identifier doesn't exist in the input/output section, which is valid state so should be changed from an assertion to a compiler error.
