### ISSUE TITLE
Compiler segmentation fault on switch statement

### ISSUE THREAD

**Issue by user00e00** [ziglang/zig#3107]
Problematic code:
```zig
// version: 0.4.0+81c441f8
pub fn main() void{
    _ = digitToCharCustom(4);
}

fn digitToCharCustom(digit: u8) u8 {
    return switch (digit) {
        0 => '.',
        1...9 => digit + '0',
        10...35 => digit + 'a' - 10,
        else => unreachable,
    };
}
```
Result:
```
Segmentation fault at address 0x7f57c6afb568
???:?:?: 0x7f3fb98fbc84 in ??? (???)


???:?:?: 0x7f3fbe50321f in ??? (???)
```

I believe this compiled fine on the 0.4 release.

**Comment by FireFox317** [comment]
In master this doesn't segfault, but generates invalid LLVM:
```
PHINode should have one entry for each predecessor of its parent basic block!
  %13 = phi i8 [ %7, %OverflowOk ], [ %18, %OverflowOk6 ], !dbg !47
LLVM ERROR: Broken module found, compilation aborted!
```
This issue should also solve the following test case (right now this always returns 2):
```
test "return switch case with ranges and 'normal' switch statements" {
    expect(number(8) == 3);
}

fn number(digit: u8) u8 {
    return switch (digit) {
        0 => u8(1),
        2...4 => u8(2),
        8 => u8(3),
        else => unreachable,
    };
}
```

**Comment by SamTebbs33** [comment]
When called with --verbose-ir it fails an assertion

```
#0  stage2_panic (ptr=0x55555a74a6f0 "Assertion failed. This is a bug in the Zig compiler.", len=52) at stage1.zig:37
#1  0x00005555564dc779 in assert (ok=false) at /home/sam/repos/zig/src/util.cpp:28
#2  0x00005555564ed7dc in render_const_val_ptr (g=0x55555c3f9810, buf=0x7fffffffdc90, const_val=0x55555cf49780,
    type_entry=0x55555cf3d820) at /home/sam/repos/zig/src/analyze.cpp:5340
#3  0x00005555564ee2cf in render_const_value (g=0x55555c3f9810, buf=0x7fffffffdc90, const_val=0x55555cf49780)
    at /home/sam/repos/zig/src/analyze.cpp:5542
#4  0x00005555564acff4 in ir_print_const_value (irp=0x7fffffffdd70, const_val=0x55555cf49780)
    at /home/sam/repos/zig/src/ir_print.cpp:39
#5  0x00005555564ad0c0 in ir_print_other_instruction (irp=0x7fffffffdd70, instruction=0x55555cf49770)
    at /home/sam/repos/zig/src/ir_print.cpp:53
#6  0x00005555564ad19b in ir_print_return (irp=0x7fffffffdd70, return_instruction=0x55555cf499b0)
    at /home/sam/repos/zig/src/ir_print.cpp:70
#7  0x00005555564b3cdb in ir_print_instruction (irp=0x7fffffffdd70, instruction=0x55555cf499b0)
    at /home/sam/repos/zig/src/ir_print.cpp:1647
#8  0x00005555564b4d9e in ir_print (codegen=0x55555c3f9810, f=0x7ffff79a74e0 <_IO_2_1_stderr_>, executable=0x55555cf47e60,
    indent_size=2) at /home/sam/repos/zig/src/ir_print.cpp:2167
#9  0x0000555556467d12 in ir_eval_const_value (codegen=0x55555c3f9810, scope=0x55555c8db050, node=0x55555c91db10,
    expected_type=0x0, backward_branch_count=0x7fffffffde68, backward_branch_quota=0x7fffffffde70, fn_entry=0x0,
    c_import_buf=0x0, source_node=0x55555c91db10, exec_name=0x7ffff772bae8, parent_exec=0x0, expected_type_source_node=0x0)
    at /home/sam/repos/zig/src/ir.cpp:11492
#10 0x00005555564e0551 in analyze_const_value (g=0x55555c3f9810, scope=0x55555c8db050, node=0x55555c91db10, type_entry=0x0,
    type_name=0x7ffff772bae8) at /home/sam/repos/zig/src/analyze.cpp:973
#11 0x00005555564e76d0 in resolve_decl_var (g=0x55555c3f9810, tld_var=0x55555c94c7c0)
    at /home/sam/repos/zig/src/analyze.cpp:3210
#12 0x00005555564e804c in resolve_top_level_decl (g=0x55555c3f9810, tld=0x55555c94c7c0, source_node=0x55555c67f0f0)
    at /home/sam/repos/zig/src/analyze.cpp:3397
#13 0x000055555647f050 in ir_analyze_decl_ref (ira=0x55555cdc0c30, source_instruction=0x55555cdbd110, tld=0x55555c94c7c0)
    at /home/sam/repos/zig/src/ir.cpp:17866
#14 0x000055555647fc08 in ir_analyze_instruction_field_ptr (ira=0x55555cdc0c30, field_ptr_instruction=0x55555cdbd110)
    at /home/sam/repos/zig/src/ir.cpp:18036
#15 0x000055555649ba23 in ir_analyze_instruction_base (ira=0x55555cdc0c30, instruction=0x55555cdbd110)
    at /home/sam/repos/zig/src/ir.cpp:25534
#16 0x000055555649c9ad in ir_analyze (codegen=0x55555c3f9810, old_exec=0x55555c6d1e08, new_exec=0x55555c6d1ef8,
    expected_type=0x55555c409730, expected_type_source_node=0x55555c67dfc0) at /home/sam/repos/zig/src/ir.cpp:25855
```
```
assert(type_entry->id == ZigTypeIdPointer);
```

**Comment by FireFox317** [comment]
This is now fixed! I'm not sure which commit actually solved this issue.
