### ISSUE TITLE
Compiler crash when trying to negate an error union

### ISSUE THREAD

**Issue by Yardanico** [ziglang/zig#3179]
Code to reproduce the problem:
```zig
fn retError() !f64 {
    return error.Overflow;
}

fn parse_factor() !f64 {
    return -retError();
}

pub fn main() !void {
    _ = try parse_factor();
}
```

Error message:
```
unreachable: /deps/zig/src/codegen.cpp:ir_render_un_op:3305
Unable to dump stack trace: Unable to open debug info: MissingDebugInfo
fish: “zig run tt.zig” terminated by signal SIGABRT (Abort)
```
(sorry I don't have a debugging version of the compiler)

**Comment by SamTebbs33** [comment]
Got a backtrace here
```
#1  0x0000000000f8adec in zig_panic (format=0x4d3f489 "unreachable: %s:%s:%d") at /home/samteb01/repos/zig/src/util.cpp:21
#2  0x0000000000ecc7e3 in ir_render_un_op (g=0x6bd7ac0, executable=0xd310e10, un_op_instruction=0xd316270)
    at /home/samteb01/repos/zig/src/codegen.cpp:3305
#3  0x0000000000ed6b6b in ir_render_instruction (g=0x6bd7ac0, executable=0xd310e10, instruction=0xd316270)
    at /home/samteb01/repos/zig/src/codegen.cpp:5835
#4  0x0000000000ed74c9 in ir_render (g=0x6bd7ac0, fn_entry=0xd310cf0) at /home/samteb01/repos/zig/src/codegen.cpp:6003
#5  0x0000000000edce76 in do_code_gen (g=0x6bd7ac0) at /home/samteb01/repos/zig/src/codegen.cpp:7287
#6  0x0000000000ee652d in codegen_build_and_link (g=0x6bd7ac0) at /home/samteb01/repos/zig/src/codegen.cpp:10014
#7  0x0000000000ebde17 in main (argc=3, argv=0x7fffffffe5c8) at /home/samteb01/repos/zig/src/main.cpp:1216
```
It's failing because only integers and floats are expected to be the operand of a unary op. Looks like another compiler error is needed when the operand isn't one of those.
