### ISSUE TITLE
usingnamespace segfaults the compiler

### ISSUE THREAD

**Issue by DutchGhost** [ziglang/zig#3329]
The following program segfaults:
```Zig
pub usingnamespace @import("root");

pub fn main() anyerror!void {
}
```

Zig version used: 0.4.0+805f9b30

```
Starting program: /home/ghost/zig-linux-x86_64-0.4.0+805f9b30/zig run src/main.zig

Program received signal SIGSEGV, Segmentation fault.
0x0000000008894b99 in add_symbols_from_container(CodeGen*, TldUsingNamespace*, TldUsingNamespace*, ScopeDecls*) ()
(gdb) backtrace
#0  0x0000000008894b99 in add_symbols_from_container(CodeGen*, TldUsingNamespace*, TldUsingNamespace*, ScopeDecls*) ()
#1  0x0000000008894c74 in add_symbols_from_container(CodeGen*, TldUsingNamespace*, TldUsingNamespace*, ScopeDecls*) ()
#2  0x0000000008894c74 in add_symbols_from_container(CodeGen*, TldUsingNamespace*, TldUsingNamespace*, ScopeDecls*) ()
#3  0x0000000008894c74 in add_symbols_from_container(CodeGen*, TldUsingNamespace*, TldUsingNamespace*, ScopeDecls*) ()
#4  0x0000000008894c74 in add_symbols_from_container(CodeGen*, TldUsingNamespace*, TldUsingNamespace*, ScopeDecls*) ()
#5  0x0000000008894c74 in add_symbols_from_container(CodeGen*, TldUsingNamespace*, TldUsingNamespace*, ScopeDecls*) ()
#6  0x0000000008894c74 in add_symbols_from_container(CodeGen*, TldUsingNamespace*, TldUsingNamespace*, ScopeDecls*) ()
#7  0x0000000008894c74 in add_symbols_from_container(CodeGen*, TldUsingNamespace*, TldUsingNamespace*, ScopeDecls*) ()
#8  0x0000000008894c74 in add_symbols_from_container(CodeGen*, TldUsingNamespace*, TldUsingNamespace*, ScopeDecls*) ()
#9  0x0000000008894c74 in add_symbols_from_container(CodeGen*, TldUsingNamespace*, TldUsingNamespace*, ScopeDecls*) ()
#10 0x0000000008894c74 in add_symbols_from_container(CodeGen*, TldUsingNamespace*, TldUsingNamespace*, ScopeDecls*) ()

.....
.....

#34923 0x0000000008894c74 in add_symbols_from_container(CodeGen*, TldUsingNamespace*, TldUsingNamespace*, ScopeDecls*) ()
#34924 0x00000000088b00f0 in semantic_analyze(CodeGen*) ()
#34925 0x0000000008809a58 in gen_root_source(CodeGen*) ()
#34926 0x000000000880a507 in codegen_build_and_link(CodeGen*) ()
#34927 0x000000000874dd90 in main ()
```

**Comment by andrewrk** [comment]
This now gives 

```
./test2.zig:1:5: error: import of 'main' overrides existing definition
pub usingnamespace @import("root");
    ^
./test2.zig:3:5: note: previous definition here
pub fn main() anyerror!void {}
    ^
/home/andy/dev/zig/lib/std/special/test_runner.zig:7:5: note: imported definition here
pub fn main() anyerror!void {
    ^
```
