### ISSUE TITLE
linking behavior tests for RISC-V results in silent failure due to LLD

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#3339]
```
[nix-shell:~/dev/zig/build]$ ./zig test ../test/stage1/behavior.zig -target riscv64-linux

[nix-shell:~/dev/zig/build]$ echo $?
1

[nix-shell:~/dev/zig/build]$ gdb ./zig -ex 'run test ../test/stage1/behavior.zig -target riscv64-linux'
(gdb) break _exit
Breakpoint 2 at 0x7ffff7955640
(gdb) run
Starting program: /home/andy/dev/zig/build/zig test ../test/stage1/behavior.zig -target riscv64-linux
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/6yaj6n8l925xxfbcd65gzqx3dz7idrnn-glibc-2.27/lib/libthread_db.so.1".
[New Thread 0x7ffff45ba700 (LWP 31451)]
[New Thread 0x7ffff3db9700 (LWP 31452)]
[New Thread 0x7ffff35b8700 (LWP 31453)]
[New Thread 0x7ffff2db7700 (LWP 31454)]
[New Thread 0x7ffff25b6700 (LWP 31455)]
[New Thread 0x7ffff1db5700 (LWP 31456)]
[New Thread 0x7ffff15b4700 (LWP 31457)]
[New Thread 0x7ffff0db3700 (LWP 31458)]
[New Thread 0x7fffe3fff700 (LWP 31459)]
[New Thread 0x7fffe37fe700 (LWP 31460)]
[New Thread 0x7fffe2ffd700 (LWP 31461)]
[New Thread 0x7fffe27fc700 (LWP 31462)]
[New Thread 0x7fffe1ffb700 (LWP 31463)]
[New Thread 0x7fffe17fa700 (LWP 31464)]
[New Thread 0x7fffe0ff9700 (LWP 31465)]
[New Thread 0x7fffdbfff700 (LWP 31466)]

Thread 1 "zig" hit Breakpoint 2, 0x00007ffff7955640 in _exit ()
   from /nix/store/6yaj6n8l925xxfbcd65gzqx3dz7idrnn-glibc-2.27/lib/libc.so.6
(gdb) up
#1  0x0000000002e6cf44 in lld::exitLld (val=1)
    at /home/andy/dev/zig/deps/lld/Common/ErrorHandler.cpp:61
61	  _exit(val);
(gdb) up
#2  0x0000000002e6da09 in lld::ErrorHandler::fatal (this=0x70b6420 <lld::errorHandler()::handler>, 
    msg=...) at /home/andy/dev/zig/deps/lld/Common/ErrorHandler.cpp:177
177	  exitLld(1);
(gdb) p msg
$1 = (const llvm::Twine &) @0x7fffffff8d80: {
  LHS = {
    twine = 0x560df88, 
    cString = 0x560df88 ".eh_frame: relocation is not in any piece", 
    stdString = 0x560df88, 
    stringRef = 0x560df88, 
    smallString = 0x560df88, 
    formatvObject = 0x560df88, 
    character = -120 '\210', 
    decUI = 90234760, 
    decI = 90234760, 
    decUL = 0x560df88, 
    decL = 0x560df88, 
    decULL = 0x560df88, 
    decLL = 0x560df88, 
    uHex = 0x560df88
  }, 
  RHS = {
    twine = 0x7ffff4bca930, 
    cString = 0x7ffff4bca930 "\024", 
    stdString = 0x7ffff4bca930, 
    stringRef = 0x7ffff4bca930, 
    smallString = 0x7ffff4bca930, 
    formatvObject = 0x7ffff4bca930, 
    character = 48 '0', 
    decUI = 4106004784, 
    decI = -188962512, 
    decUL = 0x7ffff4bca930, 
    decL = 0x7ffff4bca930, 
    decULL = 0x7ffff4bca930, 
    decLL = 0x7ffff4bca930, 
    uHex = 0x7ffff4bca930
  }, 
  LHSKind = llvm::Twine::CStringKind, 
  RHSKind = llvm::Twine::EmptyKind
}
(gdb) 
```

The next step here is to create a reduction and file a bug report upstream.

**Comment by LemonBoy** [comment]
I guess [this](https://reviews.llvm.org/rL366531) LLVM commit should fix the problem.

**Comment by andrewrk** [comment]
Yep this is solved in master branch, presumably with the merge of llvm10.
