### ISSUE TITLE
exporting main crashes the compiler

### ISSUE THREAD

**Issue by DutchGhost** [ziglang/zig#3659]
The following code
```Zig
pub extern const main: fn() void;

const builtin = @import("builtin");

comptime {
    @export("", main, builtin.GlobalLinkage.Strong);
}
```
crashes the compiler.

```
Starting program: /home/ghost/Documents/zig-linux-x86_64-0.5.0+ce70a9be2/zig run src/main.zig
Assertion failed at /deps/zig/src/ir.cpp:14995 in ir_analyze_instruction_export. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped

Program received signal SIGABRT, Aborted.
__restore_sigs (set=set@entry=0x7ffffffed2e0) at ./arch/x86_64/syscall_arch.h:40
40      ./arch/x86_64/syscall_arch.h: No such file or directory.
(gdb) backtrace
#0  __restore_sigs (set=set@entry=0x7ffffffed2e0) at ./arch/x86_64/syscall_arch.h:40
#1  0x000000000d11c274 in raise (sig=sig@entry=6) at src/signal/raise.c:11
#2  0x000000000d116098 in abort () at src/exit/abort.c:13
#3  0x00000000088dad76 in std.os.abort ()
#4  0x0000000000000000 in ?? ()
(gdb)
```

**Comment by DutchGhost** [comment]
On the latest master build, the code that fails is:
```Zig
pub extern const main: fn () void;

const builtin = @import("builtin");

comptime {
    @export(main, .{ .name = "main" });
}
```

**Comment by andrewrk** [comment]
Works now:

```
$ ../stage4/bin/zig run main.zig 
/home/andy/dev/zig/lib/std/start.zig:602:52: error: access of union field 'Fn' while field 'Pointer' is active
    switch (@typeInfo(@typeInfo(@TypeOf(root.main)).Fn.return_type.?)) {
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
/home/andy/dev/zig/lib/std/builtin.zig:204:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
/home/andy/dev/zig/lib/std/start.zig:551:12: note: called from here
    return @call(.always_inline, callMain, .{});
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/andy/dev/zig/lib/std/start.zig:501:36: note: called from here
    return initEventLoopAndCallMain();
           ~~~~~~~~~~~~~~~~~~~~~~~~^~
/home/andy/dev/zig/lib/std/start.zig:464:17: note: called from here
    std.os.exit(@call(.always_inline, callMainWithArgs, .{ argc, argv, envp }));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Test coverage for this wouldn't be interesting since it's a run-of-the-mill type error in start.zig.
