### ISSUE TITLE
Invalid source code crashes compiler rather than giving an error

### ISSUE THREAD

**Issue by qbradley** [ziglang/zig#3793]
typing a bit too fast, this minimal example crashed the compiler (syncd to commit f0d6447569e89a7b862da806a78da52d15160ef4 in master):

```zig
pub fn(main) void
}
```
replace `fn(main)` with `fn main()` fixed the issue but I was hoping for an error message instead :-)

Call stack:
```
Program received signal SIGSEGV, Segmentation fault.
add_source_file (g=g@entry=0x55555c30dd90, package=<optimized out>, resolved_path=resolved_path@entry=0x55555c332e30,
    source_code=source_code@entry=0x55555c3383c0, source_kind=source_kind@entry=SourceKindRoot) at /home/qbradley/src/zig/src/analyze.cpp:4806
(gdb) bt
#0  add_source_file (g=g@entry=0x55555c30dd90, package=<optimized out>, resolved_path=resolved_path@entry=0x55555c332e30,
    source_code=source_code@entry=0x55555c3383c0, source_kind=source_kind@entry=SourceKindRoot) at /home/qbradley/src/zig/src/analyze.cpp:4806
#1  0x0000555556338fcf in gen_root_source (g=g@entry=0x55555c30dd90) at /home/qbradley/src/zig/src/codegen.cpp:9223
#2  0x00005555563399e9 in codegen_build_and_link (g=0x55555c30dd90) at /home/qbradley/src/zig/src/codegen.cpp:10244
#3  0x000055555627c8e3 in main (argc=3, argv=0x7fffffffe458) at /home/qbradley/src/zig/src/main.cpp:1286
(gdb) list
4801                    assert(proto_node->type == NodeTypeFnProto);
4802                    Buf *proto_name = proto_node->data.fn_proto.name;
4803
4804                    bool is_pub = (proto_node->data.fn_proto.visib_mod == VisibModPub);
4805                    if (is_pub) {
4806                        if (buf_eql_str(proto_name, "main")) {
4807                            g->have_pub_main = true;
4808                        }
4809                    }
4810                }
(gdb) print proto_name
$1 = (Buf *) 0x0
```

**Comment by mikdusan** [comment]
I'll just add here that the bug manifests when main is looked for and _any_ fn has a missing name:

```zig
```
