### ISSUE TITLE
assert in hash_const_val hit with comptime struct

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#3801]
```zig
const Foo = struct {
    data: var = void,
    pub fn foo(comptime self: *Foo) void {}
};

var x = Foo{};
comptime { x.foo(); }
```

```
#7  0x00005555556c0898 in zig_assert (ok=false, file=0x5555558adc00 "/home/daurnimator/src/zig/src/analyze.cpp", line=5100, func=0x5555558afba8 "hash_const_val") at /home/daurnimator/src/zig/src/util.hpp:50
#8  0x00005555556d1550 in hash_const_val (const_val=0x555555a519e0) at /home/daurnimator/src/zig/src/analyze.cpp:5100
#9  0x00005555556d210f in fn_eval_hash (scope=0x555555a51b30) at /home/daurnimator/src/zig/src/analyze.cpp:5402
#10 0x00005555556910a5 in HashMap<Scope*, ZigValue*, &(fn_eval_hash(Scope*)), &(fn_eval_eql(Scope*, Scope*))>::key_to_index (this=0x55555597ecd0, key=@0x7fffffffb3d8: 0x555555a51b30) at /home/daurnimator/src/zig/src/hash_map.hpp:238
#11 0x000055555568ffdf in HashMap<Scope*, ZigValue*, &(fn_eval_hash(Scope*)), &(fn_eval_eql(Scope*, Scope*))>::internal_get (this=0x55555597ecd0, key=@0x7fffffffb3d8: 0x555555a51b30) at /home/daurnimator/src/zig/src/hash_map.hpp:223
#12 0x000055555568f35f in HashMap<Scope*, ZigValue*, &(fn_eval_hash(Scope*)), &(fn_eval_eql(Scope*, Scope*))>::maybe_get (this=0x55555597ecd0, key=@0x7fffffffb3d8: 0x555555a51b30) at /home/daurnimator/src/zig/src/hash_map.hpp:81
#13 0x00005555556556e7 in ir_analyze_fn_call (ira=0x555555a4a040, call_instruction=0x555555a49930, fn_entry=0x555555a4e910, fn_type=0x555555a4ff50, fn_ref=0x555555a50480, first_arg_ptr=0x555555a4e7e0, comptime_fn_call=true, fn_inline=FnInlineAuto) at /home/daurnimator/src/zig/src/ir.cpp:17270
#14 0x00005555556578ed in ir_analyze_instruction_call (ira=0x555555a4a040, call_instruction=0x555555a49930) at /home/daurnimator/src/zig/src/ir.cpp:17758
#15 0x000055555567c9ca in ir_analyze_instruction_base (ira=0x555555a4a040, instruction=0x555555a49930) at /home/daurnimator/src/zig/src/ir.cpp:27384
#16 0x000055555567d871 in ir_analyze (codegen=0x55555597eaf0, old_exec=0x555555a48d40, new_exec=0x555555a49f90, expected_type=0x5555559a1fc0, expected_type_source_node=0x0) at /home/daurnimator/src/zig/src/ir.cpp:27687
#17 0x00005555556402d8 in ir_eval_const_value (codegen=0x55555597eaf0, scope=0x5555559bbc60, node=0x5555559bdf40, expected_type=0x5555559a1fc0, backward_branch_count=0x7fffffffb8b8, backward_branch_quota=0x7fffffffb8c0, fn_entry=0x0, c_import_buf=0x0, source_node=0x5555559bdf40, exec_name=0x0, parent_exec=0x0, expected_type_source_node=0x0, undef_allowed=UndefBad) at /home/daurnimator/src/zig/src/ir.cpp:11588
#18 0x00005555556c4800 in analyze_const_value (g=0x55555597eaf0, scope=0x5555559bbc60, node=0x5555559bdf40, type_entry=0x5555559a1fc0, type_name=0x0, undef=UndefBad) at /home/daurnimator/src/zig/src/analyze.cpp:1104
#19 0x00005555556cc260 in resolve_decl_comptime (g=0x55555597eaf0, tld_comptime=0x5555559bbe40) at /home/daurnimator/src/zig/src/analyze.cpp:3455
#20 0x00005555556cdf27 in resolve_top_level_decl (g=0x55555597eaf0, tld=0x5555559bbe40, source_node=0x0, allow_lazy=false) at /home/daurnimator/src/zig/src/analyze.cpp:4038
#21 0x00005555556d0889 in semantic_analyze (g=0x55555597eaf0) at /home/daurnimator/src/zig/src/analyze.cpp:4836
#22 0x00005555556022d7 in gen_root_source (g=0x55555597eaf0) at /home/daurnimator/src/zig/src/codegen.cpp:9272
#23 0x000055555560605d in codegen_build_and_link (g=0x55555597eaf0) at /home/daurnimator/src/zig/src/codegen.cpp:10244
#24 0x00005555555d941b in main (argc=3, argv=0x7fffffffc208) at /home/daurnimator/src/zig/src/main.cpp:1342
```

**Comment by nektro** [comment]
updating the snippet to modern changes

```zig
const Foo = struct {
    data: anytype = void,
    pub fn foo(comptime self: *Foo) void {
        _ = self;
    }
};

var x = Foo{};
comptime {
    x.foo();
}

pub fn main() void {}
```

this now works

**Comment by Vexu** [comment]
Anytype fields have been removed.
