### ISSUE TITLE
Segfault / integer overflow in argument processing

### ISSUE THREAD

**Issue by pixelherodev** [ziglang/zig#3945]
I'm using the following to process arguments:

```zig

const TranspilerSettings = struct {
    print_all: bool,
    output_opts: bool,
    print_regmap: bool,
    backend: ?[]const u8,
    bootsector_name: ?[]const u8,
};

var settings = TranspilerSettings {
    .print_all = false,
    .output_opts = false,
    .print_regmap = false,
    .backend = null,
    .bootsector_name = null
};

...

pub fn main() void {

            inline while (index < @memberCount(TranspilerSettings)) : (index += 1) {
                if (std.mem.eql(u8, @memberName(TranspilerSettings, index), argument[2..])) {
                    const member_type = @TypeOf(@field(settings, @memberName(TranspilerSettings, index)));
                    if (member_type == bool) {
                        @field(settings, @memberName(TranspilerSettings, index)) = true;
                    }
                    else if (member_type == ?[]const u8) {
                        if (arg.next(allocator)) |_val| {
                            const val = _val catch unreachable;
                            @field(settings, @memberName(TranspilerSettings, index)) = val;
                        }
                        else {
                            @panic("No value provided to argument!");
                        }
                    }
                    good = true;
                    break;
                }
            }
            if (!good) {
                @panic("Unrecognized argument!\n");
            }
        }
        else if (path) |p| {
            @panic("Multiple paths given!");
        }
        else {
            path = std.mem.dupe(allocator, u8, argument) catch @panic("Out of memory");
        }
        allocator.free(argument);
    }
```

If only one `?[]const u8` is present in the TranspilerSettings structure, this works perfectly. If any more are added, it results in this: 

```
0x00007ffff04afd80 in llvm::BasicBlock::getContext() const () from /usr/lib/llvm/9/lib64/libLLVMCore.so.9
(gdb) bt
#0  0x00007ffff04afd80 in llvm::BasicBlock::getContext() const () from /usr/lib/llvm/9/lib64/libLLVMCore.so.9
#1  0x00007ffff0551219 in llvm::BranchInst::BranchInst(llvm::BasicBlock*, llvm::BasicBlock*, llvm::Value*, llvm::Instruction*) ()
   from /usr/lib/llvm/9/lib64/libLLVMCore.so.9
#2  0x00007ffff04e1718 in LLVMBuildCondBr () from /usr/lib/llvm/9/lib64/libLLVMCore.so.9
#3  0x0000555555a26c54 in ir_render_cond_br (g=0x55555668e340, executable=0x55555b269e60, cond_br_instruction=0x55555e33dc50)
    at /home/noam/Documents/Development/Builds/zig/src/codegen.cpp:3370
#4  0x0000555555a32d6a in ir_render_instruction (g=0x55555668e340, executable=0x55555b269e60, instruction=0x55555e33dc50)
    at /home/noam/Documents/Development/Builds/zig/src/codegen.cpp:6219
#5  0x0000555555a337cf in ir_render (g=0x55555668e340, fn_entry=0x55555b269de0) at /home/noam/Documents/Development/Builds/zig/src/codegen.cpp:6401
#6  0x0000555555a399d5 in do_code_gen (g=0x55555668e340) at /home/noam/Documents/Development/Builds/zig/src/codegen.cpp:7750
#7  0x0000555555a43ea2 in codegen_build_and_link (g=0x55555668e340) at /home/noam/Documents/Development/Builds/zig/src/codegen.cpp:10296
#8  0x0000555555a16edc in main (argc=5, argv=0x7fffffffdd58) at /home/noam/Documents/Development/Builds/zig/src/main.cpp:1295
```

Zig version: 0.5.0+4d54e9a4f

**Comment by pixelherodev** [comment]
I'd give this a better title but I'm not 100% sure what the cause is.

This *might* be a duplicate of another issue I vaguely remember seeing and commenting on, but I'm not certain.

**Comment by FireFox317** [comment]
Related or dupe of #2727 and #2604

**Comment by pixelherodev** [comment]
I haven't done any real work on the compiler, but would be more than willing to set aside time to look into this.

Any tips on how to get started looking into a bug like this?

**Comment by daurnimator** [comment]
Looks to be a dupe of #2727
