### ISSUE TITLE
Bitshifting on comptime @as() with a builtin produces a segfault

### ISSUE THREAD

**Issue by kprotty** [ziglang/zig#4024]
zig: `0.5.0+0fb3e6608`

example code:
```zig
pub fn main() void {
    const x = @as(usize, 1) << @alignOf(usize);
}
```

gdb backtrace:
```
#0  0x00007ffff1c273fc in bigint_fits_in_bits(BigInt const*, unsigned long, bool) ()
#1  0x00007ffff1bc57ea in ir_analyze_instruction_bin_op(IrAnalyze*, IrInstructionBinOp*) ()
#2  0x00007ffff1bcdf6a in ir_analyze_instruction_base(IrAnalyze*, IrInstruction*) ()
#3  0x00007ffff1bcfe20 in ir_analyze(CodeGen*, IrExecutable*, IrExecutable*, ZigType*, AstNode*) ()
#4  0x00007ffff1c1a103 in analyze_fn_body(CodeGen*, ZigFn*) [clone .part.0] ()
#5  0x00007ffff1c1c2fc in semantic_analyze(CodeGen*) ()
#6  0x00007ffff1b51327 in gen_root_source(CodeGen*) ()
#7  0x00007ffff1b6a20a in codegen_build_and_link(CodeGen*) ()
#8  0x00007ffff1aacba8 in main ()
```

**Comment by schmee** [comment]
You're in luck! 😄 https://github.com/ziglang/zig/pull/4023

**Comment by kprotty** [comment]
oh wow, the coincidence

**Comment by Vexu** [comment]
I spotted it in discord and then forgot to mention I fixed it.
