### ISSUE TITLE
Generating of docs is currently hitting an assert

### ISSUE THREAD

**Issue by FireFox317** [ziglang/zig#4488]
Running `zig test ../lib/std/std.zig -femit-docs -fno-emit-bin --override-lib-dir ../lib/` from the build directory results in an assertion:
**codegen.cpp:1838 in codegen_report_errors_and_exit**
```zig
void codegen_report_errors_and_exit(CodeGen *g) {
    assert(g->errors.length != 0);
...
```

Backtrace:
```gdb
(gdb) bt
#0  zig_panic (format=0x555556334158 "Assertion failed at %s:%d in %s. This is a bug in the Zig compiler.")
    at /home/timon/dev/zig/zig-source/src/util.cpp:14
#1  0x0000555555a71bf6 in zig_assert (ok=false, file=0x555556334380 "/home/timon/dev/zig/zig-source/src/codegen.cpp", line=1838, 
    func=0x555556334d80 "codegen_report_errors_and_exit") at /home/timon/dev/zig/zig-source/src/util_base.hpp:53
#2  0x0000555555a78c4a in codegen_report_errors_and_exit (g=0x5555567defc0) at /home/timon/dev/zig/zig-source/src/codegen.cpp:1838
#3  0x0000555555aa6b1e in anal_dump_value (ctx=0x7fffffffd5b0, source_node=0x555556df0600, ty=0x5555dd8565f0, value=0x5555dd7f4630)
    at /home/timon/dev/zig/zig-source/src/dump_analysis.cpp:671
#4  0x0000555555aa87cb in zig_print_analysis_dump (g=0x5555567defc0, f=0x55561dd37530, one_indent=0x5555563342ea "", 
    nl=0x5555563342ea "") at /home/timon/dev/zig/zig-source/src/dump_analysis.cpp:1270
#5  0x0000555555a9eecd in codegen_build_and_link (g=0x5555567defc0) at /home/timon/dev/zig/zig-source/src/codegen.cpp:10719
#6  0x0000555555a7000a in main0 (argc=7, argv=0x7fffffffdf38) at /home/timon/dev/zig/zig-source/src/main.cpp:1307
#7  0x0000555555a70485 in main (argc=7, argv=0x7fffffffdf38) at /home/timon/dev/zig/zig-source/src/main.cpp:1385
(gdb) up 3
#3  0x0000555555aa6b1e in anal_dump_value (ctx=0x7fffffffd5b0, source_node=0x555556df0600, ty=0x5555dd8565f0, value=0x5555dd7f4630)
    at /home/timon/dev/zig/zig-source/src/dump_analysis.cpp:671
671             codegen_report_errors_and_exit(ctx->g);
(gdb) p er
(gdb) p err
$1 = ErrorSemanticAnalyzeFail
(gdb) p source_node.owner.name
$2 = {list = {items = 0x555556ddf720 "meta", length = 5, capacity = 8}}
(gdb) p source_node.line
$4 = 73
```

Looks like it is unable to resolve
https://github.com/ziglang/zig/blob/master/lib/std/meta.zig#L74

**Comment by andrewrk** [comment]
Confirmed, I can reproduce it. Thanks
