### ISSUE TITLE
Slicing array fields of packed structs crashes the compiler

### ISSUE THREAD

**Issue by alexnask** [ziglang/zig#5235]
Testcase:  

```zig
const std = @import("std");

const S = packed struct {
    arr: [5]u8,
};

pub fn main() !void {
    var a: S = undefined;
    std.debug.warn("{}\n", .{a.arr[0..2]});
}
```  

gdb backtrace at crash:  
```
(gdb) run build-exe test.zig
Starting program: /mnt/c/dev/zig/build-linux/zig build-exe test.zig
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Code Generation [402/531] std.mem.bytesAsSlice...
Program received signal SIGSEGV, Segmentation fault.
0x000000000e1a9ca8 in llvm::PointerType::get(llvm::Type*, unsigned int) ()
(gdb) bt
#0  0x000000000e1a9ca8 in llvm::PointerType::get(llvm::Type*, unsigned int) ()
#1  0x000000000e0c6f9d in LLVMBuildInBoundsGEP ()
#2  0x000000000917be6f in ir_render_slice (g=0x10b026c0, executable=0x154005b0, instruction=0x154a6a60) at /mnt/c/dev/zig/src/codegen.cpp:5582
#3  0x000000000918041c in ir_render_instruction (g=0x10b026c0, executable=0x154005b0, instruction=0x154a6a60) at /mnt/c/dev/zig/src/codegen.cpp:6624
#4  0x0000000009180b21 in ir_render (g=0x10b026c0, fn_entry=0x15400530) at /mnt/c/dev/zig/src/codegen.cpp:6744
#5  0x00000000091871ea in do_code_gen (g=0x10b026c0) at /mnt/c/dev/zig/src/codegen.cpp:8144
#6  0x00000000091928f6 in codegen_build_and_link (g=0x10b026c0) at /mnt/c/dev/zig/src/codegen.cpp:10917
#7  0x0000000009161e1a in main0 (argc=3, argv=0x7ffffffedbf8) at /mnt/c/dev/zig/src/main.cpp:1671
#8  0x000000000916299e in main (argc=3, argv=0x7ffffffedbf8) at /mnt/c/dev/zig/src/main.cpp:1858
(gdb) q
```

**Comment by SpexGuy** [comment]
This is probably the same problem that's causing #5104.

**Comment by alexnask** [comment]
Yes, this is essentially a duplicate, I missed it when opening, should be more careful.
