### ISSUE TITLE
helloworld.zig with evented io never terminates

### ISSUE THREAD

**Issue by xxxbxxx** [ziglang/zig#5302]
hello!
This program never halts:

```zig
const std = @import("std");
pub const io_mode = .evented;
pub fn main() void {
    std.debug.warn("Hello, world!\n", .{});
}
```

gdb:

```gdb
[New LWP 20830]
[New LWP 20831]
[New LWP 20832]
[New LWP 20833]
[New LWP 20834]
[New LWP 20835]
[New LWP 20836]
[New LWP 20837]
Hello, world!
[LWP 20837 exited]
[LWP 20836 exited]
^C
Thread 1 "hello_mt" received signal SIGINT, Interrupt.
0x000000000022fa12 in std.os.linux.x86_64.syscall4 (number=futex, arg1=140737354100736, arg2=0, arg3=20830, arg4=0) at /usr/lib/zig/std/os/linux/x86_64.zig:42
42	    return asm volatile ("syscall"
(gdb) info threads 
  Id   Target Id            Frame 
* 1    LWP 20826 "hello_mt" 0x000000000022fa12 in std.os.linux.x86_64.syscall4 (number=futex, arg1=140737354100736, arg2=0, arg3=20830, arg4=0)
    at /usr/lib/zig/std/os/linux/x86_64.zig:42
  2    LWP 20830 "hello_mt" 0x0000000000235df9 in std.os.linux.x86_64.syscall6 (number=epoll_pwait, arg1=10, arg2=140737354100592, arg3=1, 
    arg4=18446744073709551615, arg5=0, arg6=128) at /usr/lib/zig/std/os/linux/x86_64.zig:75
  3    LWP 20831 "hello_mt" 0x0000000000235df9 in std.os.linux.x86_64.syscall6 (number=epoll_pwait, arg1=10, arg2=140737337315184, arg3=1, 
    arg4=18446744073709551615, arg5=0, arg6=128) at /usr/lib/zig/std/os/linux/x86_64.zig:75
  4    LWP 20832 "hello_mt" 0x0000000000235df9 in std.os.linux.x86_64.syscall6 (number=epoll_pwait, arg1=10, arg2=140737320529776, arg3=1, 
    arg4=18446744073709551615, arg5=0, arg6=128) at /usr/lib/zig/std/os/linux/x86_64.zig:75
  5    LWP 20833 "hello_mt" 0x0000000000235df9 in std.os.linux.x86_64.syscall6 (number=epoll_pwait, arg1=10, arg2=140737303744368, arg3=1, 
    arg4=18446744073709551615, arg5=0, arg6=128) at /usr/lib/zig/std/os/linux/x86_64.zig:75
  6    LWP 20834 "hello_mt" 0x0000000000235df9 in std.os.linux.x86_64.syscall6 (number=epoll_pwait, arg1=10, arg2=140737286958960, arg3=1, 
    arg4=18446744073709551615, arg5=0, arg6=128) at /usr/lib/zig/std/os/linux/x86_64.zig:75
  7    LWP 20835 "hello_mt" 0x0000000000235df9 in std.os.linux.x86_64.syscall6 (number=epoll_pwait, arg1=10, arg2=140737270173552, arg3=1, 
    arg4=18446744073709551615, arg5=0, arg6=128) at /usr/lib/zig/std/os/linux/x86_64.zig:75
(gdb) bt 
#0  0x000000000022fa12 in std.os.linux.x86_64.syscall4 (number=futex, arg1=140737354100736, arg2=0, arg3=20830, arg4=0)
    at /usr/lib/zig/std/os/linux/x86_64.zig:42
#1  0x000000000023dec2 in std.os.linux.futex_wait (uaddr=0x7ffff7ff7000, futex_op=0, val=20830, timeout=0x0) at /usr/lib/zig/std/os/linux.zig:117
#2  0x00000000002418a6 in std.thread.Thread.wait (self=0x7ffff7ff7000) at /usr/lib/zig/std/thread.zig:93
#3  0x000000000022f91a in std.event.loop.Loop.run (self=0x25e7b8 <global_instance_state>) at /usr/lib/zig/std/event/loop.zig:639
#4  0x0000000000206b82 in std.start.initEventLoopAndCallMain () at /usr/lib/zig/std/start.zig:218
#5  std.start.callMainWithArgs (argc=1, argv=0x7fffffffe698, envp=...) at /usr/lib/zig/std/start.zig:188
#6  std.start.posixCallMainAndExit () at /usr/lib/zig/std/start.zig:179
#7  0x0000000000206710 in std.start._start () at /usr/lib/zig/std/start.zig:123
(gdb) thread 2
[Switching to thread 2 (LWP 20830)]
#0  0x0000000000235df9 in std.os.linux.x86_64.syscall6 (number=epoll_pwait, arg1=10, arg2=140737354100592, arg3=1, arg4=18446744073709551615, arg5=0, arg6=128)
    at /usr/lib/zig/std/os/linux/x86_64.zig:75
75	    return asm volatile ("syscall"
(gdb) bt
#0  0x0000000000235df9 in std.os.linux.x86_64.syscall6 (number=epoll_pwait, arg1=10, arg2=140737354100592, arg3=1, arg4=18446744073709551615, arg5=0, arg6=128)
    at /usr/lib/zig/std/os/linux/x86_64.zig:75
#1  0x0000000000259f94 in std.os.linux.epoll_pwait (epoll_fd=10, events=0x7ffff7ff6f70, maxevents=1, timeout=-1, sigmask=0x0)
    at /usr/lib/zig/std/os/linux.zig:1116
#2  0x0000000000255b2c in std.os.linux.epoll_wait (epoll_fd=10, events=0x7ffff7ff6f70, maxevents=1, timeout=-1) at /usr/lib/zig/std/os/linux.zig:1112
#3  0x000000000024f000 in std.os.epoll_wait (epfd=10, events=..., timeout=-1) at /usr/lib/zig/std/os.zig:2449
#4  0x000000000024824b in std.event.loop.Loop.workerRun (self=0x25e7b8 <global_instance_state>) at /usr/lib/zig/std/event/loop.zig:960
#5  0x000000000024f0c4 in std.thread.MainFuncs.linuxThreadMain (ctx_addr=140737354100760) at /usr/lib/zig/std/thread.zig:230
#6  0x000000000025d73f in clone () at c.zig:242
#7  0x000000000000515e in ?? ()
#8  0x00007ffff6ff6000 in ?? ()
#9  0x0000000001002000 in ?? ()
#10 0x000000000025e7b8 in elf_aux_maybe ()
#11 0x0000000000000000 in ?? ()
```

Same behaviour in windows,
and same behaviour with a program that actually does something with the threads
(like my little test program: https://github.com/xxxbxxx/zig-mandelbrot-explorer )

maybe duplicate of https://github.com/ziglang/zig/issues/4922 ?

**Comment by xxxbxxx** [comment]
> Same behaviour in windows,

my mistake.  the reduced hello world test does exit properly on windows.
The lockup does happen on windows, but it does seem to require a more complex scenario.
