### ISSUE TITLE
Yet another segfault

### ISSUE THREAD

**Issue by pixelherodev** [ziglang/zig#5488]
The code at https://gist.github.com/iamgreaser/3565c00da57f7b7ab6962e3a1bf6427c produces a compiler segfault with 0.6 and with master.
```
Code Generation [286/654] std.mem.Allocator.free...[1]    12593 segmentation fault  /usr/local/bin/zig build-exe src/script/main.zig
```

```gdb
0x00007ffff5982774 in llvm::PointerType::get(llvm::Type*, unsigned int) ()
(gdb) bt
#0  0x00007ffff5982774 in llvm::PointerType::get(llvm::Type*, unsigned int) ()
#1  0x00007ffff58a44c2 in LLVMBuildStructGEP ()
#2  0x00007ffff0df9fd9 in ir_render_union_field_ptr(CodeGen*, IrExecutableGen*, IrInstGenUnionFieldPtr*) [clone .isra.0] ()
#3  0x00007ffff0e0287d in ir_render_instruction(CodeGen*, IrExecutableGen*, IrInstGen*) [clone .isra.0] ()
#4  0x00007ffff0e0395b in do_code_gen(CodeGen*) ()
#5  0x00007ffff0e0a60c in codegen_build_and_link(CodeGen*) ()
#6  0x00007ffff0dde840 in main0(int, char**) ()
#7  0x00007ffff0d4f037 in main ()
```

Closest issue I could find was #3128 which was already fixed.

**Comment by Vexu** [comment]
No longer crashes.
