### ISSUE TITLE
Compiler Segmentation Fault

### ISSUE THREAD

**Issue by kliberty** [ziglang/zig#5980]
I produced some code that causes a `Segmentation Fault` on compile (trying to access address 0x0). Version 0.6.0+4abf119d9. I was trying to see if I could get the compiler to let me get around the dynamic dispatch restriction, though s I understand it I think the code below should probably fail compilation with a message about illegal behavior.

```zig
const std = @import("std");

const allocator = std.heap.page_allocator;
const cwd = std.fs.cwd();

var _output_writer = output_writer_file;
var file: std.fs.File = undefined;

fn output_writer(comptime fmt: []const u8, obj: anytype) void {
    switch (_output_writer) {
        output_writer_file => {
            output_writer_file(fmt, obj);
        },
        output_writer_stdout => {
            output_writer_stdout(fmt, obj);
        },
        else => {
            unreachable;
        },
    }
}

fn output_writer_stdout(comptime fmt: []const u8, obj: anytype) void {
    comptime var print = std.io.getStdOut().writer().print;

    print(fmt, obj) catch unreachable;
}


fn output_writer_file(comptime fmt: []const u8, obj: anytype) void {
    var buffer: [1024 * 4]u8 = undefined;

    var out = std.fmt.bufPrint(buffer[0..], fmt, obj) catch unreachable;
    file.writeAll(out) catch unreachable;
}

pub fn main() anyerror!void {
    file = try cwd.createFile("b3.txt", std.fs.File.CreateFlags{});
    output_writer("Hello\n", .{});
}
```

**Comment by joachimschmidt557** [comment]
In case it helps, the backtrace created with gdb: 

```
#0  0x00007ffff377fa70 in llvm::Value::getContext() const () from /nix/store/i4qi8m45w705c5h74di003lljwbx9a8m-llvm-10.0.0-lib/lib/libLLVM-10.so
#1  0x00007ffff370446e in llvm::SwitchInst::SwitchInst(llvm::Value*, llvm::BasicBlock*, unsigned int, llvm::Instruction*) ()
   from /nix/store/i4qi8m45w705c5h74di003lljwbx9a8m-llvm-10.0.0-lib/lib/libLLVM-10.so
#2  0x00007ffff367ec4c in LLVMBuildSwitch () from /nix/store/i4qi8m45w705c5h74di003lljwbx9a8m-llvm-10.0.0-lib/lib/libLLVM-10.so
#3  0x0000000000785fed in ir_render_instruction(CodeGen*, IrExecutableGen*, IrInstGen*) [clone .isra.0] ()
#4  0x0000000000787cfb in do_code_gen(CodeGen*) ()
#5  0x0000000000789874 in codegen_build_and_link(CodeGen*) ()
#6  0x000000000075da16 in main0(int, char**) ()
#7  0x0000000000750947 in main ()
```

Seems like some error with the switch statement.

**Comment by Vexu** [comment]
Reduction:
```zig
fn foo(comptime a: u32) void {}
var bar = foo;

pub export fn entry() void {
    switch (bar) {
        foo => unreachable,
        else => unreachable,
    }
}
```

This seems to also cause a quite consistent integer overflow in the stack trace dumping code:
```
Segmentation fault at address 0x0
???:?:?: 0x7fa9e6461bc0 in ??? (???)
integer overflow
/lib/std/debug.zig:139:69: 0x556360f56585 in std.debug.dumpStackTraceFromBase (zigstage2)
            printSourceAtAddress(debug_info, stderr, return_address - 1, tty_config) catch return;
                                                                    ^
/lib/std/debug.zig:1771:35: 0x556360ed32c5 in std.debug.handleSegfaultLinux (zigstage2)
            dumpStackTraceFromBase(bp, ip);
                                  ^
```

**Comment by kliberty** [comment]
Does this imply that there is first an error in LLVM regarding the switch statement, and then an integer overflow when trying to print the backtrace?

**Comment by Vexu** [comment]
Duplicate of #7357
