### ISSUE TITLE
Compiler sigsegv when compile a switch statement

### ISSUE THREAD

**Issue by codehz** [ziglang/zig#6286]
zig version: 0.6.0+a496f94be

since it is hard to repro, I can only paste the gdb result:

```
Starting program: /root/soft/zig/zig test src/ecs.zig
Semantic Analysis [1550/1587] 
Program received signal SIGSEGV, Segmentation fault.
0x000000000d33ddf0 in llvm::BasicBlock::getContext() const ()
(gdb) bt
#0  0x000000000d33ddf0 in llvm::BasicBlock::getContext() const ()
#1  0x000000000d3e813f in llvm::BranchInst::BranchInst(llvm::BasicBlock*, llvm::Instruction*) ()
#2  0x000000000d3735f2 in LLVMBuildBr ()
#3  0x00000000088ab01c in ir_render_instruction(CodeGen*, IrExecutableGen*, IrInstGen*) [clone .isra.0] ()
#4  0x00000000088ac23b in do_code_gen(CodeGen*) ()
#5  0x00000000088addcc in codegen_build_and_link(CodeGen*) ()
#6  0x0000000008883a99 in main0(int, char**) ()
#7  0x00000000087f0b07 in main ()
```

and a part of code (but it works if I put it into a new file... so the thing is really weird)
```zig
switch (std.math.order(current, e)) {
    .eq => {},
    .lt => {
         if (!iter.jump(e)) {
              continue :out;
         }
     },
     .gt => return null,
}
```

**Comment by Vexu** [comment]
Not reproducible.
