### ISSUE TITLE
@typeName fails on TypeInfo.StructField.field_type if the struct field is declared as anytype

### ISSUE THREAD

**Issue by tyrion** [ziglang/zig#7740]
`TypeInfo.StructField.field_type` has type `type`, so it should be possible to pass it to `@typeName`. However this is not the case if a struct is declared with a field of type `anytype`.

You can reproduce the error with the following code:

```zig
const std = @import("std");
const print = std.debug.print;

pub fn printType(comptime t: type) void {
    switch(@typeInfo(t)) {
        .Struct => |s| printStruct(s),
        else => @compileError("Only struct supported"),
    }
}

pub fn printStruct(comptime s: std.builtin.TypeInfo.Struct) void {
    print("struct {{\n", .{});
    inline for (s.fields) |field| {
        if (field.is_comptime) {
            print("comptime ", .{});
        }
        print("  ({}) {s}: {s} = {}\n", .{
            field.alignment,
            field.name,
            @typeName(field.field_type),
            field.default_value,
        });
    }
    print("}}", .{});
}

const TestStruct = struct{
    name: []const u8,
    type: type,
    optional: bool = true,
    // Uncomment the following line and it crashes
    // default: anytype = null,
};

pub fn main() !void {
    printType(TestStruct);
}
```

**Comment by CoolRustacean** [comment]
I ran the above program through GDB, and got this:
```GDB
(gdb) bt
#0  0x000000000294ee5b in type_bare_name(ZigType*) ()
#1  0x000000000297e913 in ir_analyze_instruction_base(IrAnalyze*, IrInstSrc*) ()
#2  0x0000000002976a93 in ir_analyze(CodeGen*, IrExecutableSrc*, IrExecutableGen*, ZigType*, AstNode*, ZigValue*) ()
#3  0x000000000293e57b in analyze_fn_body(CodeGen*, ZigFn*) ()
#4  0x000000000293fae7 in semantic_analyze(CodeGen*) ()
#5  0x00000000029043d0 in codegen_build_object(CodeGen*) ()
#6  0x00000000028fc75e in zig_stage1_build_object ()
#7  0x00000000025cc741 in Compilation.performAllTheWork ()
#8  0x00007ffff7ffa670 in ?? ()
#9  0x0000000000000000 in ?? ()
```

**Comment by Vexu** [comment]
Anytype fields have been removed.
