### ISSUE TITLE
Assertion failure in LLVM

### ISSUE THREAD

**Issue by jsbert** [ziglang/zig#8029]
Attempting to compile this program triggers an assertion failure in LLVM:

```Zig
fn foo() error{SomeError}!void {
    return error.SomeError;
}

pub fn main() void {
    inline for ("00") |_| {
        if (foo()) |_| {} else |err| switch (err) {
            error.SomeError => {},
        }
    }
}
```

```
$ zig build-exe bug.zig
Code Generation [449/543] std.mem.Allocator.free... zig: /home/build/llvm-project/llvm/lib/IR/Instructions.cpp:3911: void llvm::SwitchInst::init(llvm::Value*, llvm::BasicBlock*, unsigned int): Assertion `Value && Default && NumReserved' failed.
```

LLVM version is 11.0.1. Zig version is `68e772647` (also occurs in 0.7.1).

gdb backtrace of `zig build-exe bug.zig`:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7a81859 in __GI_abort () at abort.c:79
#2  0x00007ffff7a81729 in __assert_fail_base (
    fmt=0x7ffff7c17588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x555565cdee30 "Value && Default && NumReserved",
    file=0x555565cd9370 "/home/build/llvm-project/llvm/lib/IR/Instructions.cpp", line=3911,
    function=<optimized out>) at assert.c:92
#3  0x00007ffff7a92f36 in __GI___assert_fail (
    assertion=0x555565cdee30 "Value && Default && NumReserved",
    file=0x555565cd9370 "/home/build/llvm-project/llvm/lib/IR/Instructions.cpp", line=3911,
    function=0x555565cdede0 "void llvm::SwitchInst::init(llvm::Value*, llvm::BasicBlock*, unsigned int)") at assert.c:101
#4  0x0000555560c46ad8 in llvm::SwitchInst::init (this=0x555570e71278, Value=0x55557071c9e0,
    Default=0x0, NumReserved=4) at /home/build/llvm-project/llvm/lib/IR/Instructions.cpp:3911
#5  0x0000555560c46bc3 in llvm::SwitchInst::SwitchInst (this=0x555570e71278,
    Value=0x55557071c9e0, Default=0x0, NumCases=1, InsertBefore=0x0)
    at /home/build/llvm-project/llvm/lib/IR/Instructions.cpp:3928
#6  0x00005555592f08bc in llvm::SwitchInst::Create (Value=0x55557071c9e0, Default=0x0,
    NumCases=1, InsertBefore=0x0)
    at /home/build/llvm-project/llvm/include/llvm/IR/Instructions.h:3296
#7  0x00005555594b52bd in llvm::IRBuilderBase::CreateSwitch (this=0x555568eedb10,
    V=0x55557071c9e0, Dest=0x0, NumCases=1, BranchWeights=0x0, Unpredictable=0x0)
    at /home/build/llvm-project/llvm/include/llvm/IR/IRBuilder.h:984
#8  0x0000555560b64327 in LLVMBuildSwitch (B=0x555568eedb10, V=0x55557071c9e0, Else=0x0,
    NumCases=1) at /home/build/llvm-project/llvm/lib/IR/Core.cpp:3111
#9  0x0000555558f54d93 in ir_render_switch_br (g=0x555568ee0060, executable=0x55556e7470d0,
    instruction=0x55556f1924a0) at /home/build/zig/src/stage1/codegen.cpp:5118
#10 0x0000555558f5c324 in ir_render_instruction (g=0x555568ee0060, executable=0x55556e7470d0,
    instruction=0x55556f1924a0) at /home/build/zig/src/stage1/codegen.cpp:6818
#11 0x0000555558f5cbef in ir_render (g=0x555568ee0060, fn_entry=0x55556e747050)
    at /home/build/zig/src/stage1/codegen.cpp:6970
#12 0x0000555558f634de in do_code_gen (g=0x555568ee0060)
    at /home/build/zig/src/stage1/codegen.cpp:8397
#13 0x0000555558f683da in codegen_build_object (g=0x555568ee0060)
    at /home/build/zig/src/stage1/codegen.cpp:9568
#14 0x0000555558f3968a in zig_stage1_build_object (stage1=0x555568ee0060)
    at /home/build/zig/src/stage1/stage1.cpp:130
#15 0x00005555588109e5 in Module.build_object (mod=0x555568ee0060)
    at /home/build/zig/src/stage1.zig:143
#16 0x000055555869fd30 in Compilation.updateStage1Module (comp=0x555568edbb58,
    main_progress_node=0x7fffffff8d30) at /home/build/zig/src/Compilation.zig:3331
#17 0x000055555865d303 in Compilation.performAllTheWork (self=0x555568edbb58)
    at /home/build/zig/src/Compilation.zig:1783
#18 0x0000555558657ca3 in Compilation.update (self=0x555568edbb58)
    at /home/build/zig/src/Compilation.zig:1371
#19 0x00005555585edf90 in main.updateModule (gpa=0x555568dc8010 <c_allocator_state>,
    comp=0x555568edbb58, hook=...) at /home/build/zig/src/main.zig:2082
#20 0x0000555558537f11 in main.buildOutputType (gpa=0x555568dc8010 <c_allocator_state>,
    arena=0x7fffffffe858, all_args=..., arg_mode=...) at /home/build/zig/src/main.zig:1923
#21 0x000055555850e61d in main.mainArgs (gpa=0x555568dc8010 <c_allocator_state>,
    arena=0x7fffffffe858, args=...) at /home/build/zig/src/main.zig:170
#22 0x000055555850e03f in main (argc=3, argv=0x7fffffffea98)
    at /home/build/zig/src/stage1.zig:45
```
</details>

**Comment by mikdusan** [comment]
llvm assertion failure is gone with recent compiler

```sh
$ llvm-config --version --build-mode --assertion-mode
15.0.6
debug
ON

$ zig version
0.11.0-dev.1026+4172c2916

$ zig build-obj bug1.zig
# no stdout/stderr (good)
```
