### ISSUE TITLE
Compiler segfault with optional recursive struct

### ISSUE THREAD

**Issue by mguaypaq** [ziglang/zig#8121]
The recursive data type in this example causes a compiler segfault on 0.7.0:

```zig
pub fn main() !void {
    var sf: SegFaulty() = undefined;
}

fn SegFaulty() type {
    return ?struct { f: SegFaulty() };
}
```

I know it's a very contrived type definition, but I got there by minimizing a bigger example where I was trying some kind of linked list data type.

I also tried this in a more recent commit of this repo that I had already built, and got the following (start of a) stack trace from GDB, in case that's helpful:

```gdb
#0  __vfprintf_internal (s=s@entry=0x7fffff7ff570, 
    format=format@entry=0x5555586a7da1 "(", ap=ap@entry=0x7fffff7ff718, 
    mode_flags=mode_flags@entry=0) at vfprintf-internal.c:1365
#1  0x00007ffff2a329c6 in __vsnprintf_internal (string=0x7fffff7ff660 "", 
    maxlen=<optimized out>, format=0x5555586a7da1 "(", args=0x7fffff7ff718, 
    mode_flags=0) at vsnprintf.c:114
#2  0x0000555556858f9e in buf_appendf (buf=0x555560572400, 
    format=0x5555586a7da1 "(")
    at /home/mguaypaq/code/zig/src/stage1/buffer.cpp:46
#3  0x00005555568c7667 in get_anon_type_name (codegen=0x555558fa9ae0, 
    exec=0x555560571880, kind_name=0x5555586b2d58 "struct", 
    scope=0x5555605722a0, source_node=0x555559003310, 
    out_bare_name=0x5555605723c0)
    at /home/mguaypaq/code/zig/src/stage1/ir.cpp:9842
#4  0x00005555568c77d1 in ir_gen_container_decl (irb=0x7fffff800080, 
    parent_scope=0x5555605722a0, node=0x555559003310)
    at /home/mguaypaq/code/zig/src/stage1/ir.cpp:9863
#5  0x00005555568c9518 in ir_gen_node_raw (irb=0x7fffff800080, 
    node=0x555559003310, scope=0x5555605722a0, lval=LValNone, 
    result_loc=0x555560572350)
    at /home/mguaypaq/code/zig/src/stage1/ir.cpp:10310
#6  0x00005555568c99b4 in ir_gen_node_extra (irb=0x7fffff800080, 
    node=0x555559003310, scope=0x5555605722a0, lval=LValNone, 
    result_loc=0x555560572350)
    at /home/mguaypaq/code/zig/src/stage1/ir.cpp:10448
#7  0x00005555568be73e in ir_gen_prefix_op_id_lval (irb=0x7fffff800080, 
    scope=0x5555605722a0, node=0x555559003260, op_id=IrUnOpOptional, 
    lval=LValNone) at /home/mguaypaq/code/zig/src/stage1/ir.cpp:7688
#8  0x00005555568be7b1 in ir_gen_prefix_op_id (irb=0x7fffff800080, 
    scope=0x5555605722a0, node=0x555559003260, op_id=IrUnOpOptional)
    at /home/mguaypaq/code/zig/src/stage1/ir.cpp:7696
#9  0x00005555568bf01b in ir_gen_prefix_op_expr (irb=0x7fffff800080, 
    scope=0x5555605722a0, node=0x555559003260, lval=LValNone, 
    result_loc=0x555560571a90)
    at /home/mguaypaq/code/zig/src/stage1/ir.cpp:7861
#10 0x00005555568c8e11 in ir_gen_node_raw (irb=0x7fffff800080, 
    node=0x555559003260, scope=0x5555605722a0, lval=LValNone, 
    result_loc=0x555560571a90)
    at /home/mguaypaq/code/zig/src/stage1/ir.cpp:10214
#11 0x00005555568c99b4 in ir_gen_node_extra (irb=0x7fffff800080, 
    node=0x555559003260, scope=0x5555605722a0, lval=LValNone, 
    result_loc=0x555560571a90)
    at /home/mguaypaq/code/zig/src/stage1/ir.cpp:10448
#12 0x00005555568b321d in ir_gen_return (irb=0x7fffff800080, 
    scope=0x5555605722a0, node=0x555559003620, lval=LValNone, 
    result_loc=0x555560572320)
...
```

**Comment by mikdusan** [comment]
compiler no longer segfaults

```sh
$zig version
0.11.0-dev.1026+4172c2916

$ zig build-obj ok1.zig
ok1.zig:7:13: error: struct 'ok1.SegFaulty__struct_2903' depends on itself
    return ?struct { f: SegFaulty() };
            ^~~~~~~~~~~~~~~~~~~~~~~~~
ok1.zig:7:22: note: while checking this field
    return ?struct { f: SegFaulty() };
                     ^~~~~~~~~~~~~~
```
