### ISSUE TITLE
SIGBUS in codegen while generating comptime value

### ISSUE THREAD

**Issue by mattnite** [ziglang/zig#8320]
I'm using okredis and I'm getting SIGBUS due to the following code:
```zig
    const reply = try client.trans(struct {
        id: void,
        user: void,
    }, .{
        .{ "SET", keys.id, username },
        HSET.init(keys.user, &[_]FV{
            .{ .field = "id", .value = id },
            .{ .field = "email", .value = username },
        }),
    });
```
if I comment out this piece of code we're fine:
```zig
    const reply = try client.trans(struct {
        id: void,
        user: void,
    }, .{
        .{ "SET", keys.id, username },
        //HSET.init(keys.user, &[_]FV{
        //    .{ .field = "id", .value = id },
        //    .{ .field = "email", .value = username },
        //}),
    });
```
[here](https://github.com/kristoff-it/zig-okredis/blob/808585f27b5896ee349327ca0a753d330f7195cb/src/client.zig#L103) is where the okredis code is.

and here is the backtrace I get:
```
Code Generation [817/2399] .okredis.serializer.CommandSerializer.serializeCommand...... 
Thread 1 "zig" received signal SIGBUS, Bus error.
[Switching to LWP 14557]
0x000000000285430d in gen_const_val(CodeGen*, ZigValue*, char const*) ()
(gdb) bt
#0  0x000000000285430d in gen_const_val(CodeGen*, ZigValue*, char const*) ()
#1  0x0000000002855323 in gen_const_val_ptr(CodeGen*, ZigValue*, char const*) ()
#2  0x000000000284a7e1 in ir_llvm_value(CodeGen*, IrInstGen*) ()
#3  0x000000000285c524 in ir_render_instruction(CodeGen*, IrExecutableGen*, IrInstGen*) ()
#4  0x00000000028503f6 in do_code_gen(CodeGen*) ()
#5  0x000000000284c2ae in codegen_build_object(CodeGen*) ()
#6  0x0000000002843f7e in zig_stage1_build_object ()
#7  0x00000000025d5b81 in Compilation.performAllTheWork ()
#8  0x00007ffff7f8a428 in ?? ()
#9  0x0000000000000000 in ?? ()
```

**Comment by jean-dao** [comment]
Similar backtrace with the following self contained program:
```zig
const Obj = struct {
    // compiles if not optional or not array
    a: [1]?u32,
    b: u32 = 0,
};

// compiles if dummy not comptime or removed
fn func(comptime dummy: u32, obj: Obj) void {
    _ = dummy;
    _ = obj;
}

pub fn main() void {
    // compiles if c const
    var c: u32 = 0;

    func(0, .{
        .a = [1]?u32{42},
        .b = c,
    });
}
```

```
$ zig-linux-x86_64-0.9.0-dev.897+81e2034d4/zig build-exe buserror.zig 
Bus error (core dumped)
```

```c++
#0  0x0000000002dd29fe in gen_const_val(CodeGen*, ZigValue*, char const*) ()
#1  0x0000000002dd434a in gen_parent_ptr(CodeGen*, ZigValue*, ConstParent*) ()
#2  0x0000000002dd420f in gen_const_ptr_struct_recursive(CodeGen*, ZigValue*, unsigned long) ()
#3  0x0000000002dd3998 in gen_const_val_ptr(CodeGen*, ZigValue*, char const*) ()
#4  0x0000000002dc8d80 in ir_llvm_value(CodeGen*, Stage1AirInst*) ()
#5  0x0000000002dda7ac in ir_render_instruction(CodeGen*, Stage1Air*, Stage1AirInst*) ()
#6  0x0000000002dce8eb in do_code_gen(CodeGen*) ()
#7  0x0000000002dca5be in codegen_build_object(CodeGen*) ()
#8  0x0000000002dc226d in zig_stage1_build_object ()
#9  0x0000000002a6e1d1 in Compilation.update ()
#10 0x00007f39d85c8298 in ?? ()
#11 0x0000000000000000 in ?? ()
```
